// AUTO-GENERATED form names for the eight non-English languages.
// Regenerate with tools/gen_formnames.py (needs a PKHeX checkout + .NET SDK).
// Sources: PokeAPI where it has the games' own wording -- form_names first, then
// names reduced to a label by removing the species -- else PKHeX's own label, from
// FormConverter.GetFormList unioned across EntityContexts, PKHeX commit fd213a27db65d6223bcf47935e36c7d375e04b7b.
//
// PKHeX IS TERSE ONLY IN THE LATIN LANGUAGES. It drops the head noun there -- "Alola"
// for the games' "Forme d'Alola" / "Alola-Form" -- which is why PokeAPI is preferred.
// Its Japanese, Korean and BOTH Chinese are already the games' full wording, so those
// columns are largely PKHeX's; PokeAPI carries no Chinese form names at all.
//
// Arceus and Silvally are absent on purpose: getTypeName() already names their forms
// in every language, and a row here would shadow it.
//
// ENGLISH IS DELIBERATELY ABSENT. PKSE's English names live in FormNames.cpp and are
// closer to the games than PKHeX's terse dropdown labels -- "Alolan" not "Alola",
// "Plant Cloak" not "Plant". getFormName() asks English first and only consults this
// table for another language, so the two can never disagree about which forms exist.
#include <cstddef>
#include <cstdint>

#include "Names/FormNames.h"
#include "Names/NameLanguage.h"

namespace Names
{
    namespace
    {
        struct LocalizedFormName
        {
            uint16_t species;
            uint8_t form;
            const char *names[LANGUAGE_COUNT];
        };

        // Sorted by (species, form) so the lookup can binary-search.
        const LocalizedFormName LOCALIZED_FORM_NAMES[] = {
            {   3,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            {   3,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            {   6,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            {   6,  1, {"メガＸ", nullptr, "Méga X", "Mega X", "Mega X", "Mega X", "메가X", "超级 Ｘ", "Mega Ｘ"}},
            {   6,  2, {"メガＹ", nullptr, "Méga Y", "Mega Y", "Mega Y", "Mega Y", "메가Y", "超级 Ｙ", "Mega Ｙ"}},
            {   9,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            {   9,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            {  15,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            {  15,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            {  18,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            {  18,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            {  19,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            {  19,  1, {"アローラのすがた", nullptr, "Forme d’Alola", "Forma di Alola", "Alola-Form", "Forma de Alola",
                        "알로라의 모습", "阿罗拉的样子", "阿羅拉的樣子"}},
            {  20,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            {  20,  1, {"アローラのすがた", nullptr, "Forme d’Alola", "Forma di Alola", "Alola-Form", "Forma de Alola",
                        "알로라의 모습", "阿罗拉的样子", "阿羅拉的樣子"}},
            {  20,  2, {"おおきいサイズ", nullptr, "Maxi", "Grande", "L", "Grande", "큰 사이즈", "大尺寸", "大尺寸"}},
            {  25,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            {  25,  1, {"オリジナルキャップ", nullptr, "Casquette Originale", "Berretto Originale", "Original-Kappe",
                        "Gorra Original", "오리지널캡", "初始帽子", "初始帽子"}},
            {  25,  2, {"ホウエンキャップ", nullptr, "Casquette de Hoenn", "Berretto Hoenn", "Hoenn-Kappe",
                        "Gorra Hoenn", "호연캡", "丰缘帽子", "豐緣帽子"}},
            {  25,  3, {"シンオウキャップ", nullptr, "Casquette de Sinnoh", "Berretto Sinnoh", "Sinnoh-Kappe",
                        "Gorra Sinnoh", "신오캡", "神奥帽子", "神奧帽子"}},
            {  25,  4, {"イッシュキャップ", nullptr, "Casquette d’Unys", "Berretto Unima", "Einall-Kappe",
                        "Gorra Teselia", "하나캡", "合众帽子", "合眾帽子"}},
            {  25,  5, {"カロスキャップ", nullptr, "Casquette de Kalos", "Berretto Kalos", "Kalos-Kappe",
                        "Gorra Kalos", "칼로스캡", "卡洛斯帽子", "卡洛斯帽子"}},
            {  25,  6, {"アローラキャップ", nullptr, "Casquette d’Alola", "Berretto Alola", "Alola-Kappe",
                        "Gorra Alola", "알로라캡", "阿罗拉帽子", "阿羅拉帽子"}},
            {  25,  7, {"キミにきめたキャップ", nullptr, "Casquette Partenaire", "Berretto Compagni", "Partner-Kappe",
                        "Gorra Compañero", "너로정했다캡", "就决定是你了之帽子", "就決定是你了之帽子"}},
            {  25,  8, {"Starter", nullptr, "Starter", "Starter", "Starter", "Starter", "Starter", "Starter",
                        "Starter"}},
            {  25,  9, {"ワールドキャップ", nullptr, "Casquette Monde", "Berretto Giramondo", "Weltreise-Kappe",
                        "Gorra Trotamundos", "월드캡", "世界帽子", "世界帽子"}},
            {  26,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            {  26,  1, {"アローラのすがた", nullptr, "Forme d’Alola", "Forma di Alola", "Alola-Form", "Forma de Alola",
                        "알로라의 모습", "阿罗拉的样子", "阿羅拉的樣子"}},
            {  26,  2, {"メガX", nullptr, "Méga X", "Mega X", "Mega X", "Mega X", "메가 X", "超级 Ｘ", "Mega Ｘ"}},
            {  26,  3, {"メガY", nullptr, "Méga Y", "Mega Y", "Mega Y", "Mega Y", "메가 Y", "超级 Ｙ", "Mega Ｙ"}},
            {  27,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            {  27,  1, {"アローラのすがた", nullptr, "Forme d’Alola", "Forma di Alola", "Alola-Form", "Forma de Alola",
                        "알로라의 모습", "阿罗拉的样子", "阿羅拉的樣子"}},
            {  28,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            {  28,  1, {"アローラのすがた", nullptr, "Forme d’Alola", "Forma di Alola", "Alola-Form", "Forma de Alola",
                        "알로라의 모습", "阿罗拉的样子", "阿羅拉的樣子"}},
            {  36,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            {  36,  1, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            {  37,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            {  37,  1, {"アローラのすがた", nullptr, "Forme d’Alola", "Forma di Alola", "Alola-Form", "Forma de Alola",
                        "알로라의 모습", "阿罗拉的样子", "阿羅拉的樣子"}},
            {  38,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            {  38,  1, {"アローラのすがた", nullptr, "Forme d’Alola", "Forma di Alola", "Alola-Form", "Forma de Alola",
                        "알로라의 모습", "阿罗拉的样子", "阿羅拉的樣子"}},
            {  50,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            {  50,  1, {"アローラのすがた", nullptr, "Forme d’Alola", "Forma di Alola", "Alola-Form", "Forma de Alola",
                        "알로라의 모습", "阿罗拉的样子", "阿羅拉的樣子"}},
            {  51,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            {  51,  1, {"アローラのすがた", nullptr, "Forme d’Alola", "Forma di Alola", "Alola-Form", "Forma de Alola",
                        "알로라의 모습", "阿罗拉的样子", "阿羅拉的樣子"}},
            {  52,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            {  52,  1, {"アローラのすがた", nullptr, "Forme d’Alola", "Forma di Alola", "Alola-Form", "Forma de Alola",
                        "알로라의 모습", "阿罗拉的样子", "阿羅拉的樣子"}},
            {  52,  2, {"ガラルのすがた", nullptr, "Forme de Galar", "Forma di Galar", "Galar-Form", "Forma de Galar",
                        "가라르의 모습", "伽勒尔的样子", "伽勒爾的樣子"}},
            {  53,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            {  53,  1, {"アローラのすがた", nullptr, "Forme d’Alola", "Forma di Alola", "Alola-Form", "Forma de Alola",
                        "알로라의 모습", "阿罗拉的样子", "阿羅拉的樣子"}},
            {  58,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            {  58,  1, {"ヒスイのすがた", nullptr, "Forme de Hisui", "Hisui", "Hisui-Form", "Hisui", "히스이의", "洗翠的样子",
                        "洗翠的樣子"}},
            {  59,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            {  59,  1, {"ヒスイのすがた", nullptr, "Forme de Hisui", "Hisui", "Hisui-Form", "Hisui", "히스이의", "洗翠的样子",
                        "洗翠的樣子"}},
            {  59,  2, {"キングのすがた", nullptr, "Roi", "Re", "Königs", "Señor", "왕의", "王的样子", "王的樣子"}},
            {  65,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            {  65,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            {  71,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            {  71,  1, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            {  74,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            {  74,  1, {"アローラのすがた", nullptr, "Forme d’Alola", "Forma di Alola", "Alola-Form", "Forma de Alola",
                        "알로라의 모습", "阿罗拉的样子", "阿羅拉的樣子"}},
            {  75,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            {  75,  1, {"アローラのすがた", nullptr, "Forme d’Alola", "Forma di Alola", "Alola-Form", "Forma de Alola",
                        "알로라의 모습", "阿罗拉的样子", "阿羅拉的樣子"}},
            {  76,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            {  76,  1, {"アローラのすがた", nullptr, "Forme d’Alola", "Forma di Alola", "Alola-Form", "Forma de Alola",
                        "알로라의 모습", "阿罗拉的样子", "阿羅拉的樣子"}},
            {  77,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            {  77,  1, {"ガラルのすがた", nullptr, "Forme de Galar", "Forma di Galar", "Galar-Form", "Forma de Galar",
                        "가라르의 모습", "伽勒尔的样子", "伽勒爾的樣子"}},
            {  78,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            {  78,  1, {"ガラルのすがた", nullptr, "Forme de Galar", "Forma di Galar", "Galar-Form", "Forma de Galar",
                        "가라르의 모습", "伽勒尔的样子", "伽勒爾的樣子"}},
            {  79,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            {  79,  1, {"ガラルのすがた", nullptr, "Forme de Galar", "Forma di Galar", "Galar-Form", "Forma de Galar",
                        "가라르의 모습", "伽勒尔的样子", "伽勒爾的樣子"}},
            {  80,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            {  80,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            {  80,  2, {"ガラルのすがた", nullptr, "Forme de Galar", "Forma di Galar", "Galar-Form", "Forma de Galar",
                        "가라르의 모습", "伽勒尔的样子", "伽勒爾的樣子"}},
            {  83,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            {  83,  1, {"ガラルのすがた", nullptr, "Forme de Galar", "Forma di Galar", "Galar-Form", "Forma de Galar",
                        "가라르의 모습", "伽勒尔的样子", "伽勒爾的樣子"}},
            {  88,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            {  88,  1, {"アローラのすがた", nullptr, "Forme d’Alola", "Forma di Alola", "Alola-Form", "Forma de Alola",
                        "알로라의 모습", "阿罗拉的样子", "阿羅拉的樣子"}},
            {  89,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            {  89,  1, {"アローラのすがた", nullptr, "Forme d’Alola", "Forma di Alola", "Alola-Form", "Forma de Alola",
                        "알로라의 모습", "阿罗拉的样子", "阿羅拉的樣子"}},
            {  94,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            {  94,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 100,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 100,  1, {"ヒスイのすがた", nullptr, "Forme de Hisui", "Hisui", "Hisui-Form", "Hisui", "히스이의", "洗翠的样子",
                        "洗翠的樣子"}},
            { 101,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 101,  1, {"ヒスイのすがた", nullptr, "Forme de Hisui", "Hisui", "Hisui-Form", "Hisui", "히스이의", "洗翠的样子",
                        "洗翠的樣子"}},
            { 101,  2, {"キングのすがた", nullptr, "Roi", "Re", "Königs", "Señor", "왕의", "王的样子", "王的樣子"}},
            { 103,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 103,  1, {"アローラのすがた", nullptr, "Forme d’Alola", "Forma di Alola", "Alola-Form", "Forma de Alola",
                        "알로라의 모습", "阿罗拉的样子", "阿羅拉的樣子"}},
            { 105,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 105,  1, {"アローラのすがた", nullptr, "Forme d’Alola", "Forma di Alola", "Alola-Form", "Forma de Alola",
                        "알로라의 모습", "阿罗拉的样子", "阿羅拉的樣子"}},
            { 105,  2, {"おおきいサイズ", nullptr, "Maxi", "Grande", "L", "Grande", "큰 사이즈", "大尺寸", "大尺寸"}},
            { 110,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 110,  1, {"ガラルのすがた", nullptr, "Forme de Galar", "Forma di Galar", "Galar-Form", "Forma de Galar",
                        "가라르의 모습", "伽勒尔的样子", "伽勒爾的樣子"}},
            { 115,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 115,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 121,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 121,  1, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            { 122,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 122,  1, {"ガラルのすがた", nullptr, "Forme de Galar", "Forma di Galar", "Galar-Form", "Forma de Galar",
                        "가라르의 모습", "伽勒尔的样子", "伽勒爾的樣子"}},
            { 127,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 127,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 128,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 128,  1, {"パルデア コンバット", nullptr, "Paldea Combative", "Paldea Combattiva", "Paldea Gefecht",
                        "Paldea Combatiente", "팔데아 컴뱃", "帕底亚的样子 斗战", "帕底亞的樣子 鬥戰"}},
            { 128,  2, {"パルデア ブレイズ", nullptr, "Paldea Flamboyante", "Paldea Infuocata", "Paldea Flammen",
                        "Paldea Ardiente", "팔데아 블레이즈", "帕底亚的样子 火炽", "帕底亞的樣子 火熾"}},
            { 128,  3, {"パルデア ウォーター", nullptr, "Paldea Aquatique", "Paldea Acquatica", "Paldea Fluten",
                        "Paldea Acuática", "팔데아 워터", "帕底亚的样子 水澜", "帕底亞的樣子 水瀾"}},
            { 130,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 130,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 133,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 133,  1, {"Starter", nullptr, "Starter", "Starter", "Starter", "Starter", "Starter", "Starter",
                        "Starter"}},
            { 142,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 142,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 144,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 144,  1, {"ガラルのすがた", nullptr, "Forme de Galar", "Forma di Galar", "Galar-Form", "Forma de Galar",
                        "가라르의 모습", "伽勒尔的样子", "伽勒爾的樣子"}},
            { 145,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 145,  1, {"ガラルのすがた", nullptr, "Forme de Galar", "Forma di Galar", "Galar-Form", "Forma de Galar",
                        "가라르의 모습", "伽勒尔的样子", "伽勒爾的樣子"}},
            { 146,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 146,  1, {"ガラルのすがた", nullptr, "Forme de Galar", "Forma di Galar", "Galar-Form", "Forma de Galar",
                        "가라르의 모습", "伽勒尔的样子", "伽勒爾的樣子"}},
            { 149,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 149,  1, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            { 150,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 150,  1, {"メガＸ", nullptr, "Méga X", "Mega X", "Mega X", "Mega X", "메가X", "超级 Ｘ", "Mega Ｘ"}},
            { 150,  2, {"メガＹ", nullptr, "Méga Y", "Mega Y", "Mega Y", "Mega Y", "메가Y", "超级 Ｙ", "Mega Ｙ"}},
            { 154,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 154,  1, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            { 157,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 157,  1, {"ヒスイのすがた", nullptr, "Forme de Hisui", "Hisui", "Hisui-Form", "Hisui", "히스이의", "洗翠的样子",
                        "洗翠的樣子"}},
            { 160,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 160,  1, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            { 172,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 172,  1, {"ギザみみ", nullptr, "Spiky", "Spiky", "Spitzohr", "Picoreja", "삐죽귀", "刺刺耳", "刺刺耳"}},
            { 181,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 181,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 194,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 194,  1, {"パルデアのすがた", nullptr, "Forme de Paldéa", "Paldea", "Paldea", "Paldea", "팔데아", "帕底亚的样子",
                        "帕底亞的樣子"}},
            { 199,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 199,  1, {"ガラルのすがた", nullptr, "Forme de Galar", "Forma di Galar", "Galar-Form", "Forma de Galar",
                        "가라르의 모습", "伽勒尔的样子", "伽勒爾的樣子"}},
            { 201,  0, {"Ａ", nullptr, "A", "A", "A", "A", "A", "A", "A"}},
            { 201,  1, {"Ｂ", nullptr, "B", "B", "B", "B", "B", "B", "B"}},
            { 201,  2, {"Ｃ", nullptr, "C", "C", "C", "C", "C", "C", "C"}},
            { 201,  3, {"Ｄ", nullptr, "D", "D", "D", "D", "D", "D", "D"}},
            { 201,  4, {"Ｅ", nullptr, "E", "E", "E", "E", "E", "E", "E"}},
            { 201,  5, {"Ｆ", nullptr, "F", "F", "F", "F", "F", "F", "F"}},
            { 201,  6, {"Ｇ", nullptr, "G", "G", "G", "G", "G", "G", "G"}},
            { 201,  7, {"Ｈ", nullptr, "H", "H", "H", "H", "H", "H", "H"}},
            { 201,  8, {"Ｉ", nullptr, "I", "I", "I", "I", "I", "I", "I"}},
            { 201,  9, {"Ｊ", nullptr, "J", "J", "J", "J", "J", "J", "J"}},
            { 201, 10, {"Ｋ", nullptr, "K", "K", "K", "K", "K", "K", "K"}},
            { 201, 11, {"Ｌ", nullptr, "L", "L", "L", "L", "L", "L", "L"}},
            { 201, 12, {"Ｍ", nullptr, "M", "M", "M", "M", "M", "M", "M"}},
            { 201, 13, {"Ｎ", nullptr, "N", "N", "N", "N", "N", "N", "N"}},
            { 201, 14, {"Ｏ", nullptr, "O", "O", "O", "O", "O", "O", "O"}},
            { 201, 15, {"Ｐ", nullptr, "P", "P", "P", "P", "P", "P", "P"}},
            { 201, 16, {"Ｑ", nullptr, "Q", "Q", "Q", "Q", "Q", "Q", "Q"}},
            { 201, 17, {"Ｒ", nullptr, "R", "R", "R", "R", "R", "R", "R"}},
            { 201, 18, {"Ｓ", nullptr, "S", "S", "S", "S", "S", "S", "S"}},
            { 201, 19, {"Ｔ", nullptr, "T", "T", "T", "T", "T", "T", "T"}},
            { 201, 20, {"Ｕ", nullptr, "U", "U", "U", "U", "U", "U", "U"}},
            { 201, 21, {"Ｖ", nullptr, "V", "V", "V", "V", "V", "V", "V"}},
            { 201, 22, {"Ｗ", nullptr, "W", "W", "W", "W", "W", "W", "W"}},
            { 201, 23, {"Ｘ", nullptr, "X", "X", "X", "X", "X", "X", "X"}},
            { 201, 24, {"Ｙ", nullptr, "Y", "Y", "Y", "Y", "Y", "Y", "Y"}},
            { 201, 25, {"Ｚ", nullptr, "Z", "Z", "Z", "Z", "Z", "Z", "Z"}},
            { 201, 26, {"!", nullptr, "!", "!", "!", "!", "!", "!", "!"}},
            { 201, 27, {"?", nullptr, "?", "?", "?", "?", "?", "?", "?"}},
            { 208,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 208,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 211,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 211,  1, {"ヒスイのすがた", nullptr, "Forme de Hisui", "Hisui", "Hisui-Form", "Hisui", "히스이의", "洗翠的样子",
                        "洗翠的樣子"}},
            { 212,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 212,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 214,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 214,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 215,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 215,  1, {"ヒスイのすがた", nullptr, "Forme de Hisui", "Hisui", "Hisui-Form", "Hisui", "히스이의", "洗翠的样子",
                        "洗翠的樣子"}},
            { 222,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 222,  1, {"ガラルのすがた", nullptr, "Forme de Galar", "Forma di Galar", "Galar-Form", "Forma de Galar",
                        "가라르의 모습", "伽勒尔的样子", "伽勒爾的樣子"}},
            { 227,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 227,  1, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            { 229,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 229,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 248,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 248,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 254,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 254,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 257,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 257,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 260,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 260,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 263,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 263,  1, {"ガラルのすがた", nullptr, "Forme de Galar", "Forma di Galar", "Galar-Form", "Forma de Galar",
                        "가라르의 모습", "伽勒尔的样子", "伽勒爾的樣子"}},
            { 264,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 264,  1, {"ガラルのすがた", nullptr, "Forme de Galar", "Forma di Galar", "Galar-Form", "Forma de Galar",
                        "가라르의 모습", "伽勒尔的样子", "伽勒爾的樣子"}},
            { 282,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 282,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 302,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 302,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 303,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 303,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 306,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 306,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 308,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 308,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 310,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 310,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 319,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 319,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 323,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 323,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 334,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 334,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 351,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 351,  1, {"たいようのすがた", nullptr, "Forme Solaire", "Forma Sole", "Sonnenform", "Forma Sol",
                        "태양의 모습", "太阳的样子", "太陽的樣子"}},
            { 351,  2, {"あまみずのすがた", nullptr, "Forme Eau de Pluie", "Forma Pioggia", "Regenform",
                        "Forma Lluvia", "빗방울의 모습", "雨水的样子", "雨水的樣子"}},
            { 351,  3, {"ゆきぐものすがた", nullptr, "Forme Blizzard", "Forma Nuvola di Neve", "Schneeform",
                        "Forma Nieve", "설운의 모습", "雪云的样子", "雪雲的樣子"}},
            { 354,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 354,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 358,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 358,  1, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            { 359,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 359,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 359,  2, {"メガZ", nullptr, "Méga Z", "Mega Z", "Mega Z", "Mega Z", "메가 Z", "超级 Ｚ", "Mega Ｚ"}},
            { 362,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 362,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 373,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 373,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 376,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 376,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 380,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 380,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 381,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 381,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 382,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 382,  1, {"ゲンシカイキのすがた", nullptr, "Primo-Résurgence", "Archeorisveglio", "Protomorphose",
                        "Regresión Primigenia", "원시회귀의 모습", "原始回归", "原始回歸的樣子"}},
            { 383,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 383,  1, {"ゲンシカイキのすがた", nullptr, "Primo-Résurgence", "Archeorisveglio", "Protomorphose",
                        "Regresión Primigenia", "원시회귀의 모습", "原始回归", "原始回歸的樣子"}},
            { 384,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 384,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 386,  0, {"ノーマルフォルム", nullptr, "Forme Normale", "Forma Normale", "Normalform", "Forma Normal",
                        "노말폼", "一般", "一般"}},
            { 386,  1, {"アタックフォルム", nullptr, "Forme Attaque", "Forma Attacco", "Angriffsform", "Forma Ataque",
                        "어택폼", "攻击形态", "攻擊形態"}},
            { 386,  2, {"ディフェンスフォルム", nullptr, "Forme Défense", "Forma Difesa", "Verteidigungsform",
                        "Forma Defensa", "디펜스폼", "防御形态", "防禦形態"}},
            { 386,  3, {"スピードフォルム", nullptr, "Forme Vitesse", "Forma Velocità", "Initiativeform",
                        "Forma Velocidad", "스피드폼", "速度形态", "速度形態"}},
            { 398,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 398,  1, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            { 412,  0, {"くさきのミノ", nullptr, "Cape Plante", "Manto Pianta", "Pflanzenumhang", "Tronco Planta",
                        "초목도롱", "草木蓑衣", "草木蓑衣"}},
            { 412,  1, {"すなちのミノ", nullptr, "Cape Sable", "Manto Sabbia", "Sandumhang", "Tronco Arena", "모래땅도롱",
                        "砂土蓑衣", "砂土蓑衣"}},
            { 412,  2, {"ゴミのミノ", nullptr, "Cape Déchet", "Manto Scarti", "Lumpenumhang", "Tronco Basura",
                        "슈레도롱", "垃圾蓑衣", "垃圾蓑衣"}},
            { 413,  0, {"くさきのミノ", nullptr, "Cape Plante", "Manto Pianta", "Pflanzenumhang", "Tronco Planta",
                        "초목도롱", "草木蓑衣", "草木蓑衣"}},
            { 413,  1, {"すなちのミノ", nullptr, "Cape Sable", "Manto Sabbia", "Sandumhang", "Tronco Arena", "모래땅도롱",
                        "砂土蓑衣", "砂土蓑衣"}},
            { 413,  2, {"ゴミのミノ", nullptr, "Cape Déchet", "Manto Scarti", "Lumpenumhang", "Tronco Basura",
                        "슈레도롱", "垃圾蓑衣", "垃圾蓑衣"}},
            { 414,  0, {"くさきのミノ", nullptr, "Plante", "Pianta", "Pflanz", "Planta", "초목도롱", "草木蓑衣", "草木蓑衣"}},
            { 414,  1, {"すなちのミノ", nullptr, "Sable", "Sabbia", "Sandumhang", "Arena", "모래땅도롱", "砂土蓑衣", "砂土蓑衣"}},
            { 414,  2, {"ゴミのミノ", nullptr, "Déchet", "Scarti", "Lumpenumhang", "Basura", "슈레도롱", "垃圾蓑衣", "垃圾蓑衣"}},
            { 421,  0, {"ネガフォルム", nullptr, "Temps Couvert", "Forma Nuvola", "Wolkenform", "Forma Encapotado",
                        "네거폼", "阴天形态", "陰天形態"}},
            { 421,  1, {"ポジフォルム", nullptr, "Temps Ensoleillé", "Forma Splendore", "Sonnenform",
                        "Forma Soleado", "포지폼", "晴天形态", "晴天形態"}},
            { 422,  0, {"にしのうみ", nullptr, "Mer Occident", "Mare Ovest", "Westliches Meer", "Mar Oeste", "서쪽바다",
                        "西海", "西海"}},
            { 422,  1, {"ひがしのうみ", nullptr, "Mer Orient", "Mare Est", "Östliches Meer", "Mar Este", "동쪽바다",
                        "东海", "東海"}},
            { 423,  0, {"にしのうみ", nullptr, "Mer Occident", "Mare Ovest", "Westliches Meer", "Mar Oeste", "서쪽바다",
                        "西海", "西海"}},
            { 423,  1, {"ひがしのうみ", nullptr, "Mer Orient", "Mare Est", "Östliches Meer", "Mar Este", "동쪽바다",
                        "东海", "東海"}},
            { 428,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 428,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 445,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 445,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 445,  2, {"メガZ", nullptr, "Méga Z", "Mega Z", "Mega Z", "Mega Z", "메가 Z", "超级 Ｚ", "Mega Ｚ"}},
            { 448,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 448,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 448,  2, {"メガZ", nullptr, "Méga Z", "Mega Z", "Mega Z", "Mega Z", "메가 Z", "超级 Ｚ", "Mega Ｚ"}},
            { 460,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 460,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 475,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 475,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 478,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 478,  1, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            { 479,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 479,  1, {"ヒート", nullptr, "Chaleur", "Calore", "Hitze", "Calor", "히트", "加热", "加熱"}},
            { 479,  2, {"ウォッシュ", nullptr, "Lavage", "Lavaggio", "Wasch", "Lavado", "워시", "清洗", "清洗"}},
            { 479,  3, {"フロスト", nullptr, "Froid", "Gelo", "Frost", "Frío", "프로스트", "结冰", "結冰"}},
            { 479,  4, {"スピン", nullptr, "Hélice", "Vortice", "Wirbel", "Ventilador", "스핀", "旋转", "旋轉"}},
            { 479,  5, {"カット", nullptr, "Tonte", "Taglio", "Schneid", "Corte", "커트", "切割", "切割"}},
            { 483,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 483,  1, {"オリジンフォルム", nullptr, "Forme Originelle", "Originale", "Urform", "Origen", "오리진폼",
                        "起源形态", "起源形態"}},
            { 484,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 484,  1, {"オリジンフォルム", nullptr, "Forme Originelle", "Originale", "Urform", "Origen", "오리진폼",
                        "起源形态", "起源形態"}},
            { 485,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 485,  1, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            { 487,  0, {"アナザーフォルム", nullptr, "Forme Alternative", "Forma Alterata", "Wandelform",
                        "Forma Modificada", "어나더폼", "别种形态", "別種形態"}},
            { 487,  1, {"オリジンフォルム", nullptr, "Forme Originelle", "Forma Originale", "Urform", "Forma Origen",
                        "오리진폼", "起源形态", "起源形態"}},
            { 491,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 491,  1, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            { 492,  0, {"ランドフォルム", nullptr, "Forme Terrestre", "Forma Terra", "Landform", "Forma Tierra",
                        "랜드폼", "陆上形态", "陸上形態"}},
            { 492,  1, {"スカイフォルム", nullptr, "Forme Céleste", "Forma Cielo", "Zenitform", "Forma Cielo", "스카이폼",
                        "天空形态", "天空形態"}},
            { 493, 18, {"レジェンド", nullptr, "Légende", "Leggenda", "Legende", "Legendaria", "레전드", "传说", "傳說"}},
            { 500,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 500,  1, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            { 503,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 503,  1, {"ヒスイのすがた", nullptr, "Forme de Hisui", "Hisui", "Hisui-Form", "Hisui", "히스이의", "洗翠的样子",
                        "洗翠的樣子"}},
            { 530,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 530,  1, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            { 531,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 531,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 545,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 545,  1, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            { 549,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 549,  1, {"ヒスイのすがた", nullptr, "Forme de Hisui", "Hisui", "Hisui-Form", "Hisui", "히스이의", "洗翠的样子",
                        "洗翠的樣子"}},
            { 549,  2, {"クイーンのすがた", nullptr, "Reine", "Regina", "Königinnen", "Señora", "여왕의", "女王的样子", "女王的樣子"}},
            { 550,  0, {"あかすじのすがた", nullptr, "Motif Rouge", "Forma Linearossa", "Rotlinige Form",
                        "Forma Raya Roja", "적색근의 모습", "红色", "紅條紋的樣子"}},
            { 550,  1, {"あおすじのすがた", nullptr, "Motif Bleu", "Forma Lineablu", "Blaulinige Form",
                        "Forma Raya Azul", "청색근의 모습", "蓝色", "藍條紋的樣子"}},
            { 550,  2, {"しろすじのすがた", nullptr, "Motif Blanc", "Bianco", "Weißlinienform", "Blanca", "하얀", "白色",
                        "白"}},
            { 554,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 554,  1, {"ガラルのすがた", nullptr, "Forme de Galar", "Forma di Galar", "Galar-Form", "Forma de Galar",
                        "가라르의 모습", "伽勒尔的样子", "伽勒爾的樣子"}},
            { 555,  0, {"ノーマルモード", nullptr, "Mode Normal", "Stato Normale", "Normalmodus", "Modo Normal",
                        "노말모드", "普通模式", "普通模式"}},
            { 555,  1, {"ダルマモード", nullptr, "Mode Transe", "Stato Zen", "Trance-Modus", "Modo Daruma", "달마모드",
                        "达摩模式", "達摩模式"}},
            { 555,  2, {"ガラルのすがた", nullptr, "Forme de Galar", "Forma di Galar", "Galar-Form", "Forma de Galar",
                        "가라르의 모습", "伽勒尔的样子", "伽勒爾的樣子"}},
            { 555,  3, {"ガラルのすがた ダルマモード", nullptr, "de Galar Transe", "Galar Stato Zen", "Galar (Trance)",
                        "Galar Daruma", "가라르의 모습 달마모드", "伽勒尔的样子 达摩模式", "伽勒爾的樣子 達摩模式"}},
            { 560,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 560,  1, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            { 562,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 562,  1, {"ガラルのすがた", nullptr, "Forme de Galar", "Forma di Galar", "Galar-Form", "Forma de Galar",
                        "가라르의 모습", "伽勒尔的样子", "伽勒爾的樣子"}},
            { 570,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 570,  1, {"ヒスイのすがた", nullptr, "Forme de Hisui", "Hisui", "Hisui-Form", "Hisui", "히스이의", "洗翠的样子",
                        "洗翠的樣子"}},
            { 571,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 571,  1, {"ヒスイのすがた", nullptr, "Forme de Hisui", "Hisui", "Hisui-Form", "Hisui", "히스이의", "洗翠的样子",
                        "洗翠的樣子"}},
            { 585,  0, {"はるのすがた", nullptr, "Forme Printemps", "Forma Primavera", "Frühlingsform",
                        "Forma Primavera", "봄의 모습", "春天的样子", "春天的樣子"}},
            { 585,  1, {"なつのすがた", nullptr, "Forme Été", "Forma Estate", "Sommerform", "Forma Verano", "여름의 모습",
                        "夏天的样子", "夏天的樣子"}},
            { 585,  2, {"あきのすがた", nullptr, "Forme Automne", "Forma Autunno", "Herbstform", "Forma Otoño",
                        "가을의 모습", "秋天的样子", "秋天的樣子"}},
            { 585,  3, {"ふゆのすがた", nullptr, "Forme Hiver", "Forma Inverno", "Winterform", "Forma Invierno",
                        "겨울의 모습", "冬天的样子", "冬天的樣子"}},
            { 586,  0, {"はるのすがた", nullptr, "Forme Printemps", "Forma Primavera", "Frühlingsform",
                        "Forma Primavera", "봄의 모습", "春天的样子", "春天的樣子"}},
            { 586,  1, {"なつのすがた", nullptr, "Forme Été", "Forma Estate", "Sommerform", "Forma Verano", "여름의 모습",
                        "夏天的样子", "夏天的樣子"}},
            { 586,  2, {"あきのすがた", nullptr, "Forme Automne", "Forma Autunno", "Herbstform", "Forma Otoño",
                        "가을의 모습", "秋天的样子", "秋天的樣子"}},
            { 586,  3, {"ふゆのすがた", nullptr, "Forme Hiver", "Forma Inverno", "Winterform", "Forma Invierno",
                        "겨울의 모습", "冬天的样子", "冬天的樣子"}},
            { 604,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 604,  1, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            { 609,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 609,  1, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            { 618,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 618,  1, {"ガラルのすがた", nullptr, "Forme de Galar", "Forma di Galar", "Galar-Form", "Forma de Galar",
                        "가라르의 모습", "伽勒尔的样子", "伽勒爾的樣子"}},
            { 623,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 623,  1, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            { 628,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 628,  1, {"ヒスイのすがた", nullptr, "Forme de Hisui", "Hisui", "Hisui-Form", "Hisui", "히스이의", "洗翠的样子",
                        "洗翠的樣子"}},
            { 641,  0, {"けしんフォルム", nullptr, "Forme Avatar", "Forma Incarnazione", "Inkarnationsform",
                        "Forma Avatar", "화신폼", "化身形态", "化身形態"}},
            { 641,  1, {"れいじゅうフォルム", nullptr, "Forme Totémique", "Forma Totem", "Tiergeistform", "Forma Tótem",
                        "영물폼", "灵兽形态", "靈獸形態"}},
            { 642,  0, {"けしんフォルム", nullptr, "Forme Avatar", "Forma Incarnazione", "Inkarnationsform",
                        "Forma Avatar", "화신폼", "化身形态", "化身形態"}},
            { 642,  1, {"れいじゅうフォルム", nullptr, "Forme Totémique", "Forma Totem", "Tiergeistform", "Forma Tótem",
                        "영물폼", "灵兽形态", "靈獸形態"}},
            { 645,  0, {"けしんフォルム", nullptr, "Forme Avatar", "Forma Incarnazione", "Inkarnationsform",
                        "Forma Avatar", "화신폼", "化身形态", "化身形態"}},
            { 645,  1, {"れいじゅうフォルム", nullptr, "Forme Totémique", "Forma Totem", "Tiergeistform", "Forma Tótem",
                        "영물폼", "灵兽形态", "靈獸形態"}},
            { 646,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 646,  1, {"ホワイト", nullptr, "Blanc", "Bianco", "Weißes", "Blanco", "화이트", "焰白", "焰白"}},
            { 646,  2, {"ブラック", nullptr, "Noir", "Nero", "Schwarzes", "Negro", "블랙", "暗黑", "暗黑"}},
            { 647,  0, {"いつものすがた", nullptr, "Aspect Normal", "Forma Normale", "Standardform", "Forma Habitual",
                        "평상시 모습", "平常的样子", "平常的樣子"}},
            { 647,  1, {"かくごのすがた", nullptr, "Aspect Décidé", "Forma Risoluta", "Resolutform", "Forma Brío",
                        "각오의 모습", "觉悟的样子", "覺悟的樣子"}},
            { 648,  0, {"ボイスフォルム", nullptr, "Forme Chant", "Forma Canto", "Gesangsform", "Forma Lírica",
                        "보이스폼", "歌声形态", "歌聲形態"}},
            { 648,  1, {"ステップフォルム", nullptr, "Forme Danse", "Forma Danza", "Tanzform", "Forma Danza", "스텝폼",
                        "舞步形态", "舞步形態"}},
            { 649,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 649,  1, {"アクアカセット", nullptr, "Module Aqua", "Idromodulo", "Aquamodul", "HidroROM", "아쿠아카세트",
                        "水", "水"}},
            { 649,  2, {"イナズマカセット", nullptr, "Module Choc", "Voltmodulo", "Blitzmodul", "FulgoROM", "번개카세트",
                        "电", "電"}},
            { 649,  3, {"ブレイズカセット", nullptr, "Module Pyro", "Piromodulo", "Flammenmodul", "PiroROM", "블레이즈카세트",
                        "火", "火"}},
            { 649,  4, {"フリーズカセット", nullptr, "Module Cryo", "Gelomodulo", "Gefriermodul", "CrioROM", "프리즈카세트",
                        "冰", "冰"}},
            { 652,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 652,  1, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            { 655,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 655,  1, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            { 658,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 658,  1, {"サトシ", nullptr, "Synergie", "Ash", "Battle Bond", "Ash", "지우", "小智版", "小智版"}},
            { 658,  2, {"サトシ", nullptr, "Forme Sacha", "Forma Ash", "Ash-Form", "Forma Ash", "지우", "活跃模式",
                        "活躍模式"}},
            { 658,  3, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            { 664,  0, {"ひょうせつのもよう", nullptr, "Blizzard", "Nevi Perenni", "Frost", "Polar", "빙설의 모양", "冰雪花纹",
                        "冰雪花紋"}},
            { 664,  1, {"ゆきぐにのもよう", nullptr, "Banquise", "Nordico", "Schneefeld", "Taiga", "설국의 모양", "雪国花纹",
                        "雪國花紋"}},
            { 664,  2, {"せつげんのもよう", nullptr, "Glace", "Manto di Neve", "Flocken", "Tundra", "설원의 모양", "雪原花纹",
                        "雪原花紋"}},
            { 664,  3, {"たいりくのもよう", nullptr, "Continent", "Continentale", "Kontinental", "Continental",
                        "대륙의 모양", "大陆花纹", "大陸花紋"}},
            { 664,  4, {"ていえんのもよう", nullptr, "Verdure", "Prato", "Ziergarten", "Vergel", "정원의 모양", "庭园花纹",
                        "庭園花紋"}},
            { 664,  5, {"みやびなもよう", nullptr, "Monarchie", "Eleganza", "Prunk", "Oriental", "우아한 모양", "高雅花纹",
                        "高雅花紋"}},
            { 664,  6, {"はなぞののもよう", nullptr, "Floraison", "Giardinfiore", "Blumenmeer", "Floral", "화원의 모양",
                        "花园花纹", "花園花紋"}},
            { 664,  7, {"モダンなもよう", nullptr, "Métropole", "Trendy", "Innovations", "Moderno", "모던한 모양", "摩登花纹",
                        "摩登花紋"}},
            { 664,  8, {"マリンのもよう", nullptr, "Rivage", "Marino", "Aquamarin", "Marino", "마린의 모양", "大海花纹", "大海花紋"}},
            { 664,  9, {"ぐんとうのもよう", nullptr, "Archipel", "Arcipelago", "Archipel", "Isleño", "군도의 모양", "群岛花纹",
                        "群島花紋"}},
            { 664, 10, {"こうやのもよう", nullptr, "Sécheresse", "Deserto", "Dürre", "Estepa", "황야의 모양", "荒野花纹",
                        "荒野花紋"}},
            { 664, 11, {"さじんのもよう", nullptr, "Sable", "Sabbia", "Sand", "Desierto", "사진의 모양", "沙尘花纹", "沙塵花紋"}},
            { 664, 12, {"たいがのもよう", nullptr, "Delta", "Fluviale", "Flussdelta", "Oasis", "대하의 모양", "大河花纹",
                        "大河花紋"}},
            { 664, 13, {"スコールのもよう", nullptr, "Cyclone", "Pluviale", "Monsun", "Monzón", "스콜의 모양", "骤雨花纹",
                        "驟雨花紋"}},
            { 664, 14, {"サバンナのもよう", nullptr, "Mangrove", "Savana", "Savannen", "Pantano", "사바나의 모양", "热带草原花纹",
                        "熱帶草原花紋"}},
            { 664, 15, {"たいようのもよう", nullptr, "Zénith", "Solare", "Sonnen", "Solar", "태양의 모양", "太阳花纹", "太陽花紋"}},
            { 664, 16, {"オーシャンのもよう", nullptr, "Soleil", "Oceanico", "Ozean", "Océano", "오션의 모양", "大洋花纹", "大洋花紋"}},
            { 664, 17, {"ジャングルのもよう", nullptr, "Jungle", "Giungla", "Dschungel", "Jungla", "정글의 모양", "热带雨林花纹",
                        "熱帶雨林花紋"}},
            { 664, 18, {"ファンシーなもよう", nullptr, "Fantaisie", "Sbarazzino", "Fantasie", "Fantasía", "팬시한 모양",
                        "幻彩花纹", "幻彩花紋"}},
            { 664, 19, {"ボールのもよう", nullptr, "Poké Ball", "Poké Ball", "Pokéball", "Poké Ball", "볼의 모양", "球球花纹",
                        "球球花紋"}},
            { 665,  0, {"ひょうせつのもよう", nullptr, "Blizzard", "Nevi Perenni", "Frost", "Polar", "빙설의 모양", "冰雪花纹",
                        "冰雪花紋"}},
            { 665,  1, {"ゆきぐにのもよう", nullptr, "Banquise", "Nordico", "Schneefeld", "Taiga", "설국의 모양", "雪国花纹",
                        "雪國花紋"}},
            { 665,  2, {"せつげんのもよう", nullptr, "Glace", "Manto di Neve", "Flocken", "Tundra", "설원의 모양", "雪原花纹",
                        "雪原花紋"}},
            { 665,  3, {"たいりくのもよう", nullptr, "Continent", "Continentale", "Kontinental", "Continental",
                        "대륙의 모양", "大陆花纹", "大陸花紋"}},
            { 665,  4, {"ていえんのもよう", nullptr, "Verdure", "Prato", "Ziergarten", "Vergel", "정원의 모양", "庭园花纹",
                        "庭園花紋"}},
            { 665,  5, {"みやびなもよう", nullptr, "Monarchie", "Eleganza", "Prunk", "Oriental", "우아한 모양", "高雅花纹",
                        "高雅花紋"}},
            { 665,  6, {"はなぞののもよう", nullptr, "Floraison", "Giardinfiore", "Blumenmeer", "Floral", "화원의 모양",
                        "花园花纹", "花園花紋"}},
            { 665,  7, {"モダンなもよう", nullptr, "Métropole", "Trendy", "Innovations", "Moderno", "모던한 모양", "摩登花纹",
                        "摩登花紋"}},
            { 665,  8, {"マリンのもよう", nullptr, "Rivage", "Marino", "Aquamarin", "Marino", "마린의 모양", "大海花纹", "大海花紋"}},
            { 665,  9, {"ぐんとうのもよう", nullptr, "Archipel", "Arcipelago", "Archipel", "Isleño", "군도의 모양", "群岛花纹",
                        "群島花紋"}},
            { 665, 10, {"こうやのもよう", nullptr, "Sécheresse", "Deserto", "Dürre", "Estepa", "황야의 모양", "荒野花纹",
                        "荒野花紋"}},
            { 665, 11, {"さじんのもよう", nullptr, "Sable", "Sabbia", "Sand", "Desierto", "사진의 모양", "沙尘花纹", "沙塵花紋"}},
            { 665, 12, {"たいがのもよう", nullptr, "Delta", "Fluviale", "Flussdelta", "Oasis", "대하의 모양", "大河花纹",
                        "大河花紋"}},
            { 665, 13, {"スコールのもよう", nullptr, "Cyclone", "Pluviale", "Monsun", "Monzón", "스콜의 모양", "骤雨花纹",
                        "驟雨花紋"}},
            { 665, 14, {"サバンナのもよう", nullptr, "Mangrove", "Savana", "Savannen", "Pantano", "사바나의 모양", "热带草原花纹",
                        "熱帶草原花紋"}},
            { 665, 15, {"たいようのもよう", nullptr, "Zénith", "Solare", "Sonnen", "Solar", "태양의 모양", "太阳花纹", "太陽花紋"}},
            { 665, 16, {"オーシャンのもよう", nullptr, "Soleil", "Oceanico", "Ozean", "Océano", "오션의 모양", "大洋花纹", "大洋花紋"}},
            { 665, 17, {"ジャングルのもよう", nullptr, "Jungle", "Giungla", "Dschungel", "Jungla", "정글의 모양", "热带雨林花纹",
                        "熱帶雨林花紋"}},
            { 665, 18, {"ファンシーなもよう", nullptr, "Fantaisie", "Sbarazzino", "Fantasie", "Fantasía", "팬시한 모양",
                        "幻彩花纹", "幻彩花紋"}},
            { 665, 19, {"ボールのもよう", nullptr, "Poké Ball", "Poké Ball", "Pokéball", "Poké Ball", "볼의 모양", "球球花纹",
                        "球球花紋"}},
            { 666,  0, {"ひょうせつのもよう", nullptr, "Motif Blizzard", "Motivo Nevi Perenni", "Frostmuster",
                        "Motivo Polar", "빙설의 모양", "冰雪花纹", "冰雪花紋"}},
            { 666,  1, {"ゆきぐにのもよう", nullptr, "Motif Banquise", "Motivo Nordico", "Schneefeldmuster",
                        "Motivo Taiga", "설국의 모양", "雪国花纹", "雪國花紋"}},
            { 666,  2, {"せつげんのもよう", nullptr, "Motif Glace", "Motivo Manto di Neve", "Flockenmuster",
                        "Motivo Tundra", "설원의 모양", "雪原花纹", "雪原花紋"}},
            { 666,  3, {"たいりくのもよう", nullptr, "Motif Continent", "Motivo Continentale", "Kontinentalmuster",
                        "Motivo Continental", "대륙의 모양", "大陆花纹", "大陸花紋"}},
            { 666,  4, {"ていえんのもよう", nullptr, "Motif Verdure", "Motivo Prato", "Ziergartenmuster",
                        "Motivo Vergel", "정원의 모양", "庭园花纹", "庭園花紋"}},
            { 666,  5, {"みやびなもよう", nullptr, "Motif Monarchie", "Motivo Eleganza", "Prunkmuster",
                        "Motivo Oriental", "우아한 모양", "高雅花纹", "高雅花紋"}},
            { 666,  6, {"はなぞののもよう", nullptr, "Motif Floraison", "Motivo Giardinfiore", "Blumenmeermuster",
                        "Motivo Floral", "화원의 모양", "花园花纹", "花園花紋"}},
            { 666,  7, {"モダンなもよう", nullptr, "Motif Métropole", "Motivo Trendy", "Innovationsmuster",
                        "Motivo Moderno", "모던한 모양", "摩登花纹", "摩登花紋"}},
            { 666,  8, {"マリンのもよう", nullptr, "Motif Rivage", "Motivo Marino", "Aquamarinmuster",
                        "Motivo Marino", "마린의 모양", "大海花纹", "大海花紋"}},
            { 666,  9, {"ぐんとうのもよう", nullptr, "Motif Archipel", "Motivo Arcipelago", "Archipelmuster",
                        "Motivo Isleño", "군도의 모양", "群岛花纹", "群島花紋"}},
            { 666, 10, {"こうやのもよう", nullptr, "Motif Sécheresse", "Motivo Deserto", "Dürremuster",
                        "Motivo Estepa", "황야의 모양", "荒野花纹", "荒野花紋"}},
            { 666, 11, {"さじんのもよう", nullptr, "Motif Sable", "Motivo Sabbia", "Sandmuster", "Motivo Desierto",
                        "사진의 모양", "沙尘花纹", "沙塵花紋"}},
            { 666, 12, {"たいがのもよう", nullptr, "Motif Delta", "Motivo Fluviale", "Flussdeltamuster",
                        "Motivo Oasis", "대하의 모양", "大河花纹", "大河花紋"}},
            { 666, 13, {"スコールのもよう", nullptr, "Motif Cyclone", "Motivo Pluviale", "Monsunmuster",
                        "Motivo Monzón", "스콜의 모양", "骤雨花纹", "驟雨花紋"}},
            { 666, 14, {"サバンナのもよう", nullptr, "Motif Mangrove", "Motivo Savana", "Savannenmuster",
                        "Motivo Pantano", "사바나의 모양", "热带草原花纹", "熱帶草原花紋"}},
            { 666, 15, {"たいようのもよう", nullptr, "Motif Zénith", "Motivo Solare", "Sonnenmuster", "Motivo Solar",
                        "태양의 모양", "太阳花纹", "太陽花紋"}},
            { 666, 16, {"オーシャンのもよう", nullptr, "Motif Soleil Levant", "Motivo Oceanico", "Ozeanmuster",
                        "Motivo Océano", "오션의 모양", "大洋花纹", "大洋花紋"}},
            { 666, 17, {"ジャングルのもよう", nullptr, "Motif Jungle", "Motivo Giungla", "Dschungelmuster",
                        "Motivo Jungla", "정글의 모양", "热带雨林花纹", "熱帶雨林花紋"}},
            { 666, 18, {"ファンシーなもよう", nullptr, "Motif Fantaisie", "Motivo Sbarazzino", "Fantasiemuster",
                        "Motivo Fantasía", "팬시한 모양", "幻彩花纹", "幻彩花紋"}},
            { 666, 19, {"ボールのもよう", nullptr, "Motif Poké Ball", "Motivo Poké Ball", "Pokéball-Muster",
                        "Motivo Poké Ball", "볼의 모양", "球球花纹", "球球花紋"}},
            { 668,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 668,  1, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            { 669,  0, {"あかいはな", nullptr, "Fleur Rouge", "Fiore Rosso", "Rotblütler", "Flor Roja", "빨간 꽃",
                        "红色", "紅花"}},
            { 669,  1, {"きいろのはな", nullptr, "Fleur Jaune", "Fiore Giallo", "Gelbblütler", "Flor Amarilla",
                        "노란 꽃", "黄色", "黃"}},
            { 669,  2, {"オレンジいろのはな", nullptr, "Fleur Orange", "Fiore Arancione", "Orangeblütler",
                        "Flor Naranja", "오렌지색 꽃", "橙色", "橙"}},
            { 669,  3, {"あおいはな", nullptr, "Fleur Bleue", "Fiore Blu", "Blaublütler", "Flor Azul", "파란 꽃", "蓝色",
                        "藍"}},
            { 669,  4, {"しろいはな", nullptr, "Fleur Blanche", "Fiore Bianco", "Weißblütler", "Flor Blanca",
                        "하얀 꽃", "白色", "白"}},
            { 670,  0, {"あかいはな", nullptr, "Fleur Rouge", "Fiore Rosso", "Rotblütler", "Flor Roja", "빨간 꽃",
                        "红色", "紅花"}},
            { 670,  1, {"きいろのはな", nullptr, "Fleur Jaune", "Fiore Giallo", "Gelbblütler", "Flor Amarilla",
                        "노란 꽃", "黄色", "黃"}},
            { 670,  2, {"オレンジいろのはな", nullptr, "Fleur Orange", "Fiore Arancione", "Orangeblütler",
                        "Flor Naranja", "오렌지색 꽃", "橙色", "橙"}},
            { 670,  3, {"あおいはな", nullptr, "Fleur Bleue", "Fiore Blu", "Blaublütler", "Flor Azul", "파란 꽃", "蓝色",
                        "藍"}},
            { 670,  4, {"しろいはな", nullptr, "Fleur Blanche", "Fiore Bianco", "Weißblütler", "Flor Blanca",
                        "하얀 꽃", "白色", "白"}},
            { 670,  5, {"えいえんのはな", nullptr, "Fleur Éternelle", "Fiore Eterno", "Ewigblütler", "Flor Eterna",
                        "영원의 꽃", "永恒", "永恆"}},
            { 670,  6, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            { 671,  0, {"あかいはな", nullptr, "Fleur Rouge", "Fiore Rosso", "Rotblütler", "Flor Roja", "빨간 꽃",
                        "红色", "紅花"}},
            { 671,  1, {"きいろのはな", nullptr, "Fleur Jaune", "Fiore Giallo", "Gelbblütler", "Flor Amarilla",
                        "노란 꽃", "黄色", "黃"}},
            { 671,  2, {"オレンジいろのはな", nullptr, "Fleur Orange", "Fiore Arancione", "Orangeblütler",
                        "Flor Naranja", "오렌지색 꽃", "橙色", "橙"}},
            { 671,  3, {"あおいはな", nullptr, "Fleur Bleue", "Fiore Blu", "Blaublütler", "Flor Azul", "파란 꽃", "蓝色",
                        "藍"}},
            { 671,  4, {"しろいはな", nullptr, "Fleur Blanche", "Fiore Bianco", "Weißblütler", "Flor Blanca",
                        "하얀 꽃", "白色", "白"}},
            { 676,  0, {"やせいのすがた", nullptr, "Forme Sauvage", "Forma Selvatica", "Zottelform", "Forma Salvaje",
                        "야생의 모습", "野生的样子", "野生的樣子"}},
            { 676,  1, {"ハートカット", nullptr, "Coupe Cœur", "Taglio Cuore", "Herzchenschnitt", "Corte Corazón",
                        "하트컷", "心形造型", "心形造型"}},
            { 676,  2, {"スターカット", nullptr, "Coupe Étoile", "Taglio Stella", "Sternchenschnitt",
                        "Corte Estrella", "스타컷", "星形造型", "星形造型"}},
            { 676,  3, {"ダイヤカット", nullptr, "Coupe Diamant", "Taglio Diamante", "Diamantenschnitt",
                        "Corte Rombo", "다이아컷", "菱形造型", "菱形造型"}},
            { 676,  4, {"レディカット", nullptr, "Coupe Demoiselle", "Taglio Signorina", "Fräuleinschnitt",
                        "Corte Señorita", "레이디컷", "淑女造型", "淑女造型"}},
            { 676,  5, {"マダムカット", nullptr, "Coupe Madame", "Taglio Gentildonna", "Damenschnitt", "Corte Dama",
                        "마담컷", "贵妇造型", "貴婦造型"}},
            { 676,  6, {"ジェントルカット", nullptr, "Coupe Monsieur", "Taglio Gentiluomo", "Kavaliersschnitt",
                        "Corte Caballero", "젠틀컷", "绅士造型", "紳士造型"}},
            { 676,  7, {"クイーンカット", nullptr, "Coupe Reine", "Taglio Regina", "Königinnenschnitt",
                        "Corte Aristocrático", "퀸컷", "女王造型", "女王造型"}},
            { 676,  8, {"カブキカット", nullptr, "Coupe Kabuki", "Taglio Kabuki", "Kabuki-Schnitt", "Corte Kabuki",
                        "가부키컷", "歌舞伎造型", "歌舞伎造型"}},
            { 676,  9, {"キングダムカット", nullptr, "Coupe Pharaon", "Taglio Faraone", "Herrscherschnitt",
                        "Corte Faraónico", "킹덤컷", "国王造型", "國王造型"}},
            { 678,  0, {"オスのすがた", nullptr, "Mâle", "Maschio", "Männlich", "Macho", "수컷의 모습", "♂", "♂"}},
            { 678,  1, {"メスのすがた", nullptr, "Femelle", "Femmina", "Weiblich", "Hembra", "암컷의 모습", "♀", "♀"}},
            { 678,  2, {"♂-メガ", nullptr, "♂-Méga", "♂-Mega", "♂-Mega", "♂-Mega", "♂-메가", "♂-超级", "♂-Mega"}},
            { 678,  3, {"♀-メガ", nullptr, "♀-Méga", "♀-Mega", "♀-Mega", "♀-Mega", "♀-메가", "♀-超级", "♀-Mega"}},
            { 681,  0, {"シールドフォルム", nullptr, "Forme Parade", "Forma Scudo", "Schildform", "Forma Escudo",
                        "실드폼", "盾牌形态", "盾牌形態"}},
            { 681,  1, {"ブレードフォルム", nullptr, "Forme Assaut", "Forma Spada", "Klingenform", "Forma Filo",
                        "블레이드폼", "刀剑形态", "刀劍形態"}},
            { 687,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 687,  1, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            { 689,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 689,  1, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            { 691,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 691,  1, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            { 701,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 701,  1, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            { 705,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 705,  1, {"ヒスイのすがた", nullptr, "Forme de Hisui", "Hisui", "Hisui-Form", "Hisui", "히스이의", "洗翠的样子",
                        "洗翠的樣子"}},
            { 706,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 706,  1, {"ヒスイのすがた", nullptr, "Forme de Hisui", "Hisui", "Hisui-Form", "Hisui", "히스이의", "洗翠的样子",
                        "洗翠的樣子"}},
            { 710,  0, {"ふつうのサイズ", nullptr, "Taille Normale", "Normale", "Größe M", "Tamaño Normal", "보통 사이즈",
                        "中颗种", "中顆種"}},
            { 710,  1, {"ちいさいサイズ", nullptr, "Taille Mini", "Mini", "Größe S", "Tamaño Pequeño", "작은 사이즈",
                        "小颗种", "小顆種"}},
            { 710,  2, {"おおきいサイズ", nullptr, "Taille Maxi", "Grande", "Größe L", "Tamaño Grande", "큰 사이즈",
                        "大颗种", "大顆種"}},
            { 710,  3, {"とくだいサイズ", nullptr, "Taille Ultra", "Maxi", "Größe XL", "Tamaño Extragrande", "특대 사이즈",
                        "巨颗种", "巨顆種"}},
            { 711,  0, {"ふつうのサイズ", nullptr, "Taille Normale", "Normale", "Größe M", "Tamaño Normal", "보통 사이즈",
                        "中颗种", "中顆種"}},
            { 711,  1, {"ちいさいサイズ", nullptr, "Taille Mini", "Mini", "Größe S", "Tamaño Pequeño", "작은 사이즈",
                        "小颗种", "小顆種"}},
            { 711,  2, {"おおきいサイズ", nullptr, "Taille Maxi", "Grande", "Größe L", "Tamaño Grande", "큰 사이즈",
                        "大颗种", "大顆種"}},
            { 711,  3, {"とくだいサイズ", nullptr, "Taille Ultra", "Maxi", "Größe XL", "Tamaño Extragrande", "특대 사이즈",
                        "巨颗种", "巨顆種"}},
            { 713,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 713,  1, {"ヒスイのすがた", nullptr, "Forme de Hisui", "Hisui", "Hisui-Form", "Hisui", "히스이의", "洗翠的样子",
                        "洗翠的樣子"}},
            { 713,  2, {"キングのすがた", nullptr, "Roi", "Re", "Königs", "Señor", "왕의", "王的样子", "王的樣子"}},
            { 716,  0, {"リラックスモード", nullptr, "Mode Paisible", "Modo Relax", "Ruhe-Modus", "Modo Relajado",
                        "릴랙스모드", "放松模式", "放鬆模式"}},
            { 716,  1, {"アクティブモード", nullptr, "Mode Déchaîné", "Modo Attivo", "Aktiv-Modus", "Modo Activo",
                        "액티브모드", "活跃模式", "活躍模式"}},
            { 718,  0, {"５０％フォルム", nullptr, "Forme 50 %", "Forma 50%", "50%-Form", "Forma 50%", "50%폼",
                        "50％形态", "50％形態"}},
            { 718,  1, {"１０％フォルム", nullptr, "Forme 10 %", "Forma 10%", "10%-Form", "Forma 10%", "10%폼",
                        "10％形态", "10％形態"}},
            { 718,  2, {"１０％フォルム-C", nullptr, "10 %-C", "10%-C", "10%-C", "10%-C", "10%폼-C", "10％形态-C",
                        "10％形態-C"}},
            { 718,  3, {"５０％フォルム-C", nullptr, "50 %-C", "50%-C", "50%-C", "50%-C", "50%폼-C", "50％形态-C",
                        "50％形態-C"}},
            { 718,  4, {"パーフェクトフォルム", nullptr, "Forme Parfaite", "Forma Perfetta", "Optimumform",
                        "Forma Completa", "퍼펙트폼", "完全体形态", "完全體形態"}},
            { 718,  5, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            { 719,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 719,  1, {"メガ", nullptr, "Méga", "Mega", "Mega-Form", "Mega", "메가", "超级", "Mega"}},
            { 720,  0, {"いましめられし", nullptr, "Enchaîné", "Vincolato", "Gebanntes", "Contenido", "굴레에 빠진", "惩戒",
                        "懲戒"}},
            { 720,  1, {"ときはなたれし", nullptr, "Déchaîné", "Libero", "Entfesseltes", "Desatado", "굴레를 벗어난", "解放",
                        "解放"}},
            { 724,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 724,  1, {"ヒスイのすがた", nullptr, "Forme de Hisui", "Hisui", "Hisui-Form", "Hisui", "히스이의", "洗翠的样子",
                        "洗翠的樣子"}},
            { 735,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 735,  1, {"おおきいサイズ", nullptr, "Dominant", "Grande", "Totem", "Grande", "큰 사이즈", "大尺寸", "大尺寸"}},
            { 738,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 738,  1, {"おおきいサイズ", nullptr, "Dominant", "Grande", "Totem", "Grande", "큰 사이즈", "大尺寸", "大尺寸"}},
            { 740,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 740,  1, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            { 741,  0, {"めらめらスタイル", nullptr, "Style Flamenco", "Stile Flamenco", "Flamenco-Stil",
                        "Estilo Apasionado", "이글이글스타일", "热辣热辣风格", "熱辣熱辣風格"}},
            { 741,  1, {"ぱちぱちスタイル", nullptr, "Style Pom-Pom", "Stile Cheerdance", "Cheerleading-Stil",
                        "Estilo Animado", "파칙파칙스타일", "啪滋啪滋风格", "啪滋啪滋風格"}},
            { 741,  2, {"ふらふらスタイル", nullptr, "Hula", "Hula", "Hula", "Plácido", "훌라훌라스타일", "呼拉呼拉风格", "呼拉呼拉風格"}},
            { 741,  3, {"まいまいスタイル", nullptr, "Style Buyō", "Stile Buyō", "Buyo-Stil", "Estilo Refinado",
                        "하늘하늘스타일", "轻盈轻盈风格", "輕盈輕盈風格"}},
            { 743,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 743,  1, {"おおきいサイズ", nullptr, "Dominant", "Grande", "Totem", "Grande", "큰 사이즈", "大尺寸", "大尺寸"}},
            { 744,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 744,  1, {"たそがれのすがた", nullptr, "Forme Crépusculaire", "Forma Crepuscolo", "Abend",
                        "Forma Crepuscular", "황혼의", "黄昏的样子", "黃昏的樣子"}},
            { 745,  0, {"まひるのすがた", nullptr, "Forme Diurne", "Forma Giorno", "Tagform", "Forma Diurna",
                        "한낮의 모습", "白昼的样子", "白晝的樣子"}},
            { 745,  1, {"まよなかのすがた", nullptr, "Forme Nocturne", "Forma Notte", "Nachtform", "Forma Nocturna",
                        "한밤중의 모습", "黑夜的样子", "黑夜的樣子"}},
            { 745,  2, {"たそがれのすがた", nullptr, "Forme Crépusculaire", "Forma Crepuscolo", "Zwielichtform",
                        "Forma Crepuscular", "황혼의 모습", "黄昏的样子", "黃昏的樣子"}},
            { 746,  0, {"たんどくのすがた", nullptr, "Forme Solitaire", "Forma Individuale", "Einzelform",
                        "Forma Individual", "단독의 모습", "单独的样子", "單獨的樣子"}},
            { 746,  1, {"むれたすがた", nullptr, "Forme Banc", "Forma Banco", "Schwarmform", "Forma Banco", "군집의 모습",
                        "鱼群的样子", "魚群的樣子"}},
            { 752,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 752,  1, {"おおきいサイズ", nullptr, "Dominant", "Grande", "Totem", "Grande", "큰 사이즈", "大尺寸", "大尺寸"}},
            { 754,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 754,  1, {"おおきいサイズ", nullptr, "Dominant", "Grande", "Totem", "Grande", "큰 사이즈", "大尺寸", "大尺寸"}},
            { 758,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 758,  1, {"おおきいサイズ", nullptr, "Dominant", "Grande", "Totem", "Grande", "큰 사이즈", "大尺寸", "大尺寸"}},
            { 768,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 768,  1, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            { 774,  0, {"りゅうせいのすがた", nullptr, "Forme Météore Noyeau Rouge", "M-Rosso", "M-Roter", "M-Rojo",
                        "유성의 모습", "流星的样子", "流星的樣子"}},
            { 774,  1, {"りゅうせいのすがた", nullptr, "Forme Météore Noyeau Orange", "M-Arancione", "M-Oranger",
                        "M-Naranja", "유성의 모습", "流星的样子", "流星的樣子"}},
            { 774,  2, {"りゅうせいのすがた", nullptr, "Forme Météore Noyeau Jaune", "M-Giallo", "M-Gelber",
                        "M-Amarillo", "유성의 모습", "流星的样子", "流星的樣子"}},
            { 774,  3, {"りゅうせいのすがた", nullptr, "Forme Météore Noyeau Vert", "M-Verde", "M-Grüner", "M-Verde",
                        "유성의 모습", "流星的样子", "流星的樣子"}},
            { 774,  4, {"りゅうせいのすがた", nullptr, "Forme Météore Noyeau Bleu", "M-Azzurro", "M-Hellblauer",
                        "M-Azul", "유성의 모습", "流星的样子", "流星的樣子"}},
            { 774,  5, {"りゅうせいのすがた", nullptr, "Forme Météore Noyeau Indigo", "M-Indaco", "M-Blauer", "M-Añil",
                        "유성의 모습", "流星的样子", "流星的樣子"}},
            { 774,  6, {"りゅうせいのすがた", nullptr, "Forme Météore Noyeau Violet", "M-Violetto", "M-Violetter",
                        "M-Violeta", "유성의 모습", "流星的样子", "流星的樣子"}},
            { 774,  7, {"あかいろのコア", nullptr, "Noyau Rouge", "Nucleo Rosso", "Roter Kern", "Núcleo Rojo",
                        "빨간색 코어", "红色核心", "紅色核心"}},
            { 774,  8, {"だいだいいろのコア", nullptr, "Noyau Orange", "Nucleo Arancione", "Oranger Kern",
                        "Núcleo Naranja", "주황색 코어", "橙色核心", "橙色核心"}},
            { 774,  9, {"きいろのコア", nullptr, "Noyau Jaune", "Nucleo Giallo", "Gelber Kern", "Núcleo Amarillo",
                        "노란색 코어", "黄色核心", "黃色核心"}},
            { 774, 10, {"みどりいろのコア", nullptr, "Noyau Vert", "Nucleo Verde", "Grüner Kern", "Núcleo Verde",
                        "초록색 코어", "绿色核心", "綠色核心"}},
            { 774, 11, {"みずいろのコア", nullptr, "Noyau Bleu", "Nucleo Azzurro", "Hellblauer Kern", "Núcleo Azul",
                        "옥색 코어", "浅蓝色核心", "淺藍色核心"}},
            { 774, 12, {"あおいろのコア", nullptr, "Noyau Indigo", "Nucleo Indaco", "Blauer Kern", "Núcleo Añil",
                        "파란색 코어", "蓝色核心", "藍色核心"}},
            { 774, 13, {"むらさきいろのコア", nullptr, "Noyau Violet", "Nucleo Violetto", "Violetter Kern",
                        "Núcleo Violeta", "보라색 코어", "紫色核心", "紫色核心"}},
            { 777,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 777,  1, {"おおきいサイズ", nullptr, "Dominant", "Grande", "Totem", "Grande", "큰 사이즈", "大尺寸", "大尺寸"}},
            { 778,  0, {"ばけたすがた", nullptr, "Forme Déguisée", "Forma Mascherata", "Verkleidete Form",
                        "Forma Encubierta", "둔갑한 모습", "化形的样子", "化形的樣子"}},
            { 778,  1, {"ばれたすがた", nullptr, "Forme Démasquée", "Forma Smascherata", "Entlarvte Form",
                        "Forma Descubierta", "들킨 모습", "现形的样子", "現形的樣子"}},
            { 778,  2, {"おおきいサイズ", nullptr, "Dominant", "Grande", "Totem (Getarnt)", "Grande", "큰 사이즈", "大尺寸",
                        "大尺寸"}},
            { 778,  3, {"*ばれたすがた", nullptr, "Dominant Forme Démasquée", "*Smascherata", "Totem (Entlarvt)",
                        "*Descubierta", "*들킨 모습", "*现形的样子", "*現形的樣子"}},
            { 780,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 780,  1, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            { 784,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 784,  1, {"おおきいサイズ", nullptr, "Dominant", "Grande", "Totem", "Grande", "큰 사이즈", "大尺寸", "大尺寸"}},
            { 800,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 800,  1, {"たそがれのたてがみ", nullptr, "Crinière du Couchant", "Criniera del Vespro", "Abendmähne",
                        "Melena Crepuscular", "황혼의 갈기", "黄昏之鬃", "黃昏之鬃"}},
            { 800,  2, {"あかつきのつばさ", nullptr, "Ailes de l’Aurore", "Ali dell’Aurora", "Morgenschwingen",
                        "Alas del Alba", "새벽의 날개", "拂晓之翼", "拂曉之翼"}},
            { 800,  3, {"ウルトラ", nullptr, "Ultra", "Ultra", "Ultra", "Ultra", "울트라", "究极", "究極"}},
            { 801,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 801,  1, {"５００ねんまえのいろ", nullptr, "Couleur du Passé", "Colore Antico", "Originalfarbe",
                        "Color Vetusto", "500년 전의 색", "５００年前的颜色", "５００年前的顏色"}},
            { 801,  2, {"メガ", nullptr, "Méga", "Normale-Mega", "Normal-Mega", "Normal-Mega", "노말-메가", "一般-超级",
                        "一般-Mega"}},
            { 801,  3, {"５００ねんまえのいろ-メガ", nullptr, "Passé-Méga", "Colore Antico-Mega", "Original-Mega",
                        "Vetusto-Mega", "500년 전의 색-메가", "５００年前的颜色-超级", "５００年前的顏色-Mega"}},
            { 807,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 807,  1, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            { 845,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 845,  1, {"うのみのすがた", nullptr, "Forme Gobe-Tout", "Forma Inghiottitutto", "Schlingform",
                        "Forma Tragatodo", "그대로 삼킨 모습", "一口吞的样子", "一口吞的樣子"}},
            { 845,  2, {"まるのみのすがた", nullptr, "Forme Gobe-Chu", "Forma Inghiottintero", "Stopfform",
                        "Forma Engulletodo", "통째로 삼킨 모습", "大口吞的样子", "大口吞的樣子"}},
            { 849,  0, {"ハイなすがた", nullptr, "Forme Aigüe", "Forma Melodia", "Hoch-Form", "Forma Aguda",
                        "하이한 모습", "高调的样子", "高調的樣子"}},
            { 849,  1, {"ローなすがた", nullptr, "Forme Grave", "Forma Basso", "Tief-Form", "Forma Grave", "로우한 모습",
                        "低调的样子", "低調的樣子"}},
            { 854,  0, {"がんさくフォルム", nullptr, "Forme Contrefaçon", "Contraffatta", "Fälschungsform",
                        "Falsificada", "위작", "赝品", "贗品"}},
            { 854,  1, {"しんさくフォルム", nullptr, "Forme Authentique", "Autentica", "Originalform", "Genuina", "진작",
                        "真品", "真品"}},
            { 855,  0, {"がんさくフォルム", nullptr, "Forme Contrefaçon", "Contraffatta", "Fälschungsform",
                        "Falsificada", "위작", "赝品", "贗品"}},
            { 855,  1, {"しんさくフォルム", nullptr, "Forme Authentique", "Autentica", "Originalform", "Genuina", "진작",
                        "真品", "真品"}},
            { 869,  0, {"ミルキィバニラ", nullptr, "Lait Vanille", "Lattevaniglia", "Vanille-Creme",
                        "Crema de Vainilla", "밀키바닐라", "奶香香草", "奶香香草"}},
            { 869,  1, {"ミルキィルビー", nullptr, "Ruby", "Latterosa", "Rubin", "Rosa", "밀키루비", "奶香红钻", "奶香紅鑽"}},
            { 869,  2, {"ミルキィまっちゃ", nullptr, "Matcha", "Lattematcha", "Matcha", "de Té", "밀키말차", "奶香抹茶", "奶香抹茶"}},
            { 869,  3, {"ミルキィミント", nullptr, "Menthe", "Lattementa", "Minz", "de Menta", "밀키민트", "奶香薄荷", "奶香薄荷"}},
            { 869,  4, {"ミルキィレモン", nullptr, "Citron", "Lattelimone", "Zitronen", "de Limón", "밀키레몬", "奶香柠檬",
                        "奶香檸檬"}},
            { 869,  5, {"ミルキィソルト", nullptr, "Salé", "Lattesale", "Salz", "Salada", "밀키솔트", "奶香雪盐", "奶香雪鹽"}},
            { 869,  6, {"ルビーミックス", nullptr, "Ruby", "Rosamix", "Ruby", "Rosa", "루비믹스", "红钻综合", "紅鑽綜合"}},
            { 869,  7, {"キャラメルミックス", nullptr, "Caramel", "Caramelmix", "Karamell", "Caramelo", "캐러멜믹스", "焦糖综合",
                        "焦糖綜合"}},
            { 869,  8, {"トリプルミックス", nullptr, "Tricolore", "Triplomix", "Trio", "Tres Sabores", "트리플믹스", "三色综合",
                        "三色綜合"}},
            { 870,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 870,  1, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            { 875,  0, {"アイスフェイス", nullptr, "Tête de Gel", "Gelofaccia", "Tiefkühlkopf", "Cara de Hielo",
                        "아이스페이스", "结冻头", "結凍頭"}},
            { 875,  1, {"ナイスフェイス", nullptr, "Tête Dégel", "Liquefaccia", "Wohlfühlkopf", "Cara Deshielo",
                        "나이스페이스", "解冻头", "解凍頭"}},
            { 876,  0, {"オスのすがた", nullptr, "Mâle", "Maschio", "Männlich", "Macho", "수컷의 모습", "♂", "♂"}},
            { 876,  1, {"メスのすがた", nullptr, "Femelle", "Femmina", "Weiblich", "Hembra", "암컷의 모습", "♀", "♀"}},
            { 877,  0, {"まんぷくもよう", nullptr, "Mode Rassasié", "Motivo Panciapiena", "Pappsattmuster",
                        "Forma Saciada", "배부른 모양", "满腹花纹", "滿腹花紋"}},
            { 877,  1, {"はらぺこもよう", nullptr, "Mode Affamé", "Motivo Panciavuota", "Kohldampfmuster",
                        "Forma Voraz", "배고픈 모양", "空腹花纹", "空腹花紋"}},
            { 888,  0, {"れきせんのゆうしゃ", nullptr, "Héros Aguerri", "Eroe di Mille Lotte", "Heldenhafter Krieger",
                        "Guerrero Avezado", "역전의 용사", "百战勇者", "百戰勇者"}},
            { 888,  1, {"けんのおう", nullptr, "Épée Suprême", "Re delle Spade", "König des Schwertes",
                        "Espada Suprema", "검왕", "剑之王/盾之王", "劍之王/盾之王"}},
            { 889,  0, {"れきせんのゆうしゃ", nullptr, "Héros Aguerri", "Eroe di Mille Lotte", "Heldenhafter Krieger",
                        "Guerrero Avezado", "역전의 용사", "百战勇者", "百戰勇者"}},
            { 889,  1, {"たてのおう", nullptr, "Bouclier Suprême", "Re degli Scudi", "König des Schildes",
                        "Escudo Supremo", "방패왕", "剑之王/盾之王", "劍之王/盾之王"}},
            { 890,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 890,  1, {"ムゲンダイマックス", nullptr, "Infinimax", "Dynamax Infinito", "Unendynamax",
                        "Dinamax Infinito", "무한다이맥스", "无极巨化", "無極巨化"}},
            { 892,  0, {"いちげきのかた", nullptr, "Style Poing Final", "Stile Singolcolpo", "Fokussierter Stil",
                        "Estilo Brusco", "일격의 태세", "一击流", "一擊流"}},
            { 892,  1, {"れんげきのかた", nullptr, "Style Mille Poings", "Stile Pluricolpo", "Fließender Stil",
                        "Estilo Fluido", "연격의 태세", "连击流", "連擊流"}},
            { 893,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 893,  1, {"とうちゃん", nullptr, "Papa", "Papà", "Papa", "Papá", "아빠", "阿爸", "阿爸"}},
            { 898,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 898,  1, {"はくばじょうのすがた", nullptr, "Cavalier du Froid", "Cavaliere Glaciale", "Schimmelreiter",
                        "Jinete Glacial", "백마 탄 모습", "骑白马的样子", "騎白馬的樣子"}},
            { 898,  2, {"こくばじょうのすがた", nullptr, "Cavalier d’Effroi", "Cavaliere Spettrale", "Rappenreiter",
                        "Jinete Espectral", "흑마 탄 모습", "骑黑马的样子", "騎黑馬的樣子"}},
            { 900,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 900,  1, {"キングのすがた", nullptr, "Roi", "Re", "Königs", "Señor", "왕의", "王的样子", "王的樣子"}},
            { 901,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 901,  1, {"アカツキ", nullptr, "Lune Vermeille", "Luna Cremisi", "Blutmond", "Luna Carmesí", "붉은 달",
                        "赫月", "赫月"}},
            { 902,  0, {"オスのすがた", nullptr, "Mâle", "♂", "♂", "♂", "♂", "♂", "♂"}},
            { 902,  1, {"メスのすがた", nullptr, "Femelle", "♀", "Weiblich", "♀", "♀", "♀", "♀"}},
            { 905,  0, {"けしんフォルム", nullptr, "Forme Avatar", "Incarnazione", "Inkarnations", "Avatar", "화신폼",
                        "化身形态", "化身形態"}},
            { 905,  1, {"れいじゅうフォルム", nullptr, "Forme Totémique", "Totem", "Tiergeistform", "Tótem", "영물폼",
                        "灵兽形态", "靈獸形態"}},
            { 916,  0, {"オスのすがた", nullptr, "Mâle", "♂", "♂", "♂", "♂", "♂", "♂"}},
            { 916,  1, {"メスのすがた", nullptr, "Femelle", "♀", "♀", "♀", "♀", "♀", "♀"}},
            { 925,  0, {"３びきかぞく", nullptr, "Famille de Trois", "Trifamiglia", "Dreierfamilie",
                        "Familia de Tres", "세 식구", "三只家庭", "三隻家庭"}},
            { 925,  1, {"４ひきかぞく", nullptr, "Famille de Quatre", "Quadrifamiglia", "Viererfamilie",
                        "Familia de Cuatro", "네 식구", "四只家庭", "四隻家庭"}},
            { 931,  0, {"グリーンフェザー", nullptr, "Plumage Vert", "Verdi", "Grün", "Verde", "그린", "绿色", "綠羽毛"}},
            { 931,  1, {"ブルーフェザー", nullptr, "Plumage Bleu", "Blu", "Blau", "Azul", "파란", "蓝色", "藍"}},
            { 931,  2, {"イエローフェザー", nullptr, "Plumage Jaune", "Giallo", "Gelb", "Amarilla", "노란", "黄色", "黃"}},
            { 931,  3, {"ホワイトフェザー", nullptr, "Plumage Blanc", "Bianco", "Weiß", "Blanca", "하얀", "白色", "白"}},
            { 952,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 952,  1, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            { 964,  0, {"ナイーブフォルム", nullptr, "Forme Ordinaire", "Ingenua", "Alltags", "Ingenua", "나이브", "平凡形态",
                        "平凡形態"}},
            { 964,  1, {"マイティフォルム", nullptr, "Forme Super", "Possente", "Helden", "Heroica", "마이티", "全能形态",
                        "全能形態"}},
            { 970,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 970,  1, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            { 978,  0, {"そったすがた", nullptr, "Forme Courbée", "Arcuata", "Gebogene", "Curvada", "젖힌", "上弓姿势",
                        "上弓姿勢"}},
            { 978,  1, {"たれたすがた", nullptr, "Forme Affalée", "Adagiata", "Hängende", "Lánguida", "늘어진", "下垂姿势",
                        "下垂姿勢"}},
            { 978,  2, {"のびたすがた", nullptr, "Forme Raide", "Tesa", "Gestreckte", "Recta", "뻗은", "平挺姿势", "平挺姿勢"}},
            { 978,  3, {"そった-メガ", nullptr, "Méga Forme Courbée", "Arcuata-Mega", "Gebogene-Mega",
                        "Curvada-Mega", "젖힌 메가", "上弓姿势-超级", "上弓姿勢-Mega"}},
            { 978,  4, {"たれた-メガ", nullptr, "Méga Forme Affalée", "Adagiata-Mega", "Hängende-Mega",
                        "Lánguida-Mega", "늘어진 메가", "下垂姿势-超级", "下垂姿勢-Mega"}},
            { 978,  5, {"のびた-メガ", nullptr, "Méga Forme Raide", "Tesa-Mega", "Gestreckte-Mega", "Recta-Mega",
                        "뻗은 메가", "平挺姿势-超级", "平挺姿勢-Mega"}},
            { 982,  0, {"ふたふしフォルム", nullptr, "Forme Double", "Bimetamero", "Zweisegment", "Binodular", "두 마",
                        "二节形态", "二節形態"}},
            { 982,  1, {"みつふしフォルム", nullptr, "Forme Triple", "Trimetamero", "Dreisegment", "Trinodular", "세 마",
                        "三节形态", "三節形態"}},
            { 998,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            { 998,  1, {"メガ", nullptr, "Méga", "Mega", "Mega", "Mega", "메가", "超级", "Mega"}},
            { 999,  0, {"はこフォルム", nullptr, "Forme Coffre", "Scrigno", "Truhen", "Cofre", "상자", "宝箱形态", "寶箱形態"}},
            { 999,  1, {"とほフォルム", nullptr, "Forme Marche", "Ambulante", "Wander", "Andante", "도보", "徒步形态",
                        "徒步形態"}},
            {1007,  0, {"かんぜんけいたい", nullptr, "Forme Finale", "Integrale", "Vollkommene", "Plena", "완전", "完全形态",
                        "完全形態"}},
            {1007,  1, {"せいげんけいたい", nullptr, "Forme Limitée", "Parziale", "Gehemmte", "Limitada", "제한", "制限形态",
                        "制限形態"}},
            {1007,  2, {"しっそうけいたい", nullptr, "Forme de Course", "Scattante", "Sprint", "Carrera", "질주", "疾驰形态",
                        "疾馳形態"}},
            {1007,  3, {"ゆうえいけいたい", nullptr, "Forme de Nage", "Nautica", "Schwimm", "Nado", "유영", "破浪形态",
                        "破浪形態"}},
            {1007,  4, {"かっくうけいたい", nullptr, "Forme de Vol", "Librata", "Schwingen", "Planeo", "활공", "乘风形态",
                        "乘風形態"}},
            {1008,  0, {"コンプリートモード", nullptr, "Mode Ultime", "Completo", "Kompletter", "Pleno", "컴플리트", "完整模式",
                        "完整模式"}},
            {1008,  1, {"リミテッドモード", nullptr, "Mode Bridé", "Limitato", "Begrenzter", "Limitado", "리미티드",
                        "受限模式", "受限模式"}},
            {1008,  2, {"ドライブモード", nullptr, "Mode Terrestre", "Sprint", "Fahr", "Conducción", "드라이브", "行驶模式",
                        "行駛模式"}},
            {1008,  3, {"フロートモード", nullptr, "Mode Aquatique", "Nuoto", "Wasser", "Flote", "플로트", "浮水模式", "浮水模式"}},
            {1008,  4, {"グライドモード", nullptr, "Mode Aérien", "Planata", "Gleit", "Planeo", "글라이드", "滑翔模式", "滑翔模式"}},
            {1012,  0, {"マガイモノのすがた", nullptr, "Forme Imitation", "Forma Taroccata", "Imitationsform",
                        "Forma Fraudulenta", "가짜배기의 모습", "冒牌货的样子", "冒牌貨的樣子"}},
            {1012,  1, {"タカイモノのすがた", nullptr, "Forme Onéreuse", "Forma Pregiata", "Kostbarkeitsform",
                        "Forma Opulenta", "알짜배기의 모습", "高档货的样子", "高檔貨的樣子"}},
            {1013,  0, {"ボンサクのすがた", nullptr, "Forme Médiocre", "Forma Dozzinale", "Simple Form",
                        "Forma Mediocre", "범작의 모습", "凡作的样子", "凡作的樣子"}},
            {1013,  1, {"ケッサクのすがた", nullptr, "Forme Exceptionnelle", "Forma Eccezionale", "Edle Form",
                        "Forma Exquisita", "걸작의 모습", "杰作的样子", "傑作的樣子"}},
            {1017,  0, {"みどりのめん", nullptr, "Masque Turquoise", "Maschera Turchese", "Türkisgrüne Maske",
                        "Máscara Turquesa", "벽록의가면", "碧草面具", "碧草面具"}},
            {1017,  1, {"いどのめん", nullptr, "Masque du Puits", "Maschera Pozzo", "Brunnenmaske",
                        "Máscara Fuente", "우물의가면", "水井面具", "水井面具"}},
            {1017,  2, {"かまどのめん", nullptr, "Masque du Fourneau", "Maschera Focolare", "Ofenmaske",
                        "Máscara Horno", "화덕의가면", "火灶面具", "火灶面具"}},
            {1017,  3, {"いしずえのめん", nullptr, "Masque de la Pierre", "Maschera Fondamenta", "Fundamentmaske",
                        "Máscara Cimiento", "주춧돌의가면", "础石面具", "礎石面具"}},
            {1017,  4, {"*みどり", nullptr, "*Turquoise", "*Turchese", "*Türkisgrüne", "*Turquesa", "*벽록",
                        "*碧草面具", "*碧草面具"}},
            {1017,  5, {"*いど", nullptr, "*Puits", "*Pozzo", "*Brunnen", "*Fuente", "*우물", "*水井面具", "*水井面具"}},
            {1017,  6, {"*かまど", nullptr, "*Fourneau", "*Focolare", "*Ofen", "*Horno", "*화덕", "*火灶面具", "*火灶面具"}},
            {1017,  7, {"*いしずえ", nullptr, "*Pierre", "*Fondamenta", "*Fundament", "*Cimiento", "*주춧돌", "*础石面具",
                        "*礎石面具"}},
            {1024,  0, {"ノーマル", nullptr, "Normal", "Normale", "Normal", "Normal", "노말", "一般", "一般"}},
            {1024,  1, {"テラスタルフォルム", nullptr, "Forme Téracristal", "Forma Teracristal", "Terakristall-Form",
                        "Forma teracristal", "테라스탈폼", "太晶形态", "太晶形態"}},
            {1024,  2, {"ステラフォルム", nullptr, "Forme Stellaire", "Astrale", "Stellarform", "Forma astral",
                        "스텔라폼", "星晶形态", "星晶形態"}},
        };
    }

    /// Localized form name, or nullptr when there is none for this language.
    const char *getFormNameLocalized(uint16_t speciesId, uint8_t formId, size_t languageIndex)
    {
        if (languageIndex >= LANGUAGE_COUNT)
            return nullptr;
        constexpr size_t count = sizeof(LOCALIZED_FORM_NAMES) / sizeof(LOCALIZED_FORM_NAMES[0]);
        size_t low = 0, high = count;
        while (low < high)
        {
            const size_t middle = low + (high - low) / 2;
            const LocalizedFormName &row = LOCALIZED_FORM_NAMES[middle];
            if (row.species < speciesId || (row.species == speciesId && row.form < formId))
                low = middle + 1;
            else if (row.species == speciesId && row.form == formId)
                return row.names[languageIndex];
            else
                high = middle;
        }
        return nullptr;
    }
}
