// AUTO-GENERATED ribbon names for the eight non-English languages.
// Regenerate with tools/gen_ribbonnames.py (see tools/pkhex_source.py).
// Source: PKHeX.Core/Resources/text/other/{lang}/text_Ribbons_{lang}.txt.
//
// ENGLISH IS DELIBERATELY ABSENT: PKSE's ribbon names are the ones the GAMES show,
// which is not always PKHeX's UI label -- "Champion" rather than "Champion (Gen3)",
// "Cool Ribbon Super" rather than "Cool Super". Looked up BY the English string
// RibbonNames.cpp produces; a miss falls back to that string unchanged.
#include <cstddef>
#include <cstring>

#include "Names/NameLanguage.h"
#include "Names/RibbonNames.h"

namespace Names
{
    namespace
    {
        struct LocalizedRibbonName
        {
            const char *english;
            const char *names[LANGUAGE_COUNT];
        };

        // Sorted by the English name so the lookup can binary-search.
        const LocalizedRibbonName LOCALIZED_RIBBON_NAMES[] = {
            {"Ability", {"アビリティリボン", nullptr, "Aptitude", "Abilità", "Fähigkeit", "Habilidad", "어빌리티리본",
                         "才能奖章", "才能獎章"}},
            {"Absent-Minded Mark", {"のうてんきなあかし", nullptr, "Insigne Insouciance", "Emblema Spensieratezza",
                                    "Sorglos-Zeichen", "Emblema Despreocupación", "촐랑거리는증표", "无虑之证", "無慮之證"}},
            {"Alert", {"しゃっきリボン", nullptr, "Alerte", "Allarme", "Wachsamkeit", "Alerta", "뚝심리본", "振奋奖章", "振奮獎章"}},
            {"Alola Champion", {"アローラ　チャンプリボン", nullptr, "Maître d'Alola", "Campione Alola", "Alola-Champs",
                                "Campeón de Alola", "알로라챔피언리본", "阿罗拉冠军奖章", "阿羅拉冠軍獎章"}},
            {"Alpha Mark", {"オヤブンのあかし", nullptr, "Insigne Baron", "Emblema dell’Alfa", "Elite-Zeichen",
                            "Emblema Alfa", "우두머리의증표", "头目之证", "頭目之證"}},
            {"Angry Mark", {"ふんぬのあかし", nullptr, "Insigne Colère", "Emblema Collera", "Wut-Zeichen",
                            "Emblema Cólera", "분노의증표", "愤怒之证", "憤怒之證"}},
            {"Artist", {"ブロマイドリボン", nullptr, "Artiste", "Artista", "Künstlers", "Artista", "브로마이드리본", "肖像奖章",
                        "肖像獎章"}},
            {"Battle Champion", {"バトルチャンプリボン", nullptr, "Vainqueur Championnat", "Campione Lotta",
                                 "Kampfmeister", "Campeón de Torneo", "배틀챔피언리본", "对战冠军奖章", "對戰冠軍獎章"}},
            {"Battle Memory", {"おもいでバトルリボン", nullptr, "Souvenir Combat", "Ricordo delle Lotte", "Kampfgedenk",
                               "Recuerdo de Combate", "추억배틀리본", "对战回忆奖章", "對戰回憶獎章"}},
            {"Battle Royal Master", {"ロイヤルマスターリボン", nullptr, "Champion Royal", "Asso Royale",
                                     "Battle-Royale-Meister", "Maestro Battle Royale", "로열마스터리본", "皇家大师奖章",
                                     "皇家大師獎章"}},
            {"Battle Tree Great", {"グレートツリーリボン", nullptr, "Élite de l'Arbre", "Asso dell’Albero", "Profibaum",
                                   "As del Árbol", "그레이트트리리본", "高手对战树奖章", "高手對戰樹獎章"}},
            {"Battle Tree Master", {"マスターツリーリボン", nullptr, "Maître de l'Arbre", "Genio dell’Albero",
                                    "Meisterbaum", "Maestro del Árbol", "마스터트리리본", "大师对战树奖章", "大師對戰樹獎章"}},
            {"Beauty Great", {"ビューティーリボングレート", nullptr, "Beauté Méga", "Bellezza: Livello Mega",
                              "Schönheit Mega", "Belleza difícil", "뷰티리본그레이트", "美丽上级奖章", "美麗上級獎章"}},
            {"Beauty Hyper", {"ビューティリボンハイパー", nullptr, "Beauté Hyper", "Bellezza: Livello Iper",
                              "Schönheit Hyper", "Belleza avanzado", "뷰티리본하이퍼", "美丽高级奖章", "美麗高級獎章"}},
            {"Beauty Master", {"うつくしさマスターリボン", nullptr, "Maître Beauté", "Bellezza Suprema",
                               "Schönheit Master", "Belleza experto", "아름다움마스터리본", "美丽大师奖章", "美麗大師獎章"}},
            {"Beauty Ribbon", {"ビューティリボン", nullptr, "Beauté", "Bellezza", "Schönheit", "Belleza", "뷰티리본",
                               "美丽奖章", "美麗獎章"}},
            {"Beauty Ribbon Hyper", {"ビューティリボンハイパー", nullptr, "Beauté Hyper", "Bellezza: Livello Iper",
                                     "Schönheit Hyper", "Belleza avanzado", "뷰티리본하이퍼", "美丽高级奖章", "美麗高級獎章"}},
            {"Beauty Ribbon Master", {"ビューティリボンマスター", nullptr, "Beauté Master", "Bellezza: Livello Master",
                                      "Schönheit Master", "Belleza experto", "뷰티리본마스터", "美丽大师奖章", "美麗大師獎章"}},
            {"Beauty Ribbon Super", {"ビューティリボンスーパー", nullptr, "Beauté Super", "Bellezza: Livello Super",
                                     "Schönheit Super", "Belleza alto", "뷰티리본슈퍼", "美丽超级奖章", "美麗超級獎章"}},
            {"Beauty Super", {"ビューティリボンスーパー", nullptr, "Beauté Super", "Bellezza: Livello Super",
                              "Schönheit Super", "Belleza alto", "뷰티리본슈퍼", "美丽超级奖章", "美麗超級獎章"}},
            {"Beauty Ultra", {"ビューティーリボンウルトラ", nullptr, "Beauté Ultra", "Bellezza: Livello Ultra",
                              "Schönheit Ultra", "Belleza superior", "뷰티리본울트라", "美丽究极奖章", "美麗究極獎章"}},
            {"Best Friends", {"なかよしリボン", nullptr, "Affection", "Amicizia", "Zutraulichkeits", "Amistad",
                              "절친리본", "好友奖章", "好友獎章"}},
            {"Birthday", {"バースデーリボン", nullptr, "Anniversaire", "Compleanno", "Geburtstags", "Cumpleaños",
                          "버스데이리본", "生日奖章", "生日獎章"}},
            {"Blizzard Mark", {"ごうせつのあかし", nullptr, "Insigne Blizzard", "Emblema Tormenta",
                               "Schneesturm-Zeichen", "Emblema Nevasca", "폭설의증표", "暴雪之证", "暴雪之證"}},
            {"Calmness Mark", {"れいせいのあかし", nullptr, "Insigne Sang-Froid", "Emblema Sangue Freddo",
                               "Gelassenheits-Zeichen", "Emblema Compostura", "냉정의증표", "冷静之证", "冷靜之證"}},
            {"Careless", {"うっかリボン", nullptr, "Négligence", "Indolenza", "Sorglosigkeit", "Descuido", "덜렁이리본",
                          "大意奖章", "大意獎章"}},
            {"Champion", {"チャンプリボン", nullptr, "Maître", "Campione", "Champs", "Campeón", "챔피언리본", "冠军奖章",
                          "冠軍獎章"}},
            {"Charismatic Mark", {"カリスマのあかし", nullptr, "Insigne Charisme", "Emblema Carisma",
                                  "Charisma-Zeichen", "Emblema Carisma", "카리스마의증표", "领袖之证", "領袖之證"}},
            {"Classic", {"クラシックリボン", nullptr, "Classique", "Classico", "Klassisches", "Clásica", "클래식리본",
                         "经典奖章", "經典獎章"}},
            {"Cleverness Master", {"かしこさマスターリボン", nullptr, "Maître Intelligence", "Acume Supremo",
                                   "Klugheit Master", "Ingenio experto", "슬기로움마스터리본", "聪明大师奖章", "聰明大師獎章"}},
            {"Cloudy Mark", {"どんてんのあかし", nullptr, "Insigne Nuages", "Emblema Nuvolo", "Wolken-Zeichen",
                             "Emblema Nube", "흐림의증표", "阴云之证", "陰雲之證"}},
            {"Contest Memory", {"おもいでコンテストリボン", nullptr, "Souvenir Concours", "Ricordo delle Gare",
                                "Wettbewerbsgedenk", "Recuerdo de Concurso", "추억콘테스트리본", "华丽大赛回忆奖章", "華麗大賽回憶獎章"}},
            {"Contest Star", {"コンテストスターリボン", nullptr, "Star des Concours", "Stella delle Gare",
                              "Wettbewerbsstars", "Estelar de Concursos", "콘테스트스타리본", "华丽大赛之星奖章", "華麗大賽之星獎章"}},
            {"Cool Great", {"クールリボングレート", nullptr, "Sang-Froid Méga", "Classe: Livello Mega", "Coolness Mega",
                            "Carisma difícil", "쿨리본그레이트", "帅气上级奖章", "帥氣上級獎章"}},
            {"Cool Hyper", {"クールリボンハイパー", nullptr, "Sang-Froid Hyper", "Classe: Livello Iper",
                            "Coolness Hyper", "Carisma avanzado", "쿨리본하이퍼", "帅气高级奖章", "帥氣高級獎章"}},
            {"Cool Ribbon", {"クールリボン", nullptr, "Sang-Froid", "Classe", "Coolness", "Carisma", "쿨리본", "帅气奖章",
                             "帥氣獎章"}},
            {"Cool Ribbon Hyper", {"クールリボンハイパー", nullptr, "Sang-Froid Hyper", "Classe: Livello Iper",
                                   "Coolness Hyper", "Carisma avanzado", "쿨리본하이퍼", "帅气高级奖章", "帥氣高級獎章"}},
            {"Cool Ribbon Master", {"クールリボンマスター", nullptr, "Sang-Froid Master", "Classe: Livello Master",
                                    "Coolness Master", "Carisma experto", "쿨리본마스터", "帅气大师奖章", "帥氣大師獎章"}},
            {"Cool Ribbon Super", {"クールリボンスーパー", nullptr, "Sang-Froid Super", "Classe: Livello Super",
                                   "Coolness Super", "Carisma alto", "쿨리본슈퍼", "帅气超级奖章", "帥氣超級獎章"}},
            {"Cool Super", {"クールリボンスーパー", nullptr, "Sang-Froid Super", "Classe: Livello Super",
                            "Coolness Super", "Carisma alto", "쿨리본슈퍼", "帅气超级奖章", "帥氣超級獎章"}},
            {"Cool Ultra", {"クールリボンウルトラ", nullptr, "Sang-Froid Ultra", "Classe: Livello Ultra",
                            "Coolness Ultra", "Carisma superior", "쿨리본울트라", "帅气究极奖章", "帥氣究極獎章"}},
            {"Coolness Master", {"かっこよさマスターリボン", nullptr, "Maître Sang-Froid", "Classe Suprema",
                                 "Coolness Master", "Carisma experto", "근사함마스터리본", "帅气大师奖章", "帥氣大師獎章"}},
            {"Country", {"カントリーリボン", nullptr, "Pays", "Paese", "Landes", "Campo", "컨트리리본", "地区奖章", "地區獎章"}},
            {"Crafty Mark", {"こうかつのあかし", nullptr, "Insigne Ruse", "Emblema Astuzia", "Listigkeits-Zeichen",
                             "Emblema Astucia", "교활의증표", "狡猾之证", "狡猾之證"}},
            {"Curry Mark", {"カレーのあかし", nullptr, "Insigne Curry", "Emblema Curry", "Curry-Zeichen",
                            "Emblema Curri", "카레의증표", "咖喱之证", "咖喱之證"}},
            {"Cute Great", {"キュートリボングレート", nullptr, "Grâce Méga", "Grazia: Livello Mega", "Anmut Mega",
                            "Dulzura difícil", "큐트리본그레이트", "可爱上级奖章", "可愛上級獎章"}},
            {"Cute Hyper", {"キュートリボンハイパー", nullptr, "Grâce Hyper", "Grazia: Livello Iper", "Anmut Hyper",
                            "Dulzura avanzado", "큐트리본하이퍼", "可爱高级奖章", "可愛高級獎章"}},
            {"Cute Ribbon", {"キュートリボン", nullptr, "Grâce", "Grazia", "Anmut", "Dulzura", "큐트리본", "可爱奖章", "可愛獎章"}},
            {"Cute Ribbon Hyper", {"キュートリボンハイパー", nullptr, "Grâce Hyper", "Grazia: Livello Iper",
                                   "Anmut Hyper", "Dulzura avanzado", "큐트리본하이퍼", "可爱高级奖章", "可愛高級獎章"}},
            {"Cute Ribbon Master", {"キュートリボンマスター", nullptr, "Grâce Master", "Grazia: Livello Master",
                                    "Anmut Master", "Dulzura experto", "큐트리본마스터", "可爱大师奖章", "可愛大師獎章"}},
            {"Cute Ribbon Super", {"キュートリボンスーパー", nullptr, "Grâce Super", "Grazia: Livello Super",
                                   "Anmut Super", "Dulzura alto", "큐트리본슈퍼", "可爱超级奖章", "可愛超級獎章"}},
            {"Cute Super", {"キュートリボンスーパー", nullptr, "Grâce Super", "Grazia: Livello Super", "Anmut Super",
                            "Dulzura alto", "큐트리본슈퍼", "可爱超级奖章", "可愛超級獎章"}},
            {"Cute Ultra", {"キュートリボンウルトラ", nullptr, "Grâce Ultra", "Grazia: Livello Ultra", "Anmut Ultra",
                            "Dulzura superior", "큐트리본울트라", "可爱究极奖章", "可愛究極獎章"}},
            {"Cuteness Master", {"かわいさマスターリボン", nullptr, "Maître Grâce", "Grazia Suprema", "Anmut Master",
                                 "Dulzura experto", "귀여움마스터리본", "可爱大师奖章", "可愛大師獎章"}},
            {"Dawn Mark", {"あかつきのあかし", nullptr, "Insigne Aube", "Emblema Alba", "Morgendämmerungs-Zeichen",
                           "Emblema Alba", "새벽의증표", "拂晓之证", "拂曉之證"}},
            {"Destiny Mark", {"うんめいのあかし", nullptr, "Insigne Destin", "Emblema Destino", "Schicksals-Zeichen",
                              "Emblema Destino", "운명의증표", "命运之证", "命運之證"}},
            {"Double Ability", {"ダブルアビリティリボン", nullptr, "Aptitude Duo", "Abilità Doppia", "Fähigkeit Doppel",
                                "Doble Habilidad", "더블어빌리티리본", "双人才能奖章", "雙人才能獎章"}},
            {"Downcast", {"しょんぼリボン", nullptr, "Déprime", "Sconforto", "Traurigkeit", "Abatimiento", "풀죽기리본",
                          "失望奖章", "失望獎章"}},
            {"Dry Mark", {"かんそうのあかし", nullptr, "Insigne Sécheresse", "Emblema Arsura", "Dürre-Zeichen",
                          "Emblema Sequedad", "건조의증표", "干燥之证", "乾燥之證"}},
            {"Dusk Mark", {"たそがれのあかし", nullptr, "Insigne Crépuscule", "Emblema Tramonto",
                           "Abenddämmerungs-Zeichen", "Emblema Ocaso", "황혼의증표", "黄昏之证", "黃昏之證"}},
            {"Earth", {"アースリボン", nullptr, "Terre", "Geo", "Erde", "Planeta", "어스리본", "地球奖章", "地球獎章"}},
            {"Effort", {"がんばリボン", nullptr, "Effort", "Merito", "Fleiß", "Esfuerzo", "노력리본", "努力奖章", "努力獎章"}},
            {"Event", {"イベントリボン", nullptr, "Événement", "Evento", "Veranstaltungs", "Evento", "이벤트리본", "活动奖章",
                       "活動獎章"}},
            {"Excited Mark", {"きたいのあかし", nullptr, "Insigne Enthousiasme", "Emblema Speranza",
                              "Vorfreude-Zeichen", "Emblema Ilusión", "기대의증표", "期待之证", "期待之證"}},
            {"Expert Battler", {"マスターバトルリボン", nullptr, "Génie du Combat", "Genio della Lotta", "Meisterkampf",
                                "As del Combate", "마스터배틀리본", "大师对战奖章", "大師對戰獎章"}},
            {"Ferocious Mark", {"ほんのうのあかし", nullptr, "Insigne Impulsivité", "Emblema Istinto",
                                "Impulsiv-Zeichen", "Emblema Impulsividad", "본능의증표", "本能之证", "本能之證"}},
            {"Fishing Mark", {"つりあげられたあかし", nullptr, "Insigne Pêche", "Emblema Pesca", "Angel-Zeichen",
                              "Emblema Pesca", "낚아올린증표", "上钩之证", "上鉤之證"}},
            {"Flustered Mark", {"どうようのあかし", nullptr, "Insigne Panique", "Emblema Agitazione", "Panik-Zeichen",
                                "Emblema Desconcierto", "동요의증표", "动摇之证", "動搖之證"}},
            {"Footprint", {"あしあとリボン", nullptr, "Empreinte", "Orma", "Fußabdruck", "Huella", "발자국리본", "脚印奖章",
                           "腳印獎章"}},
            {"Galar Champion", {"ガラル チャンプリボン", nullptr, "Maître de Galar", "Campione Galar", "Galar-Champs",
                                "Campeón de Galar", "가라르챔피언리본", "伽勒尔冠军奖章", "伽勒爾冠軍獎章"}},
            {"Gorgeous", {"ゴージャスリボン", nullptr, "Sublime", "Meraviglia", "Hinreißendes", "Maravilla", "고저스리본",
                          "豪华奖章", "豪華獎章"}},
            {"Gorgeous Royal", {"ゴージャスロイヤルリボン", nullptr, "Royal Sublime", "Meraviglia Reale",
                                "Hinreißendes Königliches", "Realeza Maravilla", "고저스로열리본", "豪华高贵奖章", "豪華高貴獎章"}},
            {"Gourmand Mark", {"グルメなあかし", nullptr, "Insigne Gourmet", "Emblema Gourmet", "Gourmet-Zeichen",
                               "Emblema Sibaritismo", "미식가의증표", "美食之证", "美食之證"}},
            {"Great Ability", {"グレートアビリティリボン", nullptr, "Aptitude Méga", "Abilità Mega", "Fähigkeit Groß",
                               "Gran Habilidad", "그레이트어빌리티리본", "超级才能奖章", "超級才能獎章"}},
            {"Hisui", {"ヒスイリボン", nullptr, "Hisui", "Hisui", "Hisui", "Hisui", "히스이리본", "洗翠奖章", "洗翠獎章"}},
            {"Hoenn Champion", {"ホウエン　チャンプリボン", nullptr, "Maître de Hoenn", "Campione Hoenn", "Hoenn-Champs",
                                "Campeón de Hoenn", "호연챔피언리본", "丰缘冠军奖章", "豐緣冠軍獎章"}},
            {"Humble Mark", {"ぼくとつのあかし", nullptr, "Insigne Discrétion", "Emblema Ingenuità", "Arglos-Zeichen",
                             "Emblema Sencillez", "순박의증표", "木讷之证", "木訥之證"}},
            {"Intellectual Mark", {"りせいのあかし", nullptr, "Insigne Réflexion", "Emblema Ragione",
                                   "Verstands-Zeichen", "Emblema Intelecto", "이성의증표", "理性之证", "理性之證"}},
            {"Intense Mark", {"じょうねつのあかし", nullptr, "Insigne Sang Chaud", "Emblema Sangue Caldo",
                              "Hitzkopf-Zeichen", "Emblema Pasión", "정열의증표", "热情之证", "熱情之證"}},
            {"Itemfinder Mark", {"ものひろいのあかし", nullptr, "Insigne Ramassage", "Emblema Pigliatutto",
                                 "Aufsammler-Zeichen", "Emblema Recolección", "습득의증표", "捡拾之证", "撿拾之證"}},
            {"Jittery Mark", {"きんちょうのあかし", nullptr, "Insigne Nervosité", "Emblema Nervosismo",
                              "Spannungs-Zeichen", "Emblema Nerviosismo", "긴장의증표", "紧张之证", "緊張之證"}},
            {"Joyful Mark", {"たこうのあかし", nullptr, "Insigne Bonheur", "Emblema Felicità",
                             "Glücklichkeits-Zeichen", "Emblema Felicidad", "다행의증표", "幸福之证", "幸福之證"}},
            {"Jumbo Mark", {"でっかいあかし", nullptr, "Insigne Maxi", "Emblema Grande e Grosso", "Riesen-Zeichen",
                            "Emblema Enormidad", "커다란증표", "大个子之证", "大個子之證"}},
            {"Kalos Champion", {"カロス　チャンプリボン", nullptr, "Maître de Kalos", "Campione Kalos", "Kalos-Champs",
                                "Campeón de Kalos", "칼로스챔피언리본", "卡洛斯冠军奖章", "卡洛斯冠軍獎章"}},
            {"Kindly Mark", {"やさがたのあかし", nullptr, "Insigne Gentillesse", "Emblema Aria Gentile",
                             "Sanftmut-Zeichen", "Emblema Amabilidad", "상냥함의증표", "优雅之证", "優雅之證"}},
            {"Legend", {"レジェンドリボン", nullptr, "Légende", "Leggenda", "Legende", "Leyenda", "레전드리본", "传说奖章",
                        "傳說獎章"}},
            {"Lunchtime Mark", {"しょうごのあかし", nullptr, "Insigne Appétit", "Emblema Mezzogiorno",
                                "Mittags-Zeichen", "Emblema Almuerzo", "정오의증표", "正午之证", "正午之證"}},
            {"Master Rank", {"マスターランクリボン", nullptr, "Top du Classement", "Asso Competizione", "Meisterrang",
                             "Rango Maestro", "마스터랭크리본", "级别对战大师奖章", "級別對戰大師獎章"}},
            {"Mightiest Mark", {"さいきょうのあかし", nullptr, "Insigne Surpuissant", "Emblema della Forza Assoluta",
                                "Titanen-Zeichen", "Emblema Imbatibilidad", "최강의증표", "最强之证", "最強之證"}},
            {"Mini Mark", {"ちっちゃいあかし", nullptr, "Insigne Mini", "Emblema Piccoletto", "Winzlings-Zeichen",
                           "Emblema Miniatura", "조그만증표", "小不点之证", "小不點之證"}},
            {"Misty Mark", {"のうむのあかし", nullptr, "Insigne Brume", "Emblema Nebbia", "Nebel-Zeichen",
                            "Emblema Niebla", "짙은안개의증표", "浓雾之证", "濃霧之證"}},
            {"Multi Ability", {"マルチアビリティリボン", nullptr, "Aptitude Multi", "Abilità Multipla", "Fähigkeit Multi",
                               "Habilidad Múltiple", "멀티어빌리티리본", "多人才能奖章", "多人才能獎章"}},
            {"National", {"ナショナルリボン", nullptr, "National", "Nazionale", "Nation", "Nacional", "내셔널리본", "国家奖章",
                          "國家獎章"}},
            {"National Champion", {"ナショナルチャンプリボン", nullptr, "Champion National", "Campione Nazionale",
                                   "Nationalmeister", "Campeón Nacional", "내셔널챔피언리본", "国家冠军奖章", "國家冠軍獎章"}},
            {"Once-in-a-Lifetime", {"せんざいいちぐうリボン", nullptr, "Exceptionnel", "Eccezionale", "Glückstrefferband",
                                    "Excepcionalidad", "천재일우리본", "千载难逢奖章", "千載難逢獎章"}},
            {"Pair Ability", {"ペアアビリティリボン", nullptr, "Aptitude Paire", "Abilità Insieme", "Fähigkeit Paar",
                              "Habilidad Par", "페어어빌리티리본", "组队双打才能奖章", "組隊雙打才能獎章"}},
            {"Paldea Champion", {"パルデア　チャンプリボン", nullptr, "Maître de Paldea", "Campione Paldea",
                                 "Paldea-Champs", "Campeón de Paldea", "팔데아챔피언리본", "帕底亚冠军奖章", "帕底亞冠軍獎章"}},
            {"Partner", {"パートナーリボン", nullptr, "Partenaire", "Compagno", "Partner", "Camarada", "파트너리본", "同伴奖章",
                         "同伴獎章"}},
            {"Partner Mark", {"あいぼうのあかし", nullptr, "Insigne Amitié", "Emblema Compagno Fidato",
                              "Partner-Zeichen", "Emblema Compañerismo", "파트너의증표", "搭档之证", "搭檔之證"}},
            {"Peeved Mark", {"げきはつのあかし", nullptr, "Insigne Saute d’Humeur", "Emblema Malumore",
                             "Missmut-Zeichen", "Emblema Mal Humor", "격렬의증표", "激动之证", "激動之證"}},
            {"Premier", {"プレミアリボン", nullptr, "Premier", "Principale", "Premier", "Principal", "프리미어리본", "纪念奖章",
                         "紀念獎章"}},
            {"Prideful Mark", {"じしんのあかし", nullptr, "Insigne Fierté", "Emblema Sicurezza",
                               "Selbstvertrauens-Zeichen", "Emblema Confianza", "자신의증표", "自信之证", "自信之證"}},
            {"Pumped-Up Mark", {"こうようのあかし", nullptr, "Insigne Entrain", "Emblema Entusiasmo",
                                "Ansporn-Zeichen", "Emblema Motivación", "고양의증표", "昂扬之证", "昂揚之證"}},
            {"Rainy Mark", {"あめふりのあかし", nullptr, "Insigne Pluie", "Emblema Pioggia", "Regen-Zeichen",
                            "Emblema Lluvia", "강우의증표", "降雨之证", "降雨之證"}},
            {"Rare Mark", {"みたことのないあかし", nullptr, "Insigne Rareté", "Emblema Rarità", "Raritäts-Zeichen",
                           "Emblema Rareza", "본적없는증표", "未知之证", "未知之證"}},
            {"Record", {"レコードリボン", nullptr, "Record", "Record", "Rekord", "Récord", "레코드리본", "纪录奖章", "紀錄獎章"}},
            {"Regional Champion", {"エリアチャンプリボン", nullptr, "Champion Régional", "Campione Locale",
                                   "Regionalmeister", "Campeón de Área", "에리어챔피언리본", "地区冠军奖章", "地區冠軍獎章"}},
            {"Relax", {"すっきリボン", nullptr, "Détente", "Relax", "Entspannung", "Relax", "상쾌리본", "畅快奖章", "爽快獎章"}},
            {"Rowdy Mark", {"わんぱくなあかし", nullptr, "Insigne Espièglerie", "Emblema Monello", "Raufbold-Zeichen",
                            "Emblema Travesura", "장난꾸러기증표", "淘气之证", "淘氣之證"}},
            {"Royal", {"ロイヤルリボン", nullptr, "Royal", "Reale", "Königliches", "Realeza", "로열리본", "高贵奖章", "高貴獎章"}},
            {"Sandstorm Mark", {"さじんのあかし", nullptr, "Insigne Tempête de Sable", "Emblema Tempesta di Sabbia",
                                "Sandsturm-Zeichen", "Emblema Polvareda", "모래먼지의증표", "沙尘之证", "沙塵之證"}},
            {"Scowling Mark", {"こわもてのあかし", nullptr, "Insigne Menace", "Emblema Aria Minacciosa",
                               "Grimmig-Zeichen", "Emblema Intimidación", "두려움의증표", "凶悍之证", "兇悍之證"}},
            {"Shock", {"どっきリボン", nullptr, "Choc", "Stupore", "Schocks", "Impacto", "철렁리본", "心跳奖章", "心跳獎章"}},
            {"Sinnoh Champion", {"シンオウ　チャンプリボン", nullptr, "Maître de Sinnoh", "Campione Sinnoh",
                                 "Sinnoh-Champs", "Campeón de Sinnoh", "신오챔피언리본", "神奥冠军奖章", "神奧冠軍獎章"}},
            {"Skillful Battler", {"グレートバトルリボン", nullptr, "Élite du Combat", "Asso della Lotta", "Profikampf",
                                  "Figura del Combate", "그레이트배틀리본", "高手对战奖章", "高手對戰獎章"}},
            {"Sleepy-Time Mark", {"しょうしのあかし", nullptr, "Insigne Minuit", "Emblema Mezzanotte",
                                  "Mitternachts-Zeichen", "Emblema Noche", "자정의증표", "午夜之证", "午夜之證"}},
            {"Slump Mark", {"ふちょうのあかし", nullptr, "Insigne Blessure", "Emblema Sottotono", "Formtief-Zeichen",
                            "Emblema Extenuación", "피곤의증표", "不振之证", "不振之證"}},
            {"Smart Great", {"ジーニアスリボングレート", nullptr, "Intelligence Méga", "Acume: Livello Mega",
                             "Klugheit Mega", "Ingenio difícil", "지니어스리본그레이트", "聪明上级奖章", "聰明上級獎章"}},
            {"Smart Hyper", {"ジーニアスリボンハイパー", nullptr, "Intelligence Hyper", "Acume: Livello Iper",
                             "Klugheit Hyper", "Ingenio avanzado", "지니어스리본하이퍼", "聪明高级奖章", "聰明高級獎章"}},
            {"Smart Ribbon", {"ジーニアスリボン", nullptr, "Intelligence", "Acume", "Klugheit", "Ingenio", "지니어스리본",
                              "聪明奖章", "聰明獎章"}},
            {"Smart Ribbon Hyper", {"ジーニアスリボンハイパー", nullptr, "Intelligence Hyper", "Acume: Livello Iper",
                                    "Klugheit Hyper", "Ingenio avanzado", "지니어스리본하이퍼", "聪明高级奖章", "聰明高級獎章"}},
            {"Smart Ribbon Master", {"ジーニアスリボンマスター", nullptr, "Intelligence Master", "Acume: Livello Master",
                                     "Klugheit Master", "Ingenio experto", "지니어스리본마스터", "聪明大师奖章", "聰明大師獎章"}},
            {"Smart Ribbon Super", {"ジーニアスリボンスーパー", nullptr, "Intelligence Super", "Acume: Livello Super",
                                    "Klugheit Super", "Ingenio alto", "지니어스리본슈퍼", "聪明超级奖章", "聰明超級獎章"}},
            {"Smart Super", {"ジーニアスリボンスーパー", nullptr, "Intelligence Super", "Acume: Livello Super",
                             "Klugheit Super", "Ingenio alto", "지니어스리본슈퍼", "聪明超级奖章", "聰明超級獎章"}},
            {"Smart Ultra", {"ジーニアスリボンウルトラ", nullptr, "Intelligence Ultra", "Acume: Livello Ultra",
                             "Klugheit Ultra", "Ingenio superior", "지니어스리본울트라", "聪明究极奖章", "聰明究極獎章"}},
            {"Smile", {"にっこリボン", nullptr, "Sourire", "Sorriso", "Lächelns", "Sonrisa", "방글방글리본", "欢笑奖章", "歡笑獎章"}},
            {"Smiley Mark", {"びしょうのあかし", nullptr, "Insigne Rire", "Emblema Sorriso", "Lächel-Zeichen",
                             "Emblema Sonrisa", "미소의증표", "微笑之证", "微笑之證"}},
            {"Snooze", {"ぐっすリボン", nullptr, "Sieste", "Pisolino", "Schlafens", "Cabezada", "잠보리본", "酣睡奖章",
                        "酣睡獎章"}},
            {"Snowy Mark", {"こうせつのあかし", nullptr, "Insigne Neige", "Emblema Neve", "Schneefall-Zeichen",
                            "Emblema Nieve", "강설의증표", "降雪之证", "降雪之證"}},
            {"Souvenir", {"メモリアルリボン", nullptr, "Souvenir", "Ricordo", "Gedenk", "Recuerdo", "메모리얼리본", "回忆奖章",
                          "回憶獎章"}},
            {"Special", {"スペシャルリボン", nullptr, "Spécial", "Speciale", "Sonder", "Especial", "스페셜리본", "特殊奖章",
                         "特殊獎章"}},
            {"Stormy Mark", {"いかづちのあかし", nullptr, "Insigne Tonnerre", "Emblema Tuoni e Lampi",
                             "Gewitter-Zeichen", "Emblema Tormenta", "우레의증표", "落雷之证", "落雷之證"}},
            {"Teary Mark", {"ひそうのあかし", nullptr, "Insigne Pleurs", "Emblema Sconforto", "Trübsal-Zeichen",
                            "Emblema Llanto", "비통의증표", "悲伤之证", "悲傷之證"}},
            {"Thorny Mark", {"ふじゅんのあかし", nullptr, "Insigne Frime", "Emblema Artificio", "Scheinheilig-Zeichen",
                             "Emblema Altanería", "불순의증표", "不纯之证", "不純之證"}},
            {"Titan Mark", {"ヌシのあかし", nullptr, "Insigne Dominant", "Emblema del dominante",
                            "Herrscher-Zeichen", "Emblema Dominancia", "주인의증표", "宝主之证", "寳主之證"}},
            {"Tough Great", {"パワフルリボングレート", nullptr, "Robustesse Méga", "Grinta: Livello Mega", "Stärke Mega",
                             "Dureza difícil", "파워풀리본그레이트", "强壮上级奖章", "強壯上級獎章"}},
            {"Tough Hyper", {"パワフルリボンハイパー", nullptr, "Robustesse Hyper", "Grinta: Livello Iper",
                             "Stärke Hyper", "Dureza avanzado", "파워풀리본하이퍼", "强壮高级奖章", "強壯高級獎章"}},
            {"Tough Ribbon", {"パワフルリボン", nullptr, "Robustesse", "Grinta", "Stärke", "Dureza", "파워풀리본", "强壮奖章",
                              "強壯獎章"}},
            {"Tough Ribbon Hyper", {"パワフルリボンハイパー", nullptr, "Robustesse Hyper", "Grinta: Livello Iper",
                                    "Stärke Hyper", "Dureza avanzado", "파워풀리본하이퍼", "强壮高级奖章", "強壯高級獎章"}},
            {"Tough Ribbon Master", {"パワフルリボンマスター", nullptr, "Robustesse Master", "Grinta: Livello Master",
                                     "Stärke Master", "Dureza experto", "파워풀리본마스터", "强壮大师奖章", "強壯大師獎章"}},
            {"Tough Ribbon Super", {"パワフルリボンスーパー", nullptr, "Robustesse Super", "Grinta: Livello Super",
                                    "Stärke Super", "Dureza alto", "파워풀리본슈퍼", "强壮超级奖章", "強壯超級獎章"}},
            {"Tough Super", {"パワフルリボンスーパー", nullptr, "Robustesse Super", "Grinta: Livello Super",
                             "Stärke Super", "Dureza alto", "파워풀리본슈퍼", "强壮超级奖章", "強壯超級獎章"}},
            {"Tough Ultra", {"パワフルリボンウルトラ", nullptr, "Robustesse Ultra", "Grinta: Livello Ultra",
                             "Stärke Ultra", "Dureza superior", "파워풀리본울트라", "强壮究极奖章", "強壯究極獎章"}},
            {"Toughness Master", {"たくましさマスターリボン", nullptr, "Maître Robustesse", "Grinta Suprema",
                                  "Stärke Master", "Dureza experto", "강인함마스터리본", "强壮大师奖章", "強壯大師獎章"}},
            {"Tower Master", {"マスタータワーリボン", nullptr, "Maître de la Tour", "Asso della Torre", "Meisterturm",
                              "Maestro de la Torre", "마스터타워리본", "对战塔大师奖章", "對戰塔大師獎章"}},
            {"Training", {"しゅぎょうリボン", nullptr, "Perfectionnement", "Training", "Trainings", "Ejercicio",
                          "수행리본", "修行奖章", "修行獎章"}},
            {"Twinkling Star", {"トゥインクルスターリボン", nullptr, "Étoile Brillante", "Stella Brillante",
                                "Glitzersternband", "Estrella Rutilante", "트윙클스타리본", "闪亮之星奖章", "閃亮之星獎章"}},
            {"Uncommon Mark", {"ときどきみるあかし", nullptr, "Insigne Sociabilité", "Emblema Sporadicità",
                               "Gängigkeits-Zeichen", "Emblema Familiaridad", "가끔보는증표", "偶遇之证", "偶遇之證"}},
            {"Unsure Mark", {"ふしんのあかし", nullptr, "Insigne Abattement", "Emblema Insicurezza",
                             "Selbstzweifel-Zeichen", "Emblema Inseguridad", "불신의증표", "自卑之证", "自卑之證"}},
            {"Upbeat Mark", {"かいちょうのあかし", nullptr, "Insigne Bonne Humeur", "Emblema Buonumore",
                             "Heiterkeits-Zeichen", "Emblema Buen Humor", "쾌조의증표", "爽快之证", "爽快之證"}},
            {"Victory", {"ビクトリーリボン", nullptr, "Victoire", "Trionfo", "Sieges", "Victoria", "빅토리리본", "胜利奖章",
                         "勝利獎章"}},
            {"Vigor Mark", {"げんきのあかし", nullptr, "Insigne Énergie", "Emblema Vitalità", "Elan-Zeichen",
                            "Emblema Vigor", "기력의증표", "活力之证", "活力之證"}},
            {"Winning", {"ウイニングリボン", nullptr, "Gagnant", "Vittoria", "Gewinners", "Ganador", "위닝리본", "成功奖章",
                         "成功獎章"}},
            {"Wishing", {"ウィッシュリボン", nullptr, "Souhait", "Desiderio", "Wunsch", "Deseo", "위시리본", "许愿奖章", "許願獎章"}},
            {"World", {"ワールドリボン", nullptr, "Monde", "Mondiale", "Welt", "Mundo", "월드리본", "世界奖章", "世界獎章"}},
            {"World Ability", {"ワールドアビリティリボン", nullptr, "Aptitude Monde", "Abilità Mondiale", "Fähigkeit Welt",
                               "Hablildad Mundial", "월드어빌리티리본", "世界才能奖章", "世界才能獎章"}},
            {"World Champion", {"ワールドチャンプリボン", nullptr, "Champion du Monde", "Campione Mondiale",
                                "Weltmeister", "Campeón Mundial", "월드챔피언리본", "世界冠军奖章", "世界冠軍獎章"}},
            {"Zero Energy Mark", {"けんたいのあかし", nullptr, "Insigne Nonchalance", "Emblema Pigrizia",
                                  "Lustlos-Zeichen", "Emblema Desgana", "권태의증표", "倦怠之证", "倦怠之證"}},
            {"Zoned-Out Mark", {"ゆだんのあかし", nullptr, "Insigne Inattention", "Emblema Disattenzione",
                                "Achtlos-Zeichen", "Emblema Distracción", "방심의증표", "疏忽之证", "疏忽之證"}},
        };
    }

    const char *getRibbonNameLocalized(const char *englishName, size_t languageIndex)
    {
        if (englishName == nullptr || languageIndex >= LANGUAGE_COUNT)
            return nullptr;
        constexpr size_t count =
            sizeof(LOCALIZED_RIBBON_NAMES) / sizeof(LOCALIZED_RIBBON_NAMES[0]);
        size_t low = 0, high = count;
        while (low < high)
        {
            const size_t middle = low + (high - low) / 2;
            const int order = std::strcmp(LOCALIZED_RIBBON_NAMES[middle].english, englishName);
            if (order < 0)
                low = middle + 1;
            else if (order == 0)
                return LOCALIZED_RIBBON_NAMES[middle].names[languageIndex];
            else
                high = middle;
        }
        return nullptr;
    }
}
