/**
 *
 * Auto-generated by tools/gen_evolutions.py from PKHeX's evos_*.pkl.
 * DO NOT EDIT BY HAND -- rerun the generator instead.
 *
 * Per game, because the chains differ: Pichu is absent from Let's Go, so a Pikachu
 * there has no ancestor, and a Hisuian form's ancestor is not its Kantonian one.
 * An edge is present only when both ends exist in that game.
 *
 * Layer 3 legality is the caller: an encounter template names the species that was
 * caught, so an evolved Pokemon has to be matched against its pre-evolution's slots.
 */
#ifndef PKM_EVOLUTION_TABLE_H
#define PKM_EVOLUTION_TABLE_H

#include <cstdint>

#include "Enums/GameVersion.h"

namespace Pokemon {

    /// Longest pre-evolution chain the tables can hold (real max is 2 -- Bulbasaur ->
    /// Ivysaur -> Venusaur gives Venusaur two ancestors; the extra slot is slack).
    constexpr int EVO_MAX_CHAIN = 4;

    /**
     * Immediate pre-evolution of (species, form) in `group`.
     *
     * Returns false when the species is the base of its chain, when the group has no
     * table, or when either end is absent from that game -- all of which mean "nothing
     * evolved into this here", never "unknown".
     */
    bool getPreEvolution(Enums::GameVersion group, uint16_t species, uint8_t form, uint16_t& outSpecies, uint8_t& outForm);

    /**
     * Full pre-evolution chain for (species, form), nearest ancestor first.
     *
     * Writes at most `max` entries and returns how many were written. The species
     * itself is NOT included.
     */
    int getPreEvolutionChain(Enums::GameVersion group, uint16_t species, uint8_t form, uint16_t* outSpecies, uint8_t* outForm, int max);

    /**
     * Lowest CURRENT level at which (species, form) can exist in `group`, given that it was
     * OBTAINED as its ancestor `stepsBack` links down the chain.
     *
     * `stepsBack` 0 is the species itself and always answers 0: a Pokemon caught as what it is
     * has no evolution to have satisfied. That distinction is the whole point -- Gold/Silver put
     * wild Noctowl on Route 2 at level 7, thirteen levels below the level a Hoothoot evolves at,
     * so "Noctowl must be level 20" is true of an evolved one and false of a caught one.
     *
     * Every link is asked, not just the last: a three-stage chain has two floors and the binding
     * one is the higher. Returns 0 for a group with no table, which reads as no constraint.
     */
    uint8_t getEvolutionLevelFloor(Enums::GameVersion group, uint16_t species, uint8_t form, int stepsBack);

    /** How a trade evolution is triggered. */
    enum class TradeEvolutionTrigger : uint8_t
    {
        Trade = 0,          ///< trading alone
        HeldItem = 1,       ///< trading while holding one specific item, which the evolution consumes
        PartnerSpecies = 2, ///< trading FOR one specific other species (Karrablast / Shelmet)
    };

    /** One trade evolution a (species, form) can undergo in one game. */
    struct TradeEvolution
    {
        uint16_t speciesId;
        uint8_t  formId;
        uint16_t destinationSpeciesId;
        uint8_t  destinationFormId;
        TradeEvolutionTrigger trigger;
        /// HeldItem only, in THE GAME'S OWN item id space -- Metal Coat is 199 in Gen 3 and 233
        /// from Gen 4 on, so this is read through getItemNameFor(group, ...). 0 otherwise.
        uint16_t requiredItemId;
        /// PartnerSpecies only: the species that has to be on the other end of the trade.
        uint16_t partnerSpeciesId;
    };

    /// Clamperl is the only species with two, one per held item (Huntail / Gorebyss).
    constexpr int TRADE_EVOLUTIONS_MAX_PER_SPECIES = 2;

    /**
     * Every trade evolution (speciesId, formId) has in `group`, written to `outEvolutions`.
     *
     * Returns how many were written, at most `maxEvolutions`. Zero means this species+form has no
     * trade evolution in this game -- either it has none anywhere, or one end of it is absent from
     * this game (Let's Go carries rows for Pokemon it does not have; they are filtered out here).
     *
     * The rows describe what the GAME does, not what the Pokemon can do right now: a HeldItem row
     * is returned whether or not the Pokemon is holding the item. Deciding that is the caller's,
     * so that a button can be shown and disabled rather than hidden.
     */
    int getTradeEvolutions(Enums::GameVersion group, uint16_t speciesId, uint8_t formId,
                           TradeEvolution *outEvolutions, int maxEvolutions);
}

#endif  // PKM_EVOLUTION_TABLE_H
