/**
 * LearnsetTable.h - Per-species+form "learnable move" bitsets (legality Layer-2:
 *                   is a move learnable by this Pokemon?)
 *
 * Auto-generated by tools/gen_learnsets.py from PKHeX's binary learnset resources.
 * DO NOT EDIT BY HAND -- rerun the generator instead.
 *
 * For a (species, form) present in a game, that game's bitset holds bit M set =>
 * the species+form can legally KNOW move M in that game (union of level-up / egg /
 * TM / TR / tutor / reminder, then unioned with its whole pre-evolution chain --
 * an evolved Pokemon keeps what it learned earlier). Rows mirror
 * PersonalInfoTable (base rows 0..1025, then alt forms via formIndex). All six
 * supported games are carried: GG, SWSH, BDSP, PLA, SV, ZA. Bitsets share one
 * uniform width sized to hold move id 920 (ZA's NihilLight).
 */
#ifndef PKM_LEARNSET_TABLE_H
#define PKM_LEARNSET_TABLE_H

#include <cstdint>
#include <cstddef>

#include "Enums/GameVersion.h"

namespace Pokemon {
    constexpr uint16_t LEARN_MAX_SPECIES = 1025;
    constexpr uint16_t LEARN_MAX_MOVE_ID = 920;   // ZA NihilLight; move space 0..920
    constexpr size_t   LEARN_BITSET_BYTES = 116;    // uniform width for every game

    // Pointer to the 116-byte learnable bitset for (species, form) in the given
    // game group, or nullptr if the species+form is absent from that game. Accepts a
    // GameVersion group (GG/SWSH/BDSP/PLA/SV/ZA) or an individual version (e.g.
    // GP/GE, SW/SH, BD/SP, SL/VL) -- both resolve to the right game.
    const uint8_t* getLearnableBits(uint16_t species, uint8_t form, Enums::GameVersion group);

    // True iff moveId is in the (species, form) learnable pool for the game group.
    bool isLearnable(uint16_t species, uint8_t form, Enums::GameVersion group, uint16_t moveId);
}

#endif  // PKM_LEARNSET_TABLE_H
