/**
 * PersonalInfoTable.h - Per-species "personal info" (abilities / gender / friendship
 *                       / form count / per-game presence)
 *
 * Auto-generated by tools/gen_personal.py from PKHeX's binary personal tables.
 * DO NOT EDIT BY HAND -- rerun the generator instead.
 *
 * Species-level fields come from PKHeX's Scarlet/Violet table (the most complete,
 * spanning National Dex 0..1025); alternate forms are the union across the six
 * supported games. See the generator's module docstring for offsets and provenance.
 */
#ifndef PKM_PERSONAL_INFO_TABLE_H
#define PKM_PERSONAL_INFO_TABLE_H

#include <cstdint>
#include <cstddef>

namespace Pokemon {
    // Per-game presence bits packed into PersonalInfo::presence.
    enum PersonalGameBit : uint8_t {
        PERSONAL_GAME_GG   = 1 << 0,  // Let's Go, Pikachu! / Eevee!
        PERSONAL_GAME_SWSH = 1 << 1,  // Sword / Shield
        PERSONAL_GAME_BDSP = 1 << 2,  // Brilliant Diamond / Shining Pearl
        PERSONAL_GAME_PLA  = 1 << 3,  // Legends: Arceus
        PERSONAL_GAME_SV   = 1 << 4,  // Scarlet / Violet
        PERSONAL_GAME_ZA   = 1 << 5,  // Legends: Z-A
    };

    // One entry per (species, form). Ability IDs are National ability indices (same
    // space as PKSE's Names::ABILITY_NAMES). genderRatio is the raw PKHeX gender byte:
    //   0   = always male      254 = always female      255 = genderless
    //   else = threshold; PID gender-value < genderRatio means female.
    // PKHeX stores "no second ability" as ability2 == ability1 (not 0).
    struct PersonalInfo {
        uint16_t ability1;
        uint16_t ability2;
        uint16_t abilityHidden;
        uint16_t formIndex;       // table index of this species' form 1 (0 = no alt forms)
        uint8_t  genderRatio;
        uint8_t  baseFriendship;
        uint8_t  formCount;       // number of forms across supported games; valid forms are 0..formCount-1
        uint8_t  presence;        // OR of PersonalGameBit: which games this species+form exists in
        uint8_t  type1;           // Gen 6+ type ids -- the PokemonTypes.h TYPE_* constants
        uint8_t  type2;           // TYPE_NONE (255) when single-typed
        uint16_t height;          // PKHeX personal Height (base) -- used for the LGPE absolute size
        uint16_t weight;          // PKHeX personal Weight (base)
    };

    constexpr uint16_t PERSONAL_MAX_SPECIES = 1025;
    constexpr size_t   PERSONAL_INFO_TABLE_COUNT = 1491;

    // Flat table: indices 0..1025 are the form-0 (base) entries; 1026.. are the
    // alternate-form entries a base row's formIndex redirects into.
    extern const PersonalInfo PERSONAL_INFO_TABLE[PERSONAL_INFO_TABLE_COUNT];

    // Resolve a (species, form) to its entry, mirroring PKHeX's FormIndex redirection.
    // Out-of-range species or forms fall back to the species' form-0 (or index 0) entry.
    const PersonalInfo& getPersonalInfo(uint16_t species, uint8_t form);

    // ---- Generation 3 (FireRed/LeafGreen) abilities + types ----
    // Gen 3's slot pair is NOT the one above: the S/V row disagrees for 101 of these
    // species and always carries a hidden ability, which Gen 3 has no slot for. A PK3
    // stores only a selector BIT and the game resolves it through its own table, so
    // this is the only table that describes what a Gen 3 mon can actually hold.
    // Forms share a row (PKHeX PersonalTable3.GetFormIndex is the species id).
    //
    // Its TYPES disagree with the modern table too, for 18 of the 386 species: Gen 3
    // predates the Fairy type, so Clefairy is Normal there and Fairy in Scarlet/Violet.
    // These are the SAME Gen 6+ type ids used above -- only the values differ, not the
    // encoding -- so a caller switches table without translating.
    struct PersonalAbilityG3 {
        uint8_t ability1;
        uint8_t ability2;   // == ability1 when the species has only one ability
        uint8_t type1;
        uint8_t type2;      // TYPE_NONE (255) when single-typed
    };

    constexpr uint16_t PERSONAL_G3_MAX_SPECIES = 386;

    extern const PersonalAbilityG3 PERSONAL_ABILITY_G3[PERSONAL_G3_MAX_SPECIES + 1];

    // Gen 3 ability slots + types for a species. Out-of-range species return all-zero
    // abilities and Normal/none, the same shape the modern lookup falls back to.
    const PersonalAbilityG3& getPersonalAbilityG3(uint16_t species);
}

#endif  // PKM_PERSONAL_INFO_TABLE_H
