/**
 * PersonalInfoTable.h - Per-species "personal info" (abilities / gender / friendship
 *                       / form count / per-game presence)
 *
 * Auto-generated by tools/gen_personal.py from PKHeX's binary personal tables.
 * DO NOT EDIT BY HAND -- rerun the generator instead.
 *
 * Species-level fields come from PKHeX's Scarlet/Violet table (the most complete,
 * spanning National Dex 0..1025); alternate forms are the union across the six
 * supported games. See the generator's module docstring for offsets and provenance.
 */
#ifndef PKM_PERSONAL_INFO_TABLE_H
#define PKM_PERSONAL_INFO_TABLE_H

#include <cstdint>
#include <cstddef>

namespace Pokemon {
    // Per-game presence bits packed into PersonalInfo::presence.
    enum PersonalGameBit : uint8_t {
        PERSONAL_GAME_GG   = 1 << 0,  // Let's Go, Pikachu! / Eevee!
        PERSONAL_GAME_SWSH = 1 << 1,  // Sword / Shield
        PERSONAL_GAME_BDSP = 1 << 2,  // Brilliant Diamond / Shining Pearl
        PERSONAL_GAME_PLA  = 1 << 3,  // Legends: Arceus
        PERSONAL_GAME_SV   = 1 << 4,  // Scarlet / Violet
        PERSONAL_GAME_ZA   = 1 << 5,  // Legends: Z-A
    };

    // One entry per (species, form). Ability IDs are National ability indices (same
    // space as PKSE's Names::ABILITY_NAMES). genderRatio is the raw PKHeX gender byte:
    //   0   = always male      254 = always female      255 = genderless
    //   else = threshold; PID gender-value < genderRatio means female.
    // PKHeX stores "no second ability" as ability2 == ability1 (not 0).
    struct PersonalInfo {
        uint16_t ability1;
        uint16_t ability2;
        uint16_t abilityHidden;
        uint16_t formIndex;       // table index of this species' form 1 (0 = no alt forms)
        uint8_t  genderRatio;
        uint8_t  baseFriendship;
        uint8_t  formCount;       // number of forms across supported games; valid forms are 0..formCount-1
        uint8_t  presence;        // OR of PersonalGameBit: which games this species+form exists in
        uint8_t  type1;           // Gen 6+ type ids -- the PokemonTypes.h TYPE_* constants
        uint8_t  type2;           // TYPE_NONE (255) when single-typed
        uint16_t height;          // PKHeX personal Height (base) -- used for the LGPE absolute size
        uint16_t weight;          // PKHeX personal Weight (base)
    };

    constexpr uint16_t PERSONAL_MAX_SPECIES = 1025;
    constexpr size_t   PERSONAL_INFO_TABLE_COUNT = 1491;

    // Flat table: indices 0..1025 are the form-0 (base) entries; 1026.. are the
    // alternate-form entries a base row's formIndex redirects into.
    extern const PersonalInfo PERSONAL_INFO_TABLE[PERSONAL_INFO_TABLE_COUNT];

    // Resolve a (species, form) to its entry, mirroring PKHeX's FormIndex redirection.
    // Out-of-range species or forms fall back to the species' form-0 (or index 0) entry.
    const PersonalInfo& getPersonalInfo(uint16_t species, uint8_t form);

    // ---- Generation 3 (FireRed/LeafGreen) base stats + abilities + types ----
    // Everything a Gen 3 entity needs looked up, from Gen 3's OWN personal table. Every
    // field here disagrees with the modern table for some species, which is the whole
    // reason it exists. Forms share a row (PKHeX PersonalTable3.GetFormIndex is the
    // species id), so there is no form parameter.
    //
    // BASE STATS: 42 of the 386 species differ from the modern (S/V) table, nearly all of
    // them from the Gen 6 stat pass -- Pikachu is 30 Def / 40 SpD here and 40 / 50 in Sword,
    // Dugtrio's Attack went 80 -> 100. PKSE writes the six computed battle stats into a Gen 3
    // party record, so a modern base stat does not merely display wrong, it gets saved into
    // the game.
    //
    // ABILITIES: the S/V slot pair disagrees for 101 of these species and always carries a
    // hidden ability, which Gen 3 has no slot for. A PK3 stores only a selector BIT and the
    // game resolves it through its own table, so an S/V-only ability writes a bit that
    // displays as something else.
    //
    // TYPES: 18 species differ, because Gen 3 predates the Fairy type -- Clefairy is Normal
    // here and Fairy in Scarlet/Violet. These are the SAME Gen 6+ type ids used above; only
    // the values differ, not the encoding, so a caller switches table without translating.
    //
    // ONE CAVEAT, Deoxys (#386): its forme is chosen by the GAME and not stored in the
    // entity, so FireRed and LeafGreen disagree on this row alone. These are FireRed's
    // (Attack Forme) stats -- a PK3 carries no Deoxys form field for a lookup to key on.
    struct PersonalInfoG3 {
        // Declaration order is PKHeX's personal-table order (HP, ATK, DEF, SPE, SPA, SPD),
        // which is NOT the order BaseStatsGen89 uses. Access by name, never by position.
        uint8_t hp;
        uint8_t atk;
        uint8_t def;
        uint8_t spe;
        uint8_t spa;
        uint8_t spd;
        uint8_t ability1;
        uint8_t ability2;   // == ability1 when the species has only one ability
        uint8_t type1;
        uint8_t type2;      // TYPE_NONE (255) when single-typed
    };

    constexpr uint16_t PERSONAL_G3_MAX_SPECIES = 386;

    extern const PersonalInfoG3 PERSONAL_INFO_G3[PERSONAL_G3_MAX_SPECIES + 1];

    // Gen 3 base stats + ability slots + types for a species. Out-of-range species return an
    // all-zero row, the same shape the modern lookup falls back to -- a caller that computes
    // a stat from it must treat a 0 base as "no data", not as a real base stat.
    const PersonalInfoG3& getPersonalInfoG3(uint16_t species);
}

#endif  // PKM_PERSONAL_INFO_TABLE_H
