/**
 * PLADexTable.h - Legends: Arceus Pokedex lookup tables. GENERATED by tools/gen_pladex.py.
 *
 * PLA's dex block is a research LOG, split into a per-SPECIES research entry (0x58 bytes) and a
 * per-SPECIES+FORM statistics entry (0x18 bytes) that holds the seen/obtained flags. The statistics
 * entries are not indexed by species: they are reached through a lookup keyed by
 * `species | (form << 11)`, an arbitrary ordering with no derivable structure. Copied verbatim from
 * PKHeX PokedexConstants8a; do not hand-edit, rerun the generator.
 */
#ifndef POKEMON_PLA_DEX_TABLE_H
#define POKEMON_PLA_DEX_TABLE_H

#include <cstdint>

namespace Pokemon {

    /// Returned when the species+form has no statistics entry (it cannot appear in PLA's dex).
    inline constexpr uint16_t PLA_NO_STAT_ENTRY = 0xFFFF;

    /// Number of statistics entries the block allocates.
    inline constexpr uint16_t PLA_STATISTICS_ENTRIES = 1480;

    /// Highest species with a research entry (PKHeX PokedexSave8a.MAX_SPECIES).
    inline constexpr uint16_t PLA_MAX_SPECIES = 981;

    /// Highest form the dex tables address (PKHeX PokedexSave8a.MAX_FORM).
    inline constexpr uint8_t  PLA_MAX_FORM = 120;

    /// Statistics-entry index for a (species, form), or PLA_NO_STAT_ENTRY when it has none.
    uint16_t getPLAStatisticsIndex(uint16_t species, uint8_t form) noexcept;

    /// True when the dex tracks this species+form's genders SEPARATELY (PokemonInfoGenders bit 3).
    /// Where false, the male and female slots are one shared record.
    bool plaTracksGenderSeparately(uint16_t species, uint8_t form) noexcept;
}

#endif
