/**
 * SVDexTable.h - Scarlet/Violet regional-Pokedex membership. GENERATED by tools/gen_svdex.py.
 *
 * S/V has three regional Pokedexes (Paldea, Kitakami, Blueberry) sharing ONE Zukan block. Each
 * 0x20-byte entry carries a separate "displayed variant" slot per regional dex -- form/gender/
 * shiny at 0x14, 0x18 and 0x1C -- and the game only reads the slot for a dex the species is
 * actually listed in. Stamping a slot for a dex it does not belong to makes that Pokedex render
 * a variant it should never show.
 *
 * Membership is per (species, FORM): Kantonian Meowth is a Paldea entry while Alolan Meowth is a
 * Blueberry one. Derived from PKHeX personal_sv (DexPaldea / DexKitakami / DexBlueberry), which
 * PKSE's PersonalInfoTable cannot supply -- its form rows are the union across all supported
 * games, so its indices do not line up. Do not hand-edit; rerun the generator.
 */
#ifndef POKEMON_SV_DEX_TABLE_H
#define POKEMON_SV_DEX_TABLE_H

#include <cstdint>

namespace Pokemon {

    /// Which regional Pokedexes a (species, form) appears in. 0 = not in that dex.
    struct SVDexEntry {
        uint16_t paldea;      ///< Paldea dex index
        uint8_t  kitakami;    ///< Kitakami dex index
        uint8_t  blueberry;   ///< Blueberry dex index

        bool inAnyDex() const noexcept { return paldea != 0 || kitakami != 0 || blueberry != 0; }
    };

    /// Highest National Dex species S/V has a record for.
    inline constexpr uint16_t SV_DEX_MAX_SPECIES = 1025;

    /// Regional-dex membership for a (species, form). Out-of-range species or forms fall back to
    /// the species' form-0 record, mirroring PKHeX PersonalTable9SV.GetFormIndex.
    const SVDexEntry& getSVDexEntry(uint16_t species, uint8_t form) noexcept;
}

#endif
