/**
 * SWSHDexTable.h - Sword/Shield Pokedex entry lookup. GENERATED by tools/gen_swshdex.py.
 *
 * SWSH has THREE Pokedexes, each its own save block with its own numbering: Galar (400
 * entries), Isle of Armor (211) and Crown Tundra (210). A species belongs to exactly one,
 * and its 0x30-byte entry sits at (index - 1) * 0x30 inside that block.
 *
 * Derived from PKHeX personal_swsh (PokeDexIndex / ArmorDexIndex / CrownDexIndex), which is
 * the only place this mapping exists -- it cannot be computed from the Gen 9 personal table
 * the rest of PKSE uses. Do not hand-edit; rerun the generator.
 */
#ifndef POKEMON_SWSH_DEX_TABLE_H
#define POKEMON_SWSH_DEX_TABLE_H

#include <cstdint>

namespace Pokemon {

    /// Which of the three Pokedex blocks a species lives in.
    enum class SWSHDex : uint8_t { None = 0, Galar = 1, Armor = 2, Crown = 3 };

    struct SWSHDexEntry {
        SWSHDex  dex;     ///< None when the species has no SWSH dex entry at all
        uint16_t index;   ///< 1-based index within that dex; entry offset = (index - 1) * 0x30
    };

    /// Entries per dex, for bounds-checking a block before writing into it.
    inline constexpr uint16_t SWSH_DEX_GALAR_COUNT = 400;
    inline constexpr uint16_t SWSH_DEX_ARMOR_COUNT = 211;
    inline constexpr uint16_t SWSH_DEX_CROWN_COUNT = 210;
    inline constexpr uint16_t SWSH_DEX_ENTRY_SIZE  = 0x30;

    /// Dex placement for a National Dex species, or {None, 0} if SWSH has no entry for it.
    SWSHDexEntry getSWSHDexEntry(uint16_t species) noexcept;
}

#endif
