/**
 * ItemPresence.h - Per-game "can a Pokemon HOLD this item?" lookup.
 *
 * Auto-generated by tools/gen_itempresence.py from PKHeX's ItemStorage classes.
 * DO NOT EDIT BY HAND -- rerun the generator instead.
 *
 * Used to sanitize a transferred Pokemon's held item, the same way LearnsetTable
 * sanitizes its moveset. Let's Go and Legends: Arceus have NO held-item mechanic,
 * so they report false for every id. FireRed/LeafGreen ids are Gen 3 ids; every
 * other game uses the modern item space -- callers must pass an id already in the
 * queried game's own space.
 */
#ifndef NAMES_ITEM_PRESENCE_H
#define NAMES_ITEM_PRESENCE_H

#include <cstdint>

#include "Enums/GameVersion.h"

namespace Names {
    constexpr uint16_t ITEM_PRESENCE_MAX_ID = 2684;

    /// True if a Pokemon can legally hold `itemId` in `group`. False for an unknown
    /// group, an out-of-range id, or a game with no held-item mechanic at all.
    bool isHeldItemPresent(uint16_t itemId, Enums::GameVersion group);
}

#endif  // NAMES_ITEM_PRESENCE_H
