/**
 * ItemPouches.h - Which item ids legally belong in each pouch of each game.
 *
 * Auto-generated by tools/gen_itempouches.py from PKHeX's ItemStorage classes.
 * DO NOT EDIT BY HAND -- rerun the generator instead.
 *
 * Answers "what may be ADDED here", for the item editor's create flow -- distinct
 * from ItemPresence.h, which answers "what may a Pokemon HOLD". Pouch indices are
 * that game's own PouchType* enum order (include/Trainer/Inventory*.h).
 *
 * A pouch a game does not actually have (S/V MegaStones, Z-A BattleItems) returns
 * an empty span rather than a guess.
 */
#ifndef NAMES_ITEM_POUCHES_H
#define NAMES_ITEM_POUCHES_H

#include <cstdint>
#include <cstddef>
#include <span>

#include "Enums/GameVersion.h"

namespace Names {
    /// Legal item ids for `pouchIndex` of `group`, in that game's PouchType* order.
    /// Empty when the group is unknown, the index is out of range, or the game has
    /// no such pouch.
    std::span<const uint16_t> getPouchItems(Enums::GameVersion group, size_t pouchIndex);

    /// Number of pouches the table carries for `group` (0 if unknown).
    size_t getPouchCount(Enums::GameVersion group);
}

#endif  // NAMES_ITEM_POUCHES_H
