/**
 * MovePresence.h - Is a move present (usable) in a given game?
 *
 * Auto-generated by tools/gen_movepresence.py from PKHeX (DummiedMoves / AllowedMoves /
 * PP tables). DO NOT EDIT BY HAND -- rerun the generator instead.
 *
 * Mirrors PKHeX's move-editor filter: a game only exposes the moves that exist in it
 * (dropping "dummied"/out-of-range moves). Used by the move picker so a dummied move
 * (e.g. Pound in Legends: Arceus, which the game turns into a Bad Egg) can't be set;
 * species legality is a separate, non-blocking warning.
 */
#ifndef NAMES_MOVE_PRESENCE_H
#define NAMES_MOVE_PRESENCE_H

#include <cstdint>

#include "Enums/GameVersion.h"

namespace Names {
    /// True iff moveId exists (is not dummied / out of range) in the given game group.
    /// Unknown groups return true (no filtering). Id 0 (None) returns false.
    bool isMovePresent(uint16_t moveId, Enums::GameVersion group);
}

#endif  // NAMES_MOVE_PRESENCE_H
