/**
 * MoveInfo.h - Base PP of a move, by move id.
 *
 * Auto-generated by tools/gen_moveinfo.py from PKHeX MoveInfo9.PP.
 * DO NOT EDIT BY HAND -- rerun the generator instead.
 *
 * Used to set a move's PP when it is created or picked in the editor; the entity's
 * setMove() does not set PP on its own, so without this the game reads 0 PP.
 */
#ifndef NAMES_MOVE_INFO_H
#define NAMES_MOVE_INFO_H

#include <cstdint>

namespace Names {
    /// Base PP (with 0 PP-ups) for a move id. Returns 0 for the empty slot (id 0) and
    /// a small non-zero fallback for ids outside the table (never offered by the picker).
    uint8_t getMoveBasePP(uint16_t moveId);
}

#endif  // NAMES_MOVE_INFO_H
