/**
 * MoveInfo.h - Base PP of a move, PER GAME, by move id.
 *
 * Auto-generated by tools/gen_moveinfo.py from PKHeX's MoveInfo3/7b/8/8a/9/9a PP arrays.
 * DO NOT EDIT BY HAND -- rerun the generator instead.
 *
 * Used to set a move's PP when it is created or picked in the editor; the entity's
 * setMove() does not set PP on its own, so without this the game reads 0 PP.
 *
 * Base PP is per-generation data, not a constant of the move. Giga Drain has 5 PP in
 * FireRed/LeafGreen and 10 from Gen 4 on; Recover is 20 / 10 / 5 across Gen 3 / 8 / 9;
 * Legends: Arceus re-tuned 92 moves. Always pass the group the entity actually lives in
 * -- Pokemon::getGameGroup() -- never a default.
 */
#ifndef NAMES_MOVE_INFO_H
#define NAMES_MOVE_INFO_H

#include <cstdint>

#include "Enums/GameVersion.h"

namespace Names {
    /// Base PP (with 0 PP-Ups) of a move as `group` defines it. Returns 0 for the empty
    /// slot (id 0). An id outside that game's table is never offered by the picker (it is
    /// filtered by isMovePresent, whose range comes from this same table); it returns a
    /// small non-zero value rather than 0, because 0 PP is a real unusable-move state.
    uint8_t getMoveBasePP(uint16_t moveId, Enums::GameVersion group);

    /// Max PP of a move with `ppUps` PP-Ups applied, as `group` defines it.
    /// PKHeX PKM.GetMovePP: basePP * (5 + ppUps) / 5. Returns 0 for the empty slot.
    uint8_t getMoveMaxPP(uint16_t moveId, uint8_t ppUps, Enums::GameVersion group);
}

#endif  // NAMES_MOVE_INFO_H
