/**
 * GENERATED by tools/gen_dexformtables.py.
 */
#include "Pokemon/DexTable6ORAS.h"

#include <cstddef>

namespace Pokemon
{
    namespace
    {
        // { species, first form bit, dex form count }, sorted by species.
        constexpr uint16_t FORM_BITS[][3] = {
        {   15,  198,  2 },         {   18,  200,  2 },         {   25,  189,  7 },         {   80,  202,  2 },
        {  208,  204,  2 },         {  254,  206,  2 },         {  260,  208,  2 },         {  302,  210,  2 },
        {  319,  212,  2 },         {  323,  214,  2 },         {  334,  216,  2 },         {  362,  218,  2 },
        {  373,  220,  2 },         {  376,  222,  2 },         {  382,  234,  2 },         {  383,  236,  2 },
        {  384,  224,  2 },         {  428,  226,  2 },         {  475,  228,  2 },         {  493,  238, 18 },
        {  531,  230,  2 },         {  649,  256,  5 },         {  676,  261,  1 },         {  719,  232,  2 },
        {  720,  196,  2 }, 
        };
        constexpr size_t FORM_BIT_COUNT = sizeof(FORM_BITS) / sizeof(FORM_BITS[0]);
    }

    int getDexFormBitIndex6ORAS(uint16_t species) noexcept
    {
        for (size_t rowIndex = 0; rowIndex < FORM_BIT_COUNT; ++rowIndex)
        {
            if (FORM_BITS[rowIndex][0] == species)
            {
                return static_cast<int>(FORM_BITS[rowIndex][1]);
            }
        }
        return -1;
    }

    uint8_t getDexFormCount6ORAS(uint16_t species) noexcept
    {
        for (size_t rowIndex = 0; rowIndex < FORM_BIT_COUNT; ++rowIndex)
        {
            if (FORM_BITS[rowIndex][0] == species)
            {
                return static_cast<uint8_t>(FORM_BITS[rowIndex][2]);
            }
        }
        return 0;
    }
}
