/**
 * GENERATED by tools/gen_dexformtables.py.
 */
#include "Pokemon/DexTable6XY.h"

#include <cstddef>

namespace Pokemon
{
    namespace
    {
        // { species, first form bit, dex form count }, sorted by species.
        constexpr uint16_t FORM_BITS[][3] = {
        {    3,  131,  2 },         {    6,  133,  3 },         {    9,  136,  2 },         {   65,  138,  2 },
        {   94,  140,  2 },         {  115,  142,  2 },         {  127,  144,  2 },         {  130,  146,  2 },
        {  142,  148,  2 },         {  150,  150,  3 },         {  181,  153,  2 },         {  212,  155,  2 },
        {  214,  157,  2 },         {  229,  159,  2 },         {  248,  161,  2 },         {  257,  163,  2 },
        {  282,  165,  2 },         {  303,  167,  2 },         {  306,  169,  2 },         {  308,  171,  2 },
        {  310,  173,  2 },         {  354,  175,  2 },         {  359,  177,  2 },         {  380,  179,  2 },
        {  381,  181,  2 },         {  445,  183,  2 },         {  448,  185,  2 },         {  460,  187,  2 },
        {  666,   83, 20 },         {  669,  103,  5 },         {  670,  108,  6 },         {  671,  114,  5 },
        {  681,  127,  2 },         {  710,  119,  4 },         {  711,  123,  4 },         {  716,  129,  2 },

        };
        constexpr size_t FORM_BIT_COUNT = sizeof(FORM_BITS) / sizeof(FORM_BITS[0]);
    }

    int getDexFormBitIndex6XY(uint16_t species) noexcept
    {
        for (size_t rowIndex = 0; rowIndex < FORM_BIT_COUNT; ++rowIndex)
        {
            if (FORM_BITS[rowIndex][0] == species)
            {
                return static_cast<int>(FORM_BITS[rowIndex][1]);
            }
        }
        return -1;
    }

    uint8_t getDexFormCount6XY(uint16_t species) noexcept
    {
        for (size_t rowIndex = 0; rowIndex < FORM_BIT_COUNT; ++rowIndex)
        {
            if (FORM_BITS[rowIndex][0] == species)
            {
                return static_cast<uint8_t>(FORM_BITS[rowIndex][2]);
            }
        }
        return 0;
    }
}
