/**
 * GENERATED by tools/gen_dexformtables.py.
 */
#include "Pokemon/DexTable7LGPE.h"

#include <cstddef>

namespace Pokemon
{
    namespace
    {
        // { species, first form bit, dex form count }, sorted by species.
        constexpr uint16_t FORM_BITS[][3] = {
        {    3,    0,  2 },         {    6,    1,  3 },         {    9,    3,  2 },         {   15,    4,  2 },
        {   18,    5,  2 },         {   19,    6,  2 },         {   20,    7,  3 },         {   25,    9,  9 },
        {   26,   17,  2 },         {   27,   18,  2 },         {   28,   19,  2 },         {   37,   20,  2 },
        {   38,   21,  2 },         {   50,   22,  2 },         {   51,   23,  2 },         {   52,   24,  2 },
        {   53,   25,  2 },         {   65,   26,  2 },         {   74,   27,  2 },         {   75,   28,  2 },
        {   76,   29,  2 },         {   80,   30,  2 },         {   88,   31,  2 },         {   89,   32,  2 },
        {   94,   33,  2 },         {  103,   34,  2 },         {  105,   35,  3 },         {  115,   37,  2 },
        {  127,   38,  2 },         {  130,   39,  2 },         {  142,   40,  2 },         {  150,   41,  3 },

        };
        constexpr size_t FORM_BIT_COUNT = sizeof(FORM_BITS) / sizeof(FORM_BITS[0]);
    }

    int getDexFormBitIndex7LGPE(uint16_t species) noexcept
    {
        for (size_t rowIndex = 0; rowIndex < FORM_BIT_COUNT; ++rowIndex)
        {
            if (FORM_BITS[rowIndex][0] == species)
            {
                return static_cast<int>(FORM_BITS[rowIndex][1]);
            }
        }
        return -1;
    }

    uint8_t getDexFormCount7LGPE(uint16_t species) noexcept
    {
        for (size_t rowIndex = 0; rowIndex < FORM_BIT_COUNT; ++rowIndex)
        {
            if (FORM_BITS[rowIndex][0] == species)
            {
                return static_cast<uint8_t>(FORM_BITS[rowIndex][2]);
            }
        }
        return 0;
    }

    namespace
    {
        // The (species, form) pairs Let's Go's Pokedex has an entry for, beyond plain form 0.
        // PKHeX Zukan7b.SizeDexInfoTable, in order -- the index into this list IS the entry offset.
        constexpr uint16_t FORM_ENTRIES[][2] = {
        {   3, 1 },         {   6, 1 },         {   6, 2 },         {   9, 1 },         {  15, 1 },         {  18, 1 },
        {  19, 1 },         {  20, 1 },         {  26, 1 },         {  27, 1 },         {  28, 1 },         {  37, 1 },
        {  38, 1 },         {  50, 1 },         {  51, 1 },         {  52, 1 },         {  53, 1 },         {  65, 1 },
        {  74, 1 },         {  75, 1 },         {  76, 1 },         {  80, 1 },         {  88, 1 },         {  89, 1 },
        {  94, 1 },         { 103, 1 },         { 105, 1 },         { 115, 1 },         { 127, 1 },         { 130, 1 },
        { 142, 1 },         { 150, 1 },         { 150, 2 }, 
        };
        constexpr int FORM_ENTRY_COUNT = static_cast<int>(sizeof(FORM_ENTRIES) / sizeof(FORM_ENTRIES[0]));
        constexpr int FORM_ENTRY_BASE = 153; // 0-150 Kanto, 151 Meltan, 152 Melmetal
    }

    int getDexEntryIndex7LGPE(uint16_t species, uint8_t form) noexcept
    {
        if (form == 0)
        {
            if (species >= 1 && species <= 151)
            {
                return static_cast<int>(species) - 1;
            }
            if (species == 808)
            {
                return 151;
            }
            if (species == 809)
            {
                return 152;
            }
            return -1;
        }
        for (int entryIndex = 0; entryIndex < FORM_ENTRY_COUNT; ++entryIndex)
        {
            if (FORM_ENTRIES[entryIndex][0] == species && FORM_ENTRIES[entryIndex][1] == form)
            {
                return FORM_ENTRY_BASE + entryIndex;
            }
        }
        return -1;
    }
}
