/**
 * GENERATED by tools/gen_gen1.py from PKHeX. Do not hand-edit.
 *
 * See Gen1Tables.h for why Gen 1 does not share the modern tables.
 */

#include "Pokemon/Gen1Tables.h"

namespace Pokemon {

namespace {

    // Gen 1 internal index -> National Dex. 0 marks an unused slot (MissingNo.).
    constexpr uint8_t INTERNAL_TO_NATIONAL[] = {
       0, 112, 115,  32,  35,  21, 100,  34,  80,   2, 103, 108, 102,  88,  94,  29,
      31, 104, 111, 131,  59, 151, 130,  90,  72,  92, 123, 120,   9, 127, 114,   0,
       0,  58,  95,  22,  16,  79,  64,  75, 113,  67, 122, 106, 107,  24,  47,  54,
      96,  76,   0, 126,   0, 125,  82, 109,   0,  56,  86,  50, 128,   0,   0,   0,
      83,  48, 149,   0,   0,   0,  84,  60, 124, 146, 144, 145, 132,  52,  98,   0,
       0,   0,  37,  38,  25,  26,   0,   0, 147, 148, 140, 141, 116, 117,   0,   0,
      27,  28, 138, 139,  39,  40, 133, 136, 135, 134,  66,  41,  23,  46,  61,  62,
      13,  14,  15,   0,  85,  57,  51,  49,  87,   0,   0,  10,  11,  12,  68,   0,
      55,  97,  42, 150, 143, 129,   0,   0,  89,   0,  99,  91,   0, 101,  36, 110,
      53, 105,   0,  93,  63,  65,  17,  18, 121,   1,   3,  73,   0, 118, 119,   0,
       0,   0,   0,  77,  78,  19,  20,  33,  30,  74, 137, 142,   0,  81,   0,   0,
       4,   7,   5,   8,   6,   0,   0,   0,   0,  43,  44,  45,  69,  70,  71,   0,
       0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
       0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
       0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
       0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    };

    // National Dex -> Gen 1 internal index. 0 marks a species Gen 1 does not have.
    constexpr uint8_t NATIONAL_TO_INTERNAL[] = {
    0x00,0x99,0x09,0x9A,0xB0,0xB2,0xB4,0xB1,0xB3,0x1C,0x7B,0x7C,0x7D,0x70,0x71,0x72,
    0x24,0x96,0x97,0xA5,0xA6,0x05,0x23,0x6C,0x2D,0x54,0x55,0x60,0x61,0x0F,0xA8,0x10,
    0x03,0xA7,0x07,0x04,0x8E,0x52,0x53,0x64,0x65,0x6B,0x82,0xB9,0xBA,0xBB,0x6D,0x2E,
    0x41,0x77,0x3B,0x76,0x4D,0x90,0x2F,0x80,0x39,0x75,0x21,0x14,0x47,0x6E,0x6F,0x94,
    0x26,0x95,0x6A,0x29,0x7E,0xBC,0xBD,0xBE,0x18,0x9B,0xA9,0x27,0x31,0xA3,0xA4,0x25,
    0x08,0xAD,0x36,0x40,0x46,0x74,0x3A,0x78,0x0D,0x88,0x17,0x8B,0x19,0x93,0x0E,0x22,
    0x30,0x81,0x4E,0x8A,0x06,0x8D,0x0C,0x0A,0x11,0x91,0x2B,0x2C,0x0B,0x37,0x8F,0x12,
    0x01,0x28,0x1E,0x02,0x5C,0x5D,0x9D,0x9E,0x1B,0x98,0x2A,0x1A,0x48,0x35,0x33,0x1D,
    0x3C,0x85,0x16,0x13,0x4C,0x66,0x69,0x68,0x67,0xAA,0x62,0x63,0x5A,0x5B,0xAB,0x84,
    0x4A,0x4B,0x49,0x58,0x59,0x42,0x83,0x15,
    };

    // Base PP per move id, 0..165. PKHeX MoveInfo1.PP.
    constexpr uint8_t MOVE_PP[] = {
      0, 35, 25, 10, 15, 20, 20, 15, 15, 15, 35, 30,  5, 10, 30, 30, 35, 35, 20, 15,
     20, 20, 10, 20, 30,  5, 25, 15, 15, 15, 25, 20,  5, 35, 15, 20, 20, 20, 15, 30,
     35, 20, 20, 30, 25, 40, 20, 15, 20, 20, 20, 30, 25, 15, 30, 25,  5, 15, 10,  5,
     20, 20, 20,  5, 35, 20, 25, 20, 20, 20, 15, 20, 10, 10, 40, 25, 10, 35, 30, 15,
     20, 40, 10, 15, 30, 15, 20, 10, 15, 10,  5, 10, 10, 25, 10, 20, 40, 30, 30, 20,
     20, 15, 10, 40, 15, 20, 30, 20, 20, 10, 40, 40, 30, 30, 30, 20, 30, 10, 10, 20,
      5, 10, 30, 20, 20, 20,  5, 15, 10, 20, 15, 15, 35, 20, 15, 10, 20, 30, 15, 40,
     20, 15, 10,  5, 10, 30, 10, 15, 20, 15, 40, 40, 10,  5, 15, 10, 10, 10, 15, 30,
     30, 10, 10, 20, 10, 10,
    };

    // Gen 1 item names by Gen 1 item id, 0..254. PKHeX text_ItemsG1_en.txt.
    // Empty entries are ids the games never use; the accessor reports them as "???".
    constexpr const char* ITEM_NAMES[] = {
        "(None)",                  //   0
        "Master Ball",             //   1
        "Ultra Ball",              //   2
        "Great Ball",              //   3
        "Poké Ball",               //   4
        "Town Map",                //   5
        "Bicycle",                 //   6
        "????? (7)",               //   7
        "Safari Ball",             //   8
        "Pokédex",                 //   9
        "Moon Stone",              //  10
        "Antidote",                //  11
        "Burn Heal",               //  12
        "Ice Heal",                //  13
        "Awakening",               //  14
        "Parlyz Heal",             //  15
        "Full Restore",            //  16
        "Max Potion",              //  17
        "Hyper Potion",            //  18
        "Super Potion",            //  19
        "Potion",                  //  20
        "BoulderBadge",            //  21
        "CascadeBadge",            //  22
        "ThunderBadge",            //  23
        "RainbowBadge",            //  24
        "SoulBadge",               //  25
        "MarshBadge",              //  26
        "VolcanoBadge",            //  27
        "EarthBadge",              //  28
        "Escape Rope",             //  29
        "Repel",                   //  30
        "Old Amber",               //  31
        "Fire Stone",              //  32
        "Thunder Stone",           //  33
        "Water Stone",             //  34
        "HP Up",                   //  35
        "Protein",                 //  36
        "Iron",                    //  37
        "Carbos",                  //  38
        "Calcium",                 //  39
        "Rare Candy",              //  40
        "Dome Fossil",             //  41
        "Helix Fossil",            //  42
        "Secret Key",              //  43
        "????? (44)",              //  44
        "Bike Voucher",            //  45
        "X Accuracy",              //  46
        "Leaf Stone",              //  47
        "Card Key",                //  48
        "Nugget",                  //  49
        "PP Up (Unused)",          //  50
        "Poké Doll",               //  51
        "Full Heal",               //  52
        "Revive",                  //  53
        "Max Revive",              //  54
        "Guard Spec.",             //  55
        "Super Repel",             //  56
        "Max Repel",               //  57
        "Dire Hit",                //  58
        "Coin",                    //  59
        "Fresh Water",             //  60
        "Soda Pop",                //  61
        "Lemonade",                //  62
        "S.S. Ticket",             //  63
        "Gold Teeth",              //  64
        "X Attack",                //  65
        "X Defend",                //  66
        "X Speed",                 //  67
        "X Special",               //  68
        "Coin Case",               //  69
        "Oak's Parcel",            //  70
        "Itemfinder",              //  71
        "Silph Scope",             //  72
        "Poké Flute",              //  73
        "Lift Key",                //  74
        "Exp. All",                //  75
        "Old Rod",                 //  76
        "Good Rod",                //  77
        "Super Rod",               //  78
        "PP Up",                   //  79
        "Ether",                   //  80
        "Max Ether",               //  81
        "Elixir",                  //  82
        "Max Elixir",              //  83
        "",                        //  84
        "",                        //  85
        "",                        //  86
        "",                        //  87
        "",                        //  88
        "",                        //  89
        "",                        //  90
        "",                        //  91
        "",                        //  92
        "",                        //  93
        "",                        //  94
        "",                        //  95
        "",                        //  96
        "",                        //  97
        "",                        //  98
        "",                        //  99
        "",                        // 100
        "",                        // 101
        "",                        // 102
        "",                        // 103
        "",                        // 104
        "",                        // 105
        "",                        // 106
        "",                        // 107
        "",                        // 108
        "",                        // 109
        "",                        // 110
        "",                        // 111
        "",                        // 112
        "",                        // 113
        "",                        // 114
        "",                        // 115
        "",                        // 116
        "",                        // 117
        "",                        // 118
        "",                        // 119
        "",                        // 120
        "",                        // 121
        "",                        // 122
        "",                        // 123
        "",                        // 124
        "",                        // 125
        "",                        // 126
        "",                        // 127
        "",                        // 128
        "",                        // 129
        "",                        // 130
        "",                        // 131
        "",                        // 132
        "",                        // 133
        "",                        // 134
        "",                        // 135
        "",                        // 136
        "",                        // 137
        "",                        // 138
        "",                        // 139
        "",                        // 140
        "",                        // 141
        "",                        // 142
        "",                        // 143
        "",                        // 144
        "",                        // 145
        "",                        // 146
        "",                        // 147
        "",                        // 148
        "",                        // 149
        "",                        // 150
        "",                        // 151
        "",                        // 152
        "",                        // 153
        "",                        // 154
        "",                        // 155
        "",                        // 156
        "",                        // 157
        "",                        // 158
        "",                        // 159
        "",                        // 160
        "",                        // 161
        "",                        // 162
        "",                        // 163
        "",                        // 164
        "",                        // 165
        "",                        // 166
        "",                        // 167
        "",                        // 168
        "",                        // 169
        "",                        // 170
        "",                        // 171
        "",                        // 172
        "",                        // 173
        "",                        // 174
        "",                        // 175
        "",                        // 176
        "",                        // 177
        "",                        // 178
        "",                        // 179
        "",                        // 180
        "",                        // 181
        "",                        // 182
        "",                        // 183
        "",                        // 184
        "",                        // 185
        "",                        // 186
        "",                        // 187
        "",                        // 188
        "",                        // 189
        "",                        // 190
        "",                        // 191
        "",                        // 192
        "",                        // 193
        "",                        // 194
        "",                        // 195
        "HM01",                    // 196
        "HM02",                    // 197
        "HM03",                    // 198
        "HM04",                    // 199
        "HM05",                    // 200
        "TM01",                    // 201
        "TM02",                    // 202
        "TM03",                    // 203
        "TM04",                    // 204
        "TM05",                    // 205
        "TM06",                    // 206
        "TM07",                    // 207
        "TM08",                    // 208
        "TM09",                    // 209
        "TM10",                    // 210
        "TM11",                    // 211
        "TM12",                    // 212
        "TM13",                    // 213
        "TM14",                    // 214
        "TM15",                    // 215
        "TM16",                    // 216
        "TM17",                    // 217
        "TM18",                    // 218
        "TM19",                    // 219
        "TM20",                    // 220
        "TM21",                    // 221
        "TM22",                    // 222
        "TM23",                    // 223
        "TM24",                    // 224
        "TM25",                    // 225
        "TM26",                    // 226
        "TM27",                    // 227
        "TM28",                    // 228
        "TM29",                    // 229
        "TM30",                    // 230
        "TM31",                    // 231
        "TM32",                    // 232
        "TM33",                    // 233
        "TM34",                    // 234
        "TM35",                    // 235
        "TM36",                    // 236
        "TM37",                    // 237
        "TM38",                    // 238
        "TM39",                    // 239
        "TM40",                    // 240
        "TM41",                    // 241
        "TM42",                    // 242
        "TM43",                    // 243
        "TM44",                    // 244
        "TM45",                    // 245
        "TM46",                    // 246
        "TM47",                    // 247
        "TM48",                    // 248
        "TM49",                    // 249
        "TM50",                    // 250
        "TM51",                    // 251
        "TM52",                    // 252
        "TM53",                    // 253
        "TM54",                    // 254
    };
    static_assert(sizeof(ITEM_NAMES) / sizeof(ITEM_NAMES[0]) == 255,
                  "Gen 1 item name table must cover every id 0..254");

    // Bit set = the id may legitimately sit in a Gen 1 bag (PKHeX ItemStorage1.General).
    constexpr uint8_t ITEM_LEGAL[] = {
    0x7F,0xFC,0x1F,0xE0,0xFF,0xEF,0xFB,0xF7,0xFF,0xFF,0x0F,0x00,
    0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
    0xF0,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0x07,
    };

}

uint16_t g1ToNational(uint8_t internalIndex) noexcept {
    if (internalIndex >= sizeof(INTERNAL_TO_NATIONAL)) return 0;
    return INTERNAL_TO_NATIONAL[internalIndex];
}

uint8_t nationalToG1(uint16_t species) noexcept {
    if (species >= sizeof(NATIONAL_TO_INTERNAL)) return 0;
    return NATIONAL_TO_INTERNAL[species];
}

uint8_t g1TypeToPKSE(uint8_t romType) noexcept {
    switch (romType) {
        case  0: return  0;   // Normal
        case  1: return  1;   // Fighting
        case  2: return  2;   // Flying
        case  3: return  3;   // Poison
        case  4: return  4;   // Ground
        case  5: return  5;   // Rock
        case  7: return  6;   // Bug
        case  8: return  7;   // Ghost
        case 20: return  9;   // Fire
        case 21: return 10;   // Water
        case 22: return 11;   // Grass
        case 23: return 12;   // Electric
        case 24: return 13;   // Psychic
        case 25: return 14;   // Ice
        case 26: return 15;   // Dragon
        default: return 255;   // TYPE_NONE -- includes Gen 1's unused "Bird" type (6)
    }
}

uint8_t pkseTypeToG1(uint8_t pkseType) noexcept {
    switch (pkseType) {
        case  0: return  0;   // Normal
        case  1: return  1;   // Fighting
        case  2: return  2;   // Flying
        case  3: return  3;   // Poison
        case  4: return  4;   // Ground
        case  5: return  5;   // Rock
        case  6: return  7;   // Bug
        case  7: return  8;   // Ghost
        case  9: return 20;   // Fire
        case 10: return 21;   // Water
        case 11: return 22;   // Grass
        case 12: return 23;   // Electric
        case 13: return 24;   // Psychic
        case 14: return 25;   // Ice
        case 15: return 26;   // Dragon
        default: return 0;   // Dark / Steel / Fairy do not exist in Gen 1
    }
}

const char* getItemNameGen1(uint8_t itemId) noexcept {
    const char* n = ITEM_NAMES[itemId];
    return n[0] ? n : "???";
}

bool isItemLegalGen1(uint8_t itemId) noexcept {
    return (ITEM_LEGAL[itemId >> 3] >> (itemId & 7)) & 1;
}

uint8_t getMovePPGen1(uint16_t move) noexcept {
    if (move == 0 || move >= sizeof(MOVE_PP)) return 0;
    return MOVE_PP[move];
}

uint8_t getMovePPGen1WithUps(uint16_t move, uint8_t ppUpCount) noexcept {
    const uint8_t base = getMovePPGen1(move);
    if (base == 0) return 0;
    if (ppUpCount > 3) ppUpCount = 3;
    // Gen 1/2 rule: each PP Up adds min(7, base/5). The modern formula differs.
    const uint8_t perUp = static_cast<uint8_t>(base / 5 > 7 ? 7 : base / 5);
    return static_cast<uint8_t>(base + perUp * ppUpCount);
}

}
