/**
 * GENERATED by tools/gen_personaltables.py.
 */
#include "Pokemon/Gen2Tables.h"

#include <cstddef>

namespace Pokemon
{
    namespace
    {
        const char *const ITEM_NAMES_G2[] = {
            "(None)",                  // 0
            "Master Ball",             // 1
            "Ultra Ball",              // 2
            "BrightPowder",            // 3
            "Great Ball",              // 4
            "Poké Ball",               // 5
            "Teru-sama (0)",           // 6
            "Bicycle",                 // 7
            "Moon Stone",              // 8
            "Antidote",                // 9
            "Burn Heal",               // 10
            "Ice Heal",                // 11
            "Awakening",               // 12
            "Parlyz Heal",             // 13
            "Full Restore",            // 14
            "Max Potion",              // 15
            "Hyper Potion",            // 16
            "Super Potion",            // 17
            "Potion",                  // 18
            "Escape Rope",             // 19
            "Repel",                   // 20
            "Max Elixer",              // 21
            "Fire Stone",              // 22
            "Thunder Stone",           // 23
            "Water Stone",             // 24
            "Teru-sama (1)",           // 25
            "HP Up",                   // 26
            "Protein",                 // 27
            "Iron",                    // 28
            "Carbos",                  // 29
            "Lucky Punch",             // 30
            "Calcium",                 // 31
            "Rare Candy",              // 32
            "X Accuracy",              // 33
            "Leaf Stone",              // 34
            "Metal Powder",            // 35
            "Nugget",                  // 36
            "Poké Doll",               // 37
            "Full Heal",               // 38
            "Revive",                  // 39
            "Max Revive",              // 40
            "Guard Spec.",             // 41
            "Super Repel",             // 42
            "Max Repel",               // 43
            "Dire Hit",                // 44
            "Teru-sama (2)",           // 45
            "Fresh Water",             // 46
            "Soda Pop",                // 47
            "Lemonade",                // 48
            "X Attack",                // 49
            "Teru-sama (3)",           // 50
            "X Defend",                // 51
            "X Speed",                 // 52
            "X Special",               // 53
            "Coin Case",               // 54
            "Itemfinder",              // 55
            "Teru-sama (4)",           // 56
            "Exp Share",               // 57
            "Old Rod",                 // 58
            "Good Rod",                // 59
            "Silver Leaf",             // 60
            "Super Rod",               // 61
            "PP Up",                   // 62
            "Ether",                   // 63
            "Max Ether",               // 64
            "Elixer",                  // 65
            "Red Scale",               // 66
            "SecretPotion",            // 67
            "S.S. Ticket",             // 68
            "Mystery Egg",             // 69
            "Clear Bell*",             // 70
            "Silver Wing",             // 71
            "Moomoo Milk",             // 72
            "Quick Claw",              // 73
            "PSNCureBerry",            // 74
            "Gold Leaf",               // 75
            "Soft Sand",               // 76
            "Sharp Beak",              // 77
            "PRZCureBerry",            // 78
            "Burnt Berry",             // 79
            "Ice Berry",               // 80
            "Poison Barb",             // 81
            "King's Rock",             // 82
            "Bitter Berry",            // 83
            "Mint Berry",              // 84
            "Red Apricorn",            // 85
            "TinyMushroom",            // 86
            "Big Mushroom",            // 87
            "SilverPowder",            // 88
            "Blu Apricorn",            // 89
            "Teru-sama (5)",           // 90
            "Amulet Coin",             // 91
            "Ylw Apricorn",            // 92
            "Grn Apricorn",            // 93
            "Cleanse Tag",             // 94
            "Mystic Water",            // 95
            "TwistedSpoon",            // 96
            "Wht Apricorn",            // 97
            "Black Belt",              // 98
            "Blk Apricorn",            // 99
            "Teru-sama (6)",           // 100
            "Pnk Apricorn",            // 101
            "BlackGlasses",            // 102
            "SlowpokeTail",            // 103
            "Pink Bow",                // 104
            "Stick",                   // 105
            "Smoke Ball",              // 106
            "NeverMeltIce",            // 107
            "Magnet",                  // 108
            "MiracleBerry",            // 109
            "Pearl",                   // 110
            "Big Pearl",               // 111
            "Everstone",               // 112
            "Spell Tag",               // 113
            "RageCandyBar",            // 114
            "GS Ball*",                // 115
            "Blue Card*",              // 116
            "Miracle Seed",            // 117
            "Thick Club",              // 118
            "Focus Band",              // 119
            "Teru-sama (7)",           // 120
            "EnergyPowder",            // 121
            "Energy Root",             // 122
            "Heal Powder",             // 123
            "Revival Herb",            // 124
            "Hard Stone",              // 125
            "Lucky Egg",               // 126
            "Card Key",                // 127
            "Machine Part",            // 128
            "Egg Ticket*",             // 129
            "Lost Item",               // 130
            "Stardust",                // 131
            "Star Piece",              // 132
            "Basement Key",            // 133
            "Pass",                    // 134
            "Teru-sama (8)",           // 135
            "Teru-sama (9)",           // 136
            "Teru-sama (10)",          // 137
            "Charcoal",                // 138
            "Berry Juice",             // 139
            "Scope Lens",              // 140
            "Teru-sama (11)",          // 141
            "Teru-sama (12)",          // 142
            "Metal Coat",              // 143
            "Dragon Fang",             // 144
            "Teru-sama (13)",          // 145
            "Leftovers",               // 146
            "Teru-sama (14)",          // 147
            "Teru-sama (15)",          // 148
            "Teru-sama (16)",          // 149
            "MysteryBerry",            // 150
            "Dragon Scale",            // 151
            "Berserk Gene",            // 152
            "Teru-sama (17)",          // 153
            "Teru-sama (18)",          // 154
            "Teru-sama (19)",          // 155
            "Sacred Ash",              // 156
            "Heavy Ball",              // 157
            "Flower Mail",             // 158
            "Level Ball",              // 159
            "Lure Ball",               // 160
            "Fast Ball",               // 161
            "Teru-sama (20)",          // 162
            "Light Ball",              // 163
            "Friend Ball",             // 164
            "Moon Ball",               // 165
            "Love Ball",               // 166
            "Normal Box",              // 167
            "Gorgeous Box",            // 168
            "Sun Stone",               // 169
            "Polkadot Bow",            // 170
            "Teru-sama (21)",          // 171
            "Up-Grade",                // 172
            "Berry",                   // 173
            "Gold Berry",              // 174
            "SquirtBottle",            // 175
            "Teru-sama (22)",          // 176
            "Park Ball",               // 177
            "Rainbow Wing",            // 178
            "Teru-sama (23)",          // 179
            "Brick Piece",             // 180
            "Surf Mail",               // 181
            "Litebluemail",            // 182
            "Portraitmail",            // 183
            "Lovely Mail",             // 184
            "Eon Mail",                // 185
            "Morph Mail",              // 186
            "Bluesky Mail",            // 187
            "Music Mail",              // 188
            "Mirage Mail",             // 189
            "Teru-sama (24)",          // 190
            "TM01",                    // 191
            "TM02",                    // 192
            "TM03",                    // 193
            "TM04",                    // 194
            "TM04 (Unused)",           // 195
            "TM05",                    // 196
            "TM06",                    // 197
            "TM07",                    // 198
            "TM08",                    // 199
            "TM09",                    // 200
            "TM10",                    // 201
            "TM11",                    // 202
            "TM12",                    // 203
            "TM13",                    // 204
            "TM14",                    // 205
            "TM15",                    // 206
            "TM16",                    // 207
            "TM17",                    // 208
            "TM18",                    // 209
            "TM19",                    // 210
            "TM20",                    // 211
            "TM21",                    // 212
            "TM22",                    // 213
            "TM23",                    // 214
            "TM24",                    // 215
            "TM25",                    // 216
            "TM26",                    // 217
            "TM27",                    // 218
            "TM28",                    // 219
            "TM28 (Unused)",           // 220
            "TM29",                    // 221
            "TM30",                    // 222
            "TM31",                    // 223
            "TM32",                    // 224
            "TM33",                    // 225
            "TM34",                    // 226
            "TM35",                    // 227
            "TM36",                    // 228
            "TM37",                    // 229
            "TM38",                    // 230
            "TM39",                    // 231
            "TM40",                    // 232
            "TM41",                    // 233
            "TM42",                    // 234
            "TM43",                    // 235
            "TM44",                    // 236
            "TM45",                    // 237
            "TM46",                    // 238
            "TM47",                    // 239
            "TM48",                    // 240
            "TM49",                    // 241
            "TM50",                    // 242
            "HM01",                    // 243
            "HM02",                    // 244
            "HM03",                    // 245
            "HM04",                    // 246
            "HM05",                    // 247
            "HM06",                    // 248
            "HM07",                    // 249
            "HM08 (Unused)",           // 250
            "HM09 (Unused)",           // 251
            "HM10 (Unused)",           // 252
            "HM11 (Unused)",           // 253
            "HM12 (Unused)",           // 254
            "???",                     // 255
        };

        const uint8_t ITEM_LEGAL_G2[] = {
            1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
            18, 19, 20, 21, 22, 23, 24, 26, 27, 28, 29, 30, 31, 32, 33, 34,
            35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 46, 47, 48, 49, 51, 52,
            53, 54, 55, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
            70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
            86, 87, 88, 89, 91, 92, 93, 94, 95, 96, 97, 98, 99, 101, 102, 103,
            104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119,
            121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 138, 139,
            140, 143, 144, 146, 150, 151, 152, 156, 157, 158, 159, 160, 161, 163, 164, 165,
            166, 167, 168, 169, 170, 172, 173, 174, 175, 178, 180, 181, 182, 183, 184, 185,
            186, 187, 188, 189, 191, 192, 193, 194, 196, 197, 198, 199, 200, 201, 202, 203,
            204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219,
            221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236,
            237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249,
        };
    }

    const char *getItemNameGen2(uint8_t itemId) noexcept
    {
        const char *name = ITEM_NAMES_G2[itemId];
        return (name[0] != '\0') ? name : "???";
    }

    bool isItemLegalGen2(uint8_t itemId) noexcept
    {
        // Sorted, so a binary search; the list is the union of every Gen 2 pouch.
        size_t low = 0, high = sizeof(ITEM_LEGAL_G2) / sizeof(ITEM_LEGAL_G2[0]);
        while (low < high)
        {
            const size_t mid = (low + high) / 2;
            if (ITEM_LEGAL_G2[mid] == itemId)
            {
                return true;
            }
            if (ITEM_LEGAL_G2[mid] < itemId)
            {
                low = mid + 1;
            }
            else
            {
                high = mid;
            }
        }
        return false;
    }
}
