/**
 * Auto-generated by tools/gen_encounters.py from PKHeX's wild-slot binaries and
 * static/gift/trade/raid tables. DO NOT EDIT BY HAND -- rerun the generator instead.
 *
 * One flat row per template. Wild and raid rows are MERGED per
 * (species, form, location, constraints): the level span is the union of the
 * contributing slots and the guaranteed-31 count their minimum, which is permissive
 * by construction -- merging can widen what the table accepts, never narrow it.
 * Static / gift / trade rows are never merged; each is a distinct template whose
 * fixed data has to stay exact.
 *
 * The ability slot is deliberately absent: Ability Capsule and Ability Patch let a
 * legitimate Pokemon hold a slot its encounter never offered, so the column would
 * only enable a check that false-flags real saves. Layer 2 already verifies the
 * ability against the species.
 */
#ifndef LEGALITY_ENCOUNTER_TABLE_H
#define LEGALITY_ENCOUNTER_TABLE_H

#include <cstdint>

#include "Enums/GameVersion.h"

namespace Legality {

    /// How the Pokemon was obtained. Reported verbatim, so keep the wording usable.
    enum EncounterKind : uint8_t {
        ENCOUNTER_KIND_WILD   = 0,
        ENCOUNTER_KIND_STATIC = 1,
        ENCOUNTER_KIND_GIFT   = 2,
        ENCOUNTER_KIND_TRADE  = 3,
        ENCOUNTER_KIND_RAID   = 4,
        /// A Mystery Gift distribution. Kept apart from ENCOUNTER_KIND_GIFT (an in-game NPC gift)
        /// because the two answer different questions for a reader: an event says the
        /// Pokemon came from a real distribution, which is exactly what a fateful-encounter
        /// bit claims and what nothing could previously check.
        ENCOUNTER_KIND_EVENT  = 5,
    };

    /// Shiny policy of a template -- Never is a shiny LOCK, Always a forced shiny.
    enum EncounterShiny : uint8_t {
        ENCOUNTER_SHINY_RANDOM = 0,
        ENCOUNTER_SHINY_NEVER  = 1,
        ENCOUNTER_SHINY_ALWAYS = 2,
    };

    enum EncounterFlag : uint8_t {
        ENCOUNTER_FLAG_FATEFUL = 1 << 0,  // sets the fateful-encounter (event) bit
        ENCOUNTER_FLAG_ALPHA   = 1 << 1,  // Legends Alpha (PLA / Z-A)
        ENCOUNTER_FLAG_BOOST60 = 1 << 2,  // SW/SH Wild Area: post-game boosts levels to 60
        ENCOUNTER_FLAG_EGG     = 1 << 3,  // handed over as an egg
        /// The game writes met level 0 for this encounter, so the level span bounds the CURRENT level
        /// instead. Gen 2's in-game trades: Crystal records them at LinkTrade2NPC and met level 0,
        /// and the received Pokemon is at least the level the template names (EncounterTrade2).
        ENCOUNTER_FLAG_MET_LEVEL_ZERO = 1 << 4,
    };

    constexpr uint8_t ENCOUNTER_FORM_ANY   = 0xFF;  // slot randomises the form
    constexpr uint8_t ENCOUNTER_GENDER_ANY = 0xFF;
    constexpr uint8_t ENCOUNTER_NATURE_ANY = 0xFF;

    /// Locations that stand for a whole region rather than one place. Two kinds use them:
    /// SW/SH distribution raids, where the den is anonymous so any Wild Area location of the
    /// right DLC tier is legal, and ROAMERS, which are met wherever they were finally cornered
    /// rather than where their template starts them.
    constexpr uint16_t ENCOUNTER_LOCATION_SWSH_WILDAREA               = 0xFFF0;  // Galar Wild Area
    constexpr uint16_t ENCOUNTER_LOCATION_SWSH_WILDAREA_ISLE_OF_ARMOR = 0xFFF1;  // + Isle of Armor
    constexpr uint16_t ENCOUNTER_LOCATION_SWSH_WILDAREA_ALL           = 0xFFF2;  // + Crown Tundra
    constexpr uint16_t ENCOUNTER_LOCATION_ROAMER3                     = 0xFFF3;  // Hoenn routes 101-138
    constexpr uint16_t ENCOUNTER_LOCATION_ROAMER4_SINNOH              = 0xFFF4;  // Sinnoh roamer routes
    constexpr uint16_t ENCOUNTER_LOCATION_ROAMER4_JOHTO               = 0xFFF5;  // Johto roamer routes
    constexpr uint16_t ENCOUNTER_LOCATION_ROAMER4_KANTO               = 0xFFF6;  // Kanto roamer routes
    constexpr uint16_t ENCOUNTER_LOCATION_ROAMER5                     = 0xFFF7;  // Unova roamer routes
    constexpr uint16_t ENCOUNTER_LOCATION_ROAMER2                     = 0xFFF8;  // Johto roamer routes

    /// NOT a sentinel: a real Gen 3 met location, and the one where everything that reached a Gen 3
    /// cartridge from OUTSIDE it is met -- every Mystery Gift distribution, and Pokemon Colosseum's
    /// gifts (the Japanese bonus disc's Pikachu and Celebi, and Ho-Oh from Mt. Battle). PKHeX
    /// Locations.IsEventLocation3.
    constexpr uint16_t ENCOUNTER_LOCATION_EVENT3 = 255;

    struct EncounterRow {
        uint16_t species;
        uint16_t location;     // met location, in the ORIGIN game's namespace
        uint16_t eggLocation;  // 0 unless the template hands over an egg
        uint8_t  form;         // ENCOUNTER_FORM_ANY when the slot randomises it
        uint8_t  levelMin;
        uint8_t  levelMax;
        uint8_t  versions;     // one bit per game in the group, in GameVersion-name order.
                               // Two bits everywhere except Ruby/Sapphire/Emerald, which is the
                               // only group of three -- see encounterVersionBit.
        uint8_t  kind;         // EncounterKind
        uint8_t  shiny;        // EncounterShiny
        uint8_t  gender;       // 0 male, 1 female, 2 genderless, ENCOUNTER_GENDER_ANY
        uint8_t  fixedBall;    // 0 = the encounter does not fix the ball
        uint8_t  flawlessIVs;  // guaranteed count of 31 IVs
        uint8_t  nature;       // ENCOUNTER_NATURE_ANY unless the template forces one
        uint8_t  flags;        // EncounterFlag bits
    };

    /// Where a game's eggs come from and where they may hatch.
    struct EggRule {
        uint16_t eggLocation;     // nursery id stamped into the egg-location field.
                                  // 0 means the FORMAT has no such field (Gen 3 alone),
                                  // which is why an egg there has to be inferred instead.
        /// Other ids a BRED egg may legitimately carry, 0 for an unused slot. Two of them because
        /// Gen 5 has three legal values in all: the daycare above, the ordinary link trade, and
        /// the one Spin Trade writes (PKHeX Locations.IsEggLocationBred5). Everywhere else the
        /// second slot is 0.
        uint16_t eggLocationAlternates[2];
        /// Per-location version mask: one byte per met location id, holding this table's own
        /// version bits for the games whose eggs may hatch there. An egg hatches wherever the
        /// player happens to be walking, so this is a permitted SET rather than one place --
        /// PKHeX's EggHatchLocation3 through 9, normalised. Gen 2 is the single fixed case
        /// (Crystal stamps one id and Gold/Silver record nothing at all).
        /// nullptr when the game has no breeding, or when PKSE has no mask for it, which
        /// canHatchAt reads as NOT CHECKED rather than as "nowhere".
        const uint8_t* hatchLocations;
        uint16_t hatchLocationCount;
        /// Where the game itself stamps an egg it hands over -- its day care's own map
        /// (PKHeX Locations.HatchLocation*). Always inside the mask above; it is the canonical
        /// answer of the set, and what a rebuilt Gen 3 record is given.
        uint16_t hatchLocation;
        /// One further permitted hatch location sitting too far up the id space for the mask to
        /// reach, 0 when there is none. Poke Pelago (30016) is the only one: EggHatchLocation7
        /// accepts it alongside its byte table, and a mask stretching to 30016 would be thirty
        /// kilobytes of zeros.
        uint16_t hatchLocationExtra;
        /// MET level of a hatched egg -- 0 in Gens 3 and 4, 1 from Gen 5 on (and in Crystal).
        /// NOT the level it hatches AT, which is the next field; conflating the two made every
        /// bred Gen 3 Pokemon read as having no encounter at all.
        uint8_t  hatchLevel;
        /// The level a Pokemon IS when its egg hatches -- 5 in Gens 2 and 3, 1 from Gen 4 on
        /// (PKHeX EggStateLegality.GetEggLevel). A record below it never hatched, whatever its
        /// met data says.
        uint8_t  hatchCurrentLevel;
        uint8_t  hasBreeding;     // 0 for the games with no daycare at all
    };

    struct EncounterTable {
        const EncounterRow* rows;
        uint32_t rowCount;
        /// speciesIndex[s] .. speciesIndex[s + 1] bounds the rows for species s.
        const uint16_t* speciesIndex;
        uint16_t speciesIndexLength;
        /// Species bitset: could a Pokemon here have hatched from a daycare egg?
        /// nullptr when the game has no breeding.
        const uint8_t* breedable;
        EggRule egg;
    };

    /// Encounter data for a game or game group; nullptr when PKSE has none for it
    /// (every generation before Gen 3, Pokemon GO, and anything unrecognised).
    const EncounterTable* getEncounterTable(Enums::GameVersion versionOrGroup);

    /// Row version bit for an exact version id (0 when it names a group, not a game).
    uint8_t encounterVersionBit(Enums::GameVersion version);

    /// True when a met location satisfies a row's location, resolving the region
    /// sentinels above.
    bool encounterLocationMatches(uint16_t rowLocation, uint16_t metLocation);
}

#endif  // LEGALITY_ENCOUNTER_TABLE_H
