#!/usr/bin/env python3
"""Generate src/Names/LocationNames.cpp from PKHeX met-location text resources.

Each game group's MAIN (0x0-based) met-location list is copied verbatim from
PKHeX's `text_*_00000_zh-Hans.txt` files. A location ID indexes directly into the
table, so blank slots are preserved (as "") to keep the indexing aligned, and
PKHeX's run-of-em-dashes "no location" sentinel is emitted as "" too.

The same numeric location ID names a DIFFERENT place per generation, hence one
table per game group, dispatched on the mon's origin game-version id.

Regenerate:  python tools/gen_locations.py
Pulls the PKHeX text resources it reads from GitHub on demand
(tools/pkhex_source.py); no local PKHeX checkout required.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pkhex_source import pkhex_path  # noqa: E402
OUT = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "src", "Names", "LocationNames.cpp",
)

EMDASH = "—"

# (array name, human label, relative path, source basename)
TABLES = [
    ("GG_LOC_NAMES",   "Let's Go, Pikachu! / Eevee! (GP=42, GE=43)",       "gen7/text_gg_00000_zh-Hans.txt",    "text_gg_00000_zh-Hans.txt"),
    ("SWSH_LOC_NAMES", "Sword / Shield (SW=44, SH=45)",                    "gen8/text_swsh_00000_zh-Hans.txt",  "text_swsh_00000_zh-Hans.txt"),
    ("PLA_LOC_NAMES",  "Legends: Arceus (PLA=47)",                         "gen8a/text_la_00000_zh-Hans.txt",   "text_la_00000_zh-Hans.txt"),
    ("BDSP_LOC_NAMES", "Brilliant Diamond / Shining Pearl (BD=48, SP=49)", "gen8b/text_bdsp_00000_zh-Hans.txt", "text_bdsp_00000_zh-Hans.txt"),
    ("SV_LOC_NAMES",   "Scarlet / Violet (SL=50, VL=51)",                  "gen9/text_sv_00000_zh-Hans.txt",    "text_sv_00000_zh-Hans.txt"),
    ("ZA_LOC_NAMES",   "Legends: Z-A (ZA=52)",                             "gen9a/text_za_00000_zh-Hans.txt",   "text_za_00000_zh-Hans.txt"),
    ("G3_LOC_NAMES",   "Gen 3 R/S/E + FR/LG (SA=1, RU=2, EM=3, FR=4, LG=5)", "gen3/text_rsefrlg_00000_zh-Hans.txt", "text_rsefrlg_00000_zh-Hans.txt"),
]

# originVersion cases -> table name (see Enums::GameVersion)
DISPATCH = [
    ("42: case 43", "GG_LOC_NAMES"),
    ("44: case 45", "SWSH_LOC_NAMES"),
    ("47",          "PLA_LOC_NAMES"),
    ("48: case 49", "BDSP_LOC_NAMES"),
    ("50: case 51", "SV_LOC_NAMES"),
    ("52",          "ZA_LOC_NAMES"),
    ("1: case 2: case 3: case 4: case 5", "G3_LOC_NAMES"),  # Gen 3 versions share the R/S/E + FR/LG list
]


def load_entries(path):
    with open(path, encoding="utf-8") as fh:
        lines = fh.read().split("\n")
    # Drop exactly one trailing empty element produced by a final newline.
    if lines and lines[-1] == "":
        lines = lines[:-1]
    # A run of em dashes is PKHeX's "no location" sentinel -> emit "".
    return ["" if (l and all(c == EMDASH for c in l)) else l for l in lines]


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    p = []
    p.append('/**\n'
             ' * LocationNames.cpp - Met-location name lookup (per generation)\n'
             ' *\n'
             ' * Auto-generated by tools/gen_locations.py from PKHeX\'s met-location text\n'
             ' * resources (PKHeX.Core/Resources/text/locations/.../text_*_00000_zh-Hans.txt).\n'
             ' * Each table is the MAIN (0x0-based) met-location list for one game group;\n'
             ' * a location ID indexes directly into the table.\n'
             ' *\n'
             ' * The same numeric location ID names a DIFFERENT place in each generation,\n'
             ' * so callers must pass the mon\'s ORIGIN game-version id (see Enums::GameVersion)\n'
             ' * to select the correct table.\n'
             ' *\n'
             ' * Blank slots and PKHeX\'s em-dash "no location" sentinel are emitted as "".\n'
             ' */\n\n')
    p.append('#include "Names/LocationNames.h"\n\n')
    p.append('#include <cstddef>\n\n')
    p.append("namespace Names {\n")

    counts = {}
    for arr, label, rel, base in TABLES:
        entries = load_entries(pkhex_path("Resources/text/locations/" + rel))
        counts[arr] = len(entries)
        p.append(f"\n    // {label}\n")
        p.append(f"    // Source: PKHeX {base}  ({len(entries)} entries)\n")
        p.append(f"    static const char* const {arr}[] = {{\n")
        for i, e in enumerate(entries):
            p.append(f'        "{esc(e)}",  // {i}\n')
        p.append("    };\n")

    p.append("\n"
             "    // Returns table[id] when in range, else \"\".\n"
             "    static const char* lookup(const char* const* table, size_t count, uint16_t id) {\n"
             "        return id < count ? table[id] : \"\";\n"
             "    }\n\n")
    p.append("    const char* getMetLocationName(uint8_t originVersion, uint16_t locationId) {\n")
    p.append("        switch (originVersion) {\n")
    for cases, arr in DISPATCH:
        p.append(f"            case {cases}:\n")
        p.append(f"                return lookup({arr}, sizeof({arr}) / sizeof({arr}[0]), locationId);\n")
    p.append("            default:\n")
    p.append('                return "";\n')
    p.append("        }\n")
    p.append("    }\n")

    p.append("\n    // Raw table + size for a given origin, so a picker can enumerate the locations.\n")
    p.append("    LocationTable getLocationTable(uint8_t originVersion) {\n")
    p.append("        switch (originVersion) {\n")
    for cases, arr in DISPATCH:
        p.append(f"            case {cases}:\n")
        p.append(f"                return {{ {arr}, sizeof({arr}) / sizeof({arr}[0]) }};\n")
    p.append("            default:\n")
    p.append("                return { nullptr, 0 };\n")
    p.append("        }\n")
    p.append("    }\n")
    p.append("}\n")

    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("".join(p))

    print("Wrote", OUT)
    for arr, _, _, base in TABLES:
        print(f"  {arr}: {counts[arr]} entries  <- {base}")


if __name__ == "__main__":
    main()
