#!/usr/bin/env python3
"""Generate include/Utils/Gen4Text.h from PKHeX's StringConverter4Util tables.

Gen 4 does NOT store UTF-16. It stores 16-bit indices into a game code page, and the mapping is
nothing like identity: value 0x001 is a full-width space, 0x002-0x051 are hiragana, and the Latin
letters live at 0x0AC+ as FULL-WIDTH forms. Passing a Gen 4 name through as if it were UTF-16
yields CJK punctuation, not a name -- so the table has to come across.

Gen 5 is the opposite and must NOT share this: it stores real UTF-16, so it needs no table at all.
Routing Gen 5 text through this converter mangles every name in a way that still looks like text.

Two tables are emitted:
  GEN4_INT[]   the international page, indexed directly by the stored value
  GEN4_KOR[]   Korean, based at GEN4_KOR_START (values outside GEN4_INT's range)

plus a reverse map built at load time for encoding. The terminator is 0xFFFF.

PKHeX also normalises the gender glyphs on the way out (the half-width MALE/FEMALE signs against
the circled forms this page stores at U+246D/U+246E); that is done in Gen4Text.h's helpers rather
than baked into the table, so the raw round trip stays exact.
"""
from __future__ import annotations

import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pkhex_source import pkhex_path  # noqa: E402

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "include", "Utils", "Gen4Text.h")

TERMINATOR = 0xFFFF
# PKHeX: NUL is the terminator, EMP aliases it, HGM/HGF are the circled gender glyphs.
NAMED = {"NUL": TERMINATOR, "EMP": TERMINATOR, "HGM": 0x246D, "HGF": 0x246E}


def parse_table(text: str, name: str) -> list[int]:
    m = re.search(rf"{name}\s*=>\s*\[(.*?)\n    \];", text, re.S)
    if not m:
        raise SystemExit(f"could not find {name} in StringConverter4Util.cs")
    body = re.sub(r"//[^\n]*", "", m.group(1))          # strip the offset comments
    out: list[int] = []
    for tok in re.findall(r"'(?:\\u[0-9A-Fa-f]{4}|\\.|[^'])'|\b[A-Z][A-Z0-9_]*\b", body):
        if tok.startswith("'"):
            lit = tok[1:-1]
            if lit.startswith("\\u"):
                out.append(int(lit[2:], 16))
            elif lit.startswith("\\"):
                out.append({"n": 10, "t": 9, "r": 13, "0": 0, "\\": 92, "'": 39}[lit[1]])
            else:
                out.append(ord(lit))
        else:
            if tok not in NAMED:
                raise SystemExit(f"{name}: unknown named constant {tok!r}")
            out.append(NAMED[tok])
    return out


def main() -> int:
    path = pkhex_path("PKM/Strings/StringConverter4Util.cs")
    with open(path, encoding="utf-8") as fh:
        text = fh.read()

    intl = parse_table(text, "TableINT")
    kor = parse_table(text, "TableKOR")
    m = re.search(r"TableKORStart\s*=\s*(0x[0-9A-Fa-f]+|\d+)", text)
    kor_start = int(m.group(1), 0) if m else 0
    if kor_start == 0:
        raise SystemExit("could not read TableKORStart")

    # Sanity: the letters PKSE actually cares about must land where PKHeX says.
    # 0x0AC is full-width 'A' and 0x0A2 is full-width '0'.
    if intl[0x0AC] != ord("Ａ") or intl[0x0A2] != ord("０"):
        raise SystemExit(f"TableINT looks misparsed: 0x0AC={intl[0x0AC]:#x} 0x0A2={intl[0x0A2]:#x}")
    if intl[0] != TERMINATOR:
        raise SystemExit("TableINT[0] should be the terminator")

    print(f"  TableINT  {len(intl)} entries")
    print(f"  TableKOR  {len(kor)} entries, based at {kor_start:#x}")

    def emit(name: str, vals: list[int]) -> str:
        rows = []
        for i in range(0, len(vals), 12):
            rows.append("        " + " ".join("0x%04X," % v for v in vals[i:i + 12]))
        return ("    inline constexpr uint16_t %s[%d] = {\n%s\n    };\n" %
                (name, len(vals), "\n".join(rows)))

    h = []
    h.append("/**\n")
    h.append(" * Auto-generated by tools/gen_gen4text.py from PKHeX's StringConverter4Util.\n")
    h.append(" * DO NOT EDIT BY HAND -- rerun the generator instead.\n")
    h.append(" *\n")
    h.append(" * GEN 4 IS NOT UTF-16. It stores 16-bit indices into a game code page: 0x001 is a\n")
    h.append(" * full-width space, 0x002-0x051 hiragana, and the Latin letters sit at 0x0AC+ as\n")
    h.append(" * FULL-WIDTH forms. Reading a Gen 4 name as UTF-16 yields CJK punctuation.\n")
    h.append(" *\n")
    h.append(" * GEN 5 MUST NOT USE THIS. Gen 5 stores real UTF-16 and needs no table; routing it\n")
    h.append(" * through here mangles every name in a way that still looks like text.\n")
    h.append(" *\n")
    h.append(" * The sibling of Gen1Text.h / Gen3Text.h: one table, one header, and every Gen 4 name\n")
    h.append(" * call site routes through it. The Gen 3 charset once existed as four ad-hoc subsets\n")
    h.append(" * and the damage was invisible for months (BUGS Issue 33).\n")
    h.append(" */\n")
    h.append("#ifndef UTILS_GEN4TEXT_H\n#define UTILS_GEN4TEXT_H\n\n")
    h.append("#include <cstdint>\n#include <cstddef>\n#include <string>\n\n")
    h.append("namespace Utils {\n\n")
    h.append(f"    inline constexpr uint16_t GEN4_TERMINATOR = 0x{TERMINATOR:04X};\n")
    h.append(f"    inline constexpr uint16_t GEN4_KOR_START  = 0x{kor_start:04X};\n\n")
    h.append("    /// Stored value -> Unicode code point. Index directly; entries reading\n")
    h.append("    /// GEN4_TERMINATOR are unused slots, not real characters.\n")
    h.append(emit("GEN4_INT", intl))
    h.append("\n    /// Korean page, indexed by (value - GEN4_KOR_START).\n")
    h.append(emit("GEN4_KOR", kor))
    h.append("""
    /// Decodes one stored value. Returns 0 for anything unmapped, which callers treat as
    /// "stop" rather than as a character -- an unmapped value is corrupt data, not a glyph.
    inline uint16_t gen4ToChar(uint16_t value) noexcept {
        if (value < (sizeof(GEN4_INT) / sizeof(GEN4_INT[0]))) {
            const uint16_t unicode = GEN4_INT[value];
            return unicode == GEN4_TERMINATOR ? 0 : unicode;
        }
        const uint32_t koreanIndex = static_cast<uint32_t>(value) - GEN4_KOR_START;
        if (koreanIndex < (sizeof(GEN4_KOR) / sizeof(GEN4_KOR[0]))) {
            const uint16_t unicode = GEN4_KOR[koreanIndex];
            return unicode == GEN4_TERMINATOR ? 0 : unicode;
        }
        return 0;
    }

    /// Encodes one Unicode code point. Returns GEN4_TERMINATOR when the character has no Gen 4
    /// glyph, which is the signal for canStoreNickname() to REFUSE the name rather than write a
    /// name that ends early -- the Gen 3 lesson: silently dropping characters is invisible damage.
    inline uint16_t charToGen4(uint16_t unicode) noexcept {
        if (unicode == 0) return GEN4_TERMINATOR;
        for (uint32_t i = 0; i < (sizeof(GEN4_INT) / sizeof(GEN4_INT[0])); ++i) {
            if (GEN4_INT[i] == unicode) return static_cast<uint16_t>(i);
        }
        for (uint32_t i = 0; i < (sizeof(GEN4_KOR) / sizeof(GEN4_KOR[0])); ++i) {
            if (GEN4_KOR[i] == unicode) return static_cast<uint16_t>(i + GEN4_KOR_START);
        }
        return GEN4_TERMINATOR;
    }

    /// True when every character of `text` has a Gen 4 glyph. The editor asks this BEFORE accepting
    /// a name, so a rejection is explained with the name still on screen.
    inline bool gen4CanEncode(const std::u16string& text) noexcept {
        for (char16_t character : text) {
            if (charToGen4(static_cast<uint16_t>(character)) == GEN4_TERMINATOR) return false;
        }
        return true;
    }

    /**
     * Writes one Gen 4 text field: the whole field CLEARED TO ZERO, the encoded text, then exactly
     * ONE terminator.
     *
     * That is PKHeX's StringConverterOption.ClearZero, and the shape matters. A short name leaves
     * the rest of the field at 0x00 with a single 0xFFFF after the text -- NOT a field padded with
     * terminators. The game stops at the first one either way, so padding is invisible in play and
     * still rewrites bytes the game left alone, which is exactly what an unedited round trip is
     * supposed to prove PKSE does not do.
     *
     * @param destination first byte of the field
     * @param slotCount   total u16 units the field holds (one is reserved for the terminator)
     * @param text        UTF-16 text to store; characters with no Gen 4 glyph end the name, so ask
     *                    gen4CanEncode() first
     * @param maxCharacterCount the game's own cap on this field (7 for a trainer name, 8 for a box)
     */
    inline void writeGen4Field(uint8_t* destination, size_t slotCount, const std::u16string& text,
                               size_t maxCharacterCount) noexcept {
        if (destination == nullptr || slotCount == 0) return;
        for (size_t byteIndex = 0; byteIndex < slotCount * 2; ++byteIndex) {
            destination[byteIndex] = 0;
        }
        size_t writableCount = slotCount - 1;   // one unit reserved for the terminator
        if (writableCount > maxCharacterCount) writableCount = maxCharacterCount;
        if (writableCount > text.size()) writableCount = text.size();
        size_t slotIndex = 0;
        for (; slotIndex < writableCount; ++slotIndex) {
            const uint16_t encoded = charToGen4(static_cast<uint16_t>(text[slotIndex]));
            destination[slotIndex * 2] = static_cast<uint8_t>(encoded & 0xFF);
            destination[slotIndex * 2 + 1] = static_cast<uint8_t>((encoded >> 8) & 0xFF);
        }
        destination[slotIndex * 2] = static_cast<uint8_t>(GEN4_TERMINATOR & 0xFF);
        destination[slotIndex * 2 + 1] = static_cast<uint8_t>((GEN4_TERMINATOR >> 8) & 0xFF);
    }
}

#endif  // UTILS_GEN4TEXT_H
""")
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("".join(h))
    print(f"wrote {os.path.relpath(OUT, REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
