#!/usr/bin/env python3
"""Generate include/Pokemon/SWSHDexTable.h + src/Pokemon/SWSHDexTable.cpp from PKHeX.

Sword/Shield do not have one Pokedex -- they have three, each a separate save block with its
own numbering: Galar (400 entries), Isle of Armor (211) and Crown Tundra (210). A species
belongs to exactly one of them, and its entry sits at (index - 1) * 0x30 within that block.

The mapping lives in PKHeX's personal_swsh, three u16 fields per species record:
    0x5C PokeDexIndex (Galar)   0xAC ArmorDexIndex   0xAE CrownDexIndex
A species is placed in the first of those that is non-zero, matching Zukan8.GetDexLookup.
Only the form-0 record is consulted -- the dex index is a property of the species.

Nothing else in PKSE carries this, and it cannot be derived from the Gen 9 personal table the
rest of the app uses, so it gets its own generated table.

Run by hand when the PKHeX-derived data changes; the build only compiles the committed output.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pkhex_source import pkhex_path  # noqa: E402

REC = 0xB0
OFS_GALAR, OFS_ARMOR, OFS_CROWN = 0x5C, 0xAC, 0xAE
GALAR_COUNT, ARMOR_COUNT, CROWN_COUNT = 400, 211, 210
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def u16(b, o):
    return b[o] | (b[o + 1] << 8)


def main():
    with open(pkhex_path("Resources/byte/personal/personal_swsh"), "rb") as fh:
        data = fh.read()
    count = len(data) // REC
    print(f"personal_swsh: {len(data)} bytes, {count} records")

    # Records past MAX_SPECIES are alternate-FORM entries, and they carry a copy of their base
    # species' dex index -- reading them as species produces duplicate indices. PKHeX's
    # Zukan8.GetDexLookup walks species 1..MaxSpeciesID_8_R2 only, so do the same.
    MAX_SPECIES = 898  # Calyrex; Legal.MaxSpeciesID_8_R2
    print(f"consulting species 1..{MAX_SPECIES} (the rest of the table is form entries)")

    # species -> (dexType, index); dexType 0=Galar 1=Armor 2=Crown
    entries = {}
    maxsp = 0
    for sp in range(1, min(count, MAX_SPECIES + 1)):
        e = data[sp * REC:(sp + 1) * REC]
        if len(e) < REC:
            break
        for dex_type, ofs in ((0, OFS_GALAR), (1, OFS_ARMOR), (2, OFS_CROWN)):
            idx = u16(e, ofs)
            if idx:
                entries[sp] = (dex_type, idx)
                maxsp = max(maxsp, sp)
                break

    per_type = [sum(1 for v in entries.values() if v[0] == t) for t in range(3)]
    print(f"species with a dex entry: {len(entries)}  (Galar {per_type[0]}, "
          f"Armor {per_type[1]}, Crown {per_type[2]})")
    print(f"highest species with an entry: {maxsp}")

    # Sanity: indices must be unique within a dex and inside its declared count.
    limits = (GALAR_COUNT, ARMOR_COUNT, CROWN_COUNT)
    for t, name in enumerate(("Galar", "Armor", "Crown")):
        idxs = [v[1] for v in entries.values() if v[0] == t]
        dupes = {i for i in idxs if idxs.count(i) > 1}
        over = [i for i in idxs if i > limits[t]]
        print(f"  {name:<6} indices {min(idxs)}..{max(idxs)}  duplicates: {sorted(dupes) or 'none'}  "
              f"over the {limits[t]}-entry limit: {over or 'none'}")
        assert not dupes and not over

    hdr = """/**
 * SWSHDexTable.h - Sword/Shield Pokedex entry lookup. GENERATED by tools/gen_swshdex.py.
 *
 * SWSH has THREE Pokedexes, each its own save block with its own numbering: Galar (400
 * entries), Isle of Armor (211) and Crown Tundra (210). A species belongs to exactly one,
 * and its 0x30-byte entry sits at (index - 1) * 0x30 inside that block.
 *
 * Derived from PKHeX personal_swsh (PokeDexIndex / ArmorDexIndex / CrownDexIndex), which is
 * the only place this mapping exists -- it cannot be computed from the Gen 9 personal table
 * the rest of PKSE uses. Do not hand-edit; rerun the generator.
 */
#ifndef POKEMON_SWSH_DEX_TABLE_H
#define POKEMON_SWSH_DEX_TABLE_H

#include <cstdint>

namespace Pokemon {

    /// Which of the three Pokedex blocks a species lives in.
    enum class SWSHDex : uint8_t { None = 0, Galar = 1, Armor = 2, Crown = 3 };

    struct SWSHDexEntry {
        SWSHDex  dex;     ///< None when the species has no SWSH dex entry at all
        uint16_t index;   ///< 1-based index within that dex; entry offset = (index - 1) * 0x30
    };

    /// Entries per dex, for bounds-checking a block before writing into it.
    inline constexpr uint16_t SWSH_DEX_GALAR_COUNT = %d;
    inline constexpr uint16_t SWSH_DEX_ARMOR_COUNT = %d;
    inline constexpr uint16_t SWSH_DEX_CROWN_COUNT = %d;
    inline constexpr uint16_t SWSH_DEX_ENTRY_SIZE  = 0x30;

    /// Dex placement for a National Dex species, or {None, 0} if SWSH has no entry for it.
    SWSHDexEntry getSWSHDexEntry(uint16_t species) noexcept;
}

#endif
""" % (GALAR_COUNT, ARMOR_COUNT, CROWN_COUNT)

    rows = []
    for sp in range(0, maxsp + 1):
        t, i = entries.get(sp, (None, 0))
        name = {None: "None", 0: "Galar", 1: "Armor", 2: "Crown"}[t]
        rows.append("{ SWSHDex::%s, %4d }," % (name, i))
    body = ""
    for n in range(0, len(rows), 4):
        body += "        " + " ".join(rows[n:n + 4]) + "\n"

    cpp = """/**
 * SWSHDexTable.cpp - GENERATED by tools/gen_swshdex.py from PKHeX personal_swsh. Do not hand-edit.
 */
#include "Pokemon/SWSHDexTable.h"

namespace Pokemon {

    namespace {
        // Indexed by National Dex number. {None, 0} = the species has no SWSH dex entry.
        constexpr SWSHDexEntry TABLE[] = {
%s        };
        constexpr uint16_t TABLE_MAX = %d;
    }

    SWSHDexEntry getSWSHDexEntry(uint16_t species) noexcept {
        if (species == 0 || species > TABLE_MAX) return { SWSHDex::None, 0 };
        return TABLE[species];
    }
}
""" % (body, maxsp)

    hp = os.path.join(ROOT, "include", "Pokemon", "SWSHDexTable.h")
    cp = os.path.join(ROOT, "src", "Pokemon", "SWSHDexTable.cpp")
    with open(hp, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(hdr)
    with open(cp, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(cpp)
    print(f"\nwrote {hp}\nwrote {cp}")

    for sp, label in ((25, "Pikachu"), (890, "Eternatus"), (898, "Calyrex"), (1, "Bulbasaur")):
        if sp in entries:
            t, i = entries[sp]
            print(f"  spot check: {label:<10} -> {['Galar','Armor','Crown'][t]} #{i}")
        else:
            print(f"  spot check: {label:<10} -> not in any SWSH dex")


if __name__ == "__main__":
    main()
