#!/usr/bin/env python3
"""Generate include/Pokemon/PLADexTable.h + src/Pokemon/PLADexTable.cpp from PKHeX.

Legends: Arceus does not have a Pokedex in the shape every other game uses. Its block is a research
LOG, and it is split in two:

  * a per-SPECIES research entry (0x58 bytes each, 981 of them) holding the task counters, and
  * a per-SPECIES+FORM statistics entry (0x18 bytes each, 1480 of them) holding the seen/obtained
    flags and the size records.

The statistics entries are NOT indexed by species. They are reached through a lookup table keyed by
`species | (form << 11)` -- an arbitrary, hand-authored ordering with no derivable structure, which is
why it has to be copied rather than computed. PKHeX keeps it as two parallel arrays in
PokedexConstants8a (FormStorageIndexIds -> FormStorageIndexValues), sorted so the key can be found by
binary search; that is reproduced verbatim here.

PokemonInfoIds / PokemonInfoGenders come along too: the gender flag decides whether an entry tracks
male and female separately, which the "selected variant" logic needs.

Run by hand when the PKHeX-derived data changes; the build only compiles the committed output.
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pkhex_source import pkhex_path  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = "Saves/Substructures/Gen8/LA/Pokedex/PokedexConstants8a.cs"


def grab(text, name):
    """Extract the numeric literals of a `ReadOnlySpan<T> Name => [ ... ];` array."""
    start = text.index(name + " =>")
    body = text[text.index("[", start) + 1: text.index("];", start)]
    return [int(x, 0) for x in re.findall(r"0x[0-9A-Fa-f]+|\d+", body)]


def main():
    with open(pkhex_path(SRC), encoding="utf-8-sig") as fh:
        text = fh.read()

    ids = grab(text, "FormStorageIndexIds")
    vals = grab(text, "FormStorageIndexValues")
    info_ids = grab(text, "PokemonInfoIds")
    info_gender = grab(text, "PokemonInfoGenders")

    print(f"FormStorageIndexIds   {len(ids)}")
    print(f"FormStorageIndexValues {len(vals)}")
    print(f"PokemonInfoIds        {len(info_ids)}")
    print(f"PokemonInfoGenders    {len(info_gender)}")

    assert len(ids) == len(vals), "the two FormStorageIndex arrays must be parallel"
    assert len(info_ids) == len(info_gender), "the two PokemonInfo arrays must be parallel"
    assert ids == sorted(ids), "ids must be sorted -- the lookup binary-searches them"
    assert info_ids == sorted(info_ids), "info ids must be sorted"
    assert len(set(ids)) == len(ids), "duplicate key in FormStorageIndexIds"
    assert max(vals) < 1480, f"statistics index {max(vals)} is outside the 1480-entry region"

    # A key is species | form<<11, so decoding it back must give a sane species/form pair.
    for k in ids:
        assert (k & 0x7FF) <= 981 and (k >> 11) < 120, f"key {k} decodes out of range"
    print(f"highest statistics index used: {max(vals)}  (region holds 1480)")
    print(f"keys with a non-zero form: {sum(1 for k in ids if k >> 11)}")

    def rows(vs, per, width, hexfmt=False):
        out = ""
        for n in range(0, len(vs), per):
            out += "        " + " ".join(
                (f"0x{v:02X}," if hexfmt else f"{v:>{width}},") for v in vs[n:n + per]) + "\n"
        return out

    hdr = """/**
 * PLADexTable.h - Legends: Arceus Pokedex lookup tables. GENERATED by tools/gen_pladex.py.
 *
 * PLA's dex block is a research LOG, split into a per-SPECIES research entry (0x58 bytes) and a
 * per-SPECIES+FORM statistics entry (0x18 bytes) that holds the seen/obtained flags. The statistics
 * entries are not indexed by species: they are reached through a lookup keyed by
 * `species | (form << 11)`, an arbitrary ordering with no derivable structure. Copied verbatim from
 * PKHeX PokedexConstants8a; do not hand-edit, rerun the generator.
 */
#ifndef POKEMON_PLA_DEX_TABLE_H
#define POKEMON_PLA_DEX_TABLE_H

#include <cstdint>

namespace Pokemon {

    /// Returned when the species+form has no statistics entry (it cannot appear in PLA's dex).
    inline constexpr uint16_t PLA_NO_STAT_ENTRY = 0xFFFF;

    /// Number of statistics entries the block allocates.
    inline constexpr uint16_t PLA_STATISTICS_ENTRIES = 1480;

    /// Highest species with a research entry (PKHeX PokedexSave8a.MAX_SPECIES).
    inline constexpr uint16_t PLA_MAX_SPECIES = %d;

    /// Highest form the dex tables address (PKHeX PokedexSave8a.MAX_FORM).
    inline constexpr uint8_t  PLA_MAX_FORM = %d;

    /// Statistics-entry index for a (species, form), or PLA_NO_STAT_ENTRY when it has none.
    uint16_t getPLAStatisticsIndex(uint16_t species, uint8_t form) noexcept;

    /// True when the dex tracks this species+form's genders SEPARATELY (PokemonInfoGenders bit 3).
    /// Where false, the male and female slots are one shared record.
    bool plaTracksGenderSeparately(uint16_t species, uint8_t form) noexcept;
}

#endif
""" % (981, 120)

    cpp = """/**
 * PLADexTable.cpp - GENERATED by tools/gen_pladex.py from PKHeX PokedexConstants8a. Do not hand-edit.
 */
#include "Pokemon/PLADexTable.h"

namespace Pokemon {

    namespace {
        // Sorted keys (species | form<<11) and the statistics index each maps to.
        constexpr uint16_t STORAGE_KEYS[] = {
%s        };
        constexpr uint16_t STORAGE_VALUES[] = {
%s        };
        constexpr int STORAGE_COUNT = static_cast<int>(sizeof(STORAGE_KEYS) / sizeof(STORAGE_KEYS[0]));

        // Sorted keys again, with the per-entry gender byte. Bit 3 = the two genders are tracked apart.
        constexpr uint16_t INFO_KEYS[] = {
%s        };
        constexpr uint8_t INFO_GENDERS[] = {
%s        };
        constexpr int INFO_COUNT = static_cast<int>(sizeof(INFO_KEYS) / sizeof(INFO_KEYS[0]));

        // Same binary search PKHeX uses; -1 when absent.
        int findKey(const uint16_t* keys, int count, uint16_t key) noexcept {
            int lo = 0, hi = count - 1;
            while (lo <= hi) {
                const int mid = lo + ((hi - lo) >> 1);
                if      (keys[mid] == key) return mid;
                else if (keys[mid] <  key) lo = mid + 1;
                else                       hi = mid - 1;
            }
            return -1;
        }

        uint16_t packKey(uint16_t species, uint8_t form) noexcept {
            return static_cast<uint16_t>(species | (static_cast<uint16_t>(form) << 11));
        }
    }

    uint16_t getPLAStatisticsIndex(uint16_t species, uint8_t form) noexcept {
        if (species == 0 || species > PLA_MAX_SPECIES || form >= PLA_MAX_FORM) return PLA_NO_STAT_ENTRY;
        const int i = findKey(STORAGE_KEYS, STORAGE_COUNT, packKey(species, form));
        return (i < 0) ? PLA_NO_STAT_ENTRY : STORAGE_VALUES[i];
    }

    bool plaTracksGenderSeparately(uint16_t species, uint8_t form) noexcept {
        if (species == 0 || species > PLA_MAX_SPECIES || form >= PLA_MAX_FORM) return false;
        const int i = findKey(INFO_KEYS, INFO_COUNT, packKey(species, form));
        return (i >= 0) && (INFO_GENDERS[i] & 0x08) != 0;
    }
}
""" % (rows(ids, 12, 6), rows(vals, 12, 5), rows(info_ids, 12, 6),
       rows(info_gender, 12, 4, hexfmt=True))

    hp = os.path.join(ROOT, "include", "Pokemon", "PLADexTable.h")
    cp = os.path.join(ROOT, "src", "Pokemon", "PLADexTable.cpp")
    with open(hp, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(hdr)
    with open(cp, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(cpp)
    print(f"\nwrote {hp}\nwrote {cp}")

    # Spot checks against the raw arrays, so a mangled emit is caught here rather than on hardware.
    lookup = dict(zip(ids, vals))
    for sp, fm, label in ((25, 0, "Pikachu"), (493, 0, "Arceus"), (899, 0, "Wyrdeer"),
                          (58, 1, "Growlithe-Hisui"), (59, 1, "Arcanine-Hisui"), (100, 1, "Voltorb-Hisui")):
        k = sp | (fm << 11)
        print(f"  spot check: {label:<18} key={k:<6} -> "
              f"{lookup.get(k, 'no statistics entry')}")


if __name__ == "__main__":
    main()
