#!/usr/bin/env python3
"""Generate include/Names/MovePresence.h + src/Names/MovePresence.cpp -- a per-game
"is this move present (usable) in this game?" bitmap, transcribed from PKHeX.

PKHeX's move editor (FilteredGameDataSource.GetFilteredMoves) shows only moves that
actually exist in the game: it drops moves above the game's max id AND "dummied" moves
(present in the id space but disabled -- e.g. Pound in Legends: Arceus). It does NOT
filter by species legality. PKSE's move picker mirrors this so a user can't set a move
the game turns into a Bad Egg (a dummied move), while still being free to set a present
move the species can't legally learn (flagged by the legality check).

Per game the presence set is:
  * Gen 8/9 (SwSh/PLA/BDSP/SV/ZA): move in [1 .. len(PP)-1] and NOT in DummiedMoves.
  * Let's Go (Gen7b): move in MoveInfo7b.AllowedMoves.
  * FireRed/LeafGreen (Gen3): move in [1 .. 354] (Legal.MaxMoveID_3; no dummied concept).

Regenerate:  python tools/gen_movepresence.py
Pulls the PKHeX sources it reads from GitHub on demand (tools/pkhex_source.py);
no local PKHeX checkout required.
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pkhex_source import pkhex_path  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_H = os.path.join(ROOT, "include", "Names", "MovePresence.h")
OUT_CPP = os.path.join(ROOT, "src", "Names", "MovePresence.cpp")

MAX_MOVE_ID_3 = 354  # PKHeX Legal.MaxMoveID_3


def _array_body(path, decl_regex):
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    # The declaration may carry a trailing // comment between "=>" and the "[".
    m = re.search(decl_regex + r"\s*=>\s*(?://[^\n]*\n\s*)?\[(.*?)\];", text, re.DOTALL)
    if not m:
        raise SystemExit("Could not find %s in %s" % (decl_regex, path))
    return m.group(1)


def pp_max(fname):
    body = _array_body(pkhex_path("Moves/" + fname), r"public static ReadOnlySpan<byte> PP")
    return len(re.findall(r"\d+", body)) - 1  # PP[0..max]


def dummied_set(fname):
    body = _array_body(pkhex_path("Moves/" + fname), r"public static ReadOnlySpan<byte> DummiedMoves")
    bytes_ = [int(x, 16) for x in re.findall(r"0x[0-9A-Fa-f]{2}", body)]
    out = set()
    for i, b in enumerate(bytes_):
        for bit in range(8):
            if b & (1 << bit):
                out.add(i * 8 + bit)
    return out


def allowed_set(fname):
    body = _array_body(pkhex_path("Moves/" + fname), r"ReadOnlySpan<ushort> AllowedMoves")
    return {int(x) for x in re.findall(r"\d+", body)}


def present_gen89(fname, pp_fname=None):
    # BDSP (MoveInfo8b) has no PP array of its own -- it shares SwSh's Gen 8 move range,
    # so borrow that file's PP for the upper bound while using its own dummied bitmap.
    mx = pp_max(pp_fname or fname)
    dummied = dummied_set(fname)
    return {m for m in range(1, mx + 1) if m not in dummied}


def to_bitmap(present, size_bytes):
    bm = bytearray(size_bytes)
    for m in present:
        if 0 <= m < size_bytes * 8:
            bm[m >> 3] |= 1 << (m & 7)
    return bm


def main():
    games = {
        "SWSH": present_gen89("MoveInfo8.cs"),
        "PLA": present_gen89("MoveInfo8a.cs"),
        "BDSP": present_gen89("MoveInfo8b.cs", pp_fname="MoveInfo8.cs"),
        "SV": present_gen89("MoveInfo9.cs"),
        "ZA": present_gen89("MoveInfo9a.cs"),
        "GG": allowed_set("MoveInfo7b.cs"),
        "FRLG": set(range(1, MAX_MOVE_ID_3 + 1)),
    }
    hi = max(max(s) for s in games.values())
    size_bytes = (hi // 8) + 1
    print("Highest move id %d -> %d-byte bitmaps" % (hi, size_bytes))
    for name, s in games.items():
        print("  %-5s %d present moves (Pound=%s)" % (name, len(s), 1 in s))

    with open(OUT_H, "w", encoding="utf-8", newline="\n") as fh:
        fh.write('''/**
 * MovePresence.h - Is a move present (usable) in a given game?
 *
 * Auto-generated by tools/gen_movepresence.py from PKHeX (DummiedMoves / AllowedMoves /
 * PP tables). DO NOT EDIT BY HAND -- rerun the generator instead.
 *
 * Mirrors PKHeX's move-editor filter: a game only exposes the moves that exist in it
 * (dropping "dummied"/out-of-range moves). Used by the move picker so a dummied move
 * (e.g. Pound in Legends: Arceus, which the game turns into a Bad Egg) can't be set;
 * species legality is a separate, non-blocking warning.
 */
#ifndef NAMES_MOVE_PRESENCE_H
#define NAMES_MOVE_PRESENCE_H

#include <cstdint>

#include "Enums/GameVersion.h"

namespace Names {
    /// True iff moveId exists (is not dummied / out of range) in the given game group.
    /// Unknown groups return true (no filtering). Id 0 (None) returns false.
    bool isMovePresent(uint16_t moveId, Enums::GameVersion group);
}

#endif  // NAMES_MOVE_PRESENCE_H
''')

    def emit_array(cname, bm):
        rows = []
        for i in range(0, len(bm), 12):
            rows.append("        " + ", ".join("0x%02X" % b for b in bm[i:i + 12]))
        return "    static const uint8_t %s[%d] = {\n%s\n    };\n" % (cname, len(bm), ",\n".join(rows))

    order = ["SWSH", "PLA", "BDSP", "SV", "ZA", "GG", "FRLG"]
    with open(OUT_CPP, "w", encoding="utf-8", newline="\n") as fh:
        fh.write('''/**
 * MovePresence.cpp - Per-game move-presence bitmaps.
 *
 * Auto-generated by tools/gen_movepresence.py. DO NOT EDIT BY HAND.
 */
#include "Names/MovePresence.h"

namespace Names {

''')
        for name in order:
            fh.write(emit_array("P_" + name, to_bitmap(games[name], size_bytes)))
            fh.write("\n")
        fh.write('''    bool isMovePresent(uint16_t moveId, Enums::GameVersion group) {
        const uint8_t* bm;
        switch (group) {
            case Enums::GameVersion::SWSH: bm = P_SWSH; break;
            case Enums::GameVersion::PLA:  bm = P_PLA;  break;
            case Enums::GameVersion::BDSP: bm = P_BDSP; break;
            case Enums::GameVersion::SV:   bm = P_SV;   break;
            case Enums::GameVersion::ZA:   bm = P_ZA;   break;
            case Enums::GameVersion::GG:   bm = P_GG;   break;
            case Enums::GameVersion::FRLG: bm = P_FRLG; break;
            default: return true;   // unknown group: don't filter
        }
        return (moveId >> 3) < %d && ((bm[moveId >> 3] >> (moveId & 7)) & 1) != 0;
    }

}
''' % size_bytes)

    print("Wrote", OUT_H)
    print("Wrote", OUT_CPP)


if __name__ == "__main__":
    main()
