#!/usr/bin/env python3
"""Generate include/Pokemon/SVDexTable.h + src/Pokemon/SVDexTable.cpp from PKHeX.

Scarlet/Violet has THREE regional Pokedexes -- Paldea, Kitakami and Blueberry -- but unlike
Sword/Shield they share ONE save block. Each 0x20-byte Zukan entry carries three independent
"displayed variant" slots, one per regional dex (form/gender/shiny at 0x14 / 0x18 / 0x1C), and
the game only reads the slot for a dex the species actually appears in.

Membership is per (species, FORM), not per species: Kantonian Meowth is a Paldea-dex entry
while Alolan Meowth is a Blueberry-dex one, so writing the displayed slot without consulting
this table makes the regular Pokedex render a regional variant it should never show.

Source: PKHeX personal_sv, three fields per record --
    0x1E u16 DexPaldea      0x4A u8 DexKitakami      0x4B u8 DexBlueberry
plus the form redirection the rest of the table uses (0x18 u16 FormStatsIndex, 0x1A u8
FormCount). PKSE's own PersonalInfoTable cannot supply this: its alternate-form rows are the
union across all supported games, so its row indices do not line up with personal_sv's.

Run by hand when the PKHeX-derived data changes; the build only compiles the committed output.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pkhex_source import pkhex_path  # noqa: E402

REC = 0x50
OFS_FORM_INDEX, OFS_FORM_COUNT = 0x18, 0x1A
OFS_PALDEA, OFS_KITAKAMI, OFS_BLUEBERRY = 0x1E, 0x4A, 0x4B
MAX_SPECIES = 1025  # Pecharunt; Legal.MaxSpeciesID_9
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def u16(b, o):
    return b[o] | (b[o + 1] << 8)


def main():
    with open(pkhex_path("Resources/byte/personal/personal_sv"), "rb") as fh:
        data = fh.read()
    count = len(data) // REC
    print(f"personal_sv: {len(data)} bytes, {count} records ({REC} each)")
    assert count > MAX_SPECIES, "table shorter than the species range"

    rows = []          # one per record, index == PKHeX's own record index
    for i in range(count):
        e = data[i * REC:(i + 1) * REC]
        rows.append((u16(e, OFS_PALDEA), e[OFS_KITAKAMI], e[OFS_BLUEBERRY],
                     u16(e, OFS_FORM_INDEX), e[OFS_FORM_COUNT]))

    in_any = sum(1 for r in rows if r[0] or r[1] or r[2])
    print(f"records in at least one regional dex: {in_any}")
    for n, (label, col) in enumerate((("Paldea", 0), ("Kitakami", 1), ("Blueberry", 2))):
        idxs = [r[col] for r in rows if r[col]]
        dupes = sorted({i for i in idxs if idxs.count(i) > 1})
        print(f"  {label:<10} {len(idxs):>4} records, indices {min(idxs)}..{max(idxs)}"
              f"  duplicates: {dupes or 'none'}")

    # A form's dex membership is what this table exists for, so prove the redirection works on
    # the case that motivated it: Kantonian vs Alolan Meowth must land in DIFFERENT dexes.
    def entry(species, form):
        base = rows[species]
        if form == 0 or base[3] == 0 or form >= base[4]:
            return base
        idx = base[3] + form - 1
        return rows[idx] if idx < len(rows) else base

    def where(species, form):
        p, k, b, _, _ = entry(species, form)
        return ", ".join(n for n, v in (("Paldea", p), ("Kitakami", k), ("Blueberry", b)) if v) or "none"

    print("\n  spot checks (species, form -> dexes):")
    for sp, fm, label in ((52, 0, "Meowth"), (52, 1, "Meowth-Alola"), (52, 2, "Meowth-Galar"),
                          (50, 0, "Diglett"), (50, 1, "Diglett-Alola"),
                          (27, 0, "Sandshrew"), (27, 1, "Sandshrew-Alola"),
                          (25, 0, "Pikachu"), (1000, 0, "Gholdengo")):
        print(f"    {label:<16} -> {where(sp, fm)}")
    assert where(52, 0) != where(52, 1), "Meowth forms must differ, or the redirect is broken"

    hdr = """/**
 * SVDexTable.h - Scarlet/Violet regional-Pokedex membership. GENERATED by tools/gen_svdex.py.
 *
 * S/V has three regional Pokedexes (Paldea, Kitakami, Blueberry) sharing ONE Zukan block. Each
 * 0x20-byte entry carries a separate "displayed variant" slot per regional dex -- form/gender/
 * shiny at 0x14, 0x18 and 0x1C -- and the game only reads the slot for a dex the species is
 * actually listed in. Stamping a slot for a dex it does not belong to makes that Pokedex render
 * a variant it should never show.
 *
 * Membership is per (species, FORM): Kantonian Meowth is a Paldea entry while Alolan Meowth is a
 * Blueberry one. Derived from PKHeX personal_sv (DexPaldea / DexKitakami / DexBlueberry), which
 * PKSE's PersonalInfoTable cannot supply -- its form rows are the union across all supported
 * games, so its indices do not line up. Do not hand-edit; rerun the generator.
 */
#ifndef POKEMON_SV_DEX_TABLE_H
#define POKEMON_SV_DEX_TABLE_H

#include <cstdint>

namespace Pokemon {

    /// Which regional Pokedexes a (species, form) appears in. 0 = not in that dex.
    struct SVDexEntry {
        uint16_t paldea;      ///< Paldea dex index
        uint8_t  kitakami;    ///< Kitakami dex index
        uint8_t  blueberry;   ///< Blueberry dex index

        bool inAnyDex() const noexcept { return paldea != 0 || kitakami != 0 || blueberry != 0; }
    };

    /// Highest National Dex species S/V has a record for.
    inline constexpr uint16_t SV_DEX_MAX_SPECIES = %d;

    /// Regional-dex membership for a (species, form). Out-of-range species or forms fall back to
    /// the species' form-0 record, mirroring PKHeX PersonalTable9SV.GetFormIndex.
    const SVDexEntry& getSVDexEntry(uint16_t species, uint8_t form) noexcept;
}

#endif
""" % MAX_SPECIES

    table = []
    for p, k, b, _, _ in rows:
        table.append("{ %4d, %3d, %3d }," % (p, k, b))
    body = ""
    for n in range(0, len(table), 5):
        body += "        " + " ".join(table[n:n + 5]) + "\n"

    redirect = []
    for sp in range(MAX_SPECIES + 1):
        redirect.append("{ %4d, %2d }," % (rows[sp][3], rows[sp][4]))
    rbody = ""
    for n in range(0, len(redirect), 8):
        rbody += "        " + " ".join(redirect[n:n + 8]) + "\n"

    cpp = """/**
 * SVDexTable.cpp - GENERATED by tools/gen_svdex.py from PKHeX personal_sv. Do not hand-edit.
 */
#include "Pokemon/SVDexTable.h"

namespace Pokemon {

    namespace {
        // One row per personal_sv record: indices 0..SV_DEX_MAX_SPECIES are the form-0 entries,
        // the rest are alternate forms a base row's formIndex redirects into.
        constexpr SVDexEntry TABLE[] = {
%s        };
        constexpr uint16_t TABLE_COUNT = static_cast<uint16_t>(sizeof(TABLE) / sizeof(TABLE[0]));

        // Per-species form redirection, copied from the same records (FormStatsIndex, FormCount).
        struct FormRedirect { uint16_t index; uint8_t count; };
        constexpr FormRedirect FORMS[] = {
%s        };
    }

    const SVDexEntry& getSVDexEntry(uint16_t species, uint8_t form) noexcept {
        if (species == 0 || species > SV_DEX_MAX_SPECIES) return TABLE[0];
        const FormRedirect& fr = FORMS[species];
        if (form == 0 || fr.index == 0 || form >= fr.count) return TABLE[species];
        const uint16_t idx = static_cast<uint16_t>(fr.index + form - 1);
        return (idx < TABLE_COUNT) ? TABLE[idx] : TABLE[species];
    }
}
""" % (body, rbody)

    hp = os.path.join(ROOT, "include", "Pokemon", "SVDexTable.h")
    cp = os.path.join(ROOT, "src", "Pokemon", "SVDexTable.cpp")
    with open(hp, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(hdr)
    with open(cp, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(cpp)
    print(f"\nwrote {hp}\nwrote {cp}")


if __name__ == "__main__":
    main()
