#!/usr/bin/env python3
"""Generate include/Names/MoveInfo.h + src/Names/MoveInfo.cpp -- a move id -> base PP
table, transcribed from PKHeX's MoveInfo9.PP (Gen 9).

The creator/move-picker set a move id but the entity's setMove() deliberately does NOT
set PP (it needs a base-PP table); without this the game shows every created/picked move
at "0 PP". Base PP is indexed by move id, exactly like the generated MoveNames table, and
is stable across Gen 8/9 for shared moves, so the single Gen 9 array covers every pickable
move id (moves a game doesn't have are never offered by the picker).

Regenerate:  python tools/gen_moveinfo.py
Pulls the PKHeX source it reads from GitHub on demand (tools/pkhex_source.py);
no local PKHeX checkout required.
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pkhex_source import pkhex_path  # noqa: E402

SRC = pkhex_path("Moves/MoveInfo9.cs")
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_H = os.path.join(ROOT, "include", "Names", "MoveInfo.h")
OUT_CPP = os.path.join(ROOT, "src", "Names", "MoveInfo.cpp")


def main():
    with open(SRC, encoding="utf-8") as fh:
        text = fh.read()
    m = re.search(r"public static ReadOnlySpan<byte> PP\s*=>\s*\[(.*?)\];", text, re.DOTALL)
    if not m:
        raise SystemExit("Could not find the PP array in " + SRC)
    pp = [int(x) for x in re.findall(r"\d+", m.group(1))]
    if len(pp) < 2 or pp[0] != 0:
        raise SystemExit("Unexpected PP array (len=%d, [0]=%s)" % (len(pp), pp[:1]))
    print("Parsed %d move PP values (max move id %d)" % (len(pp), len(pp) - 1))

    with open(OUT_H, "w", encoding="utf-8", newline="\n") as fh:
        fh.write('''/**
 * MoveInfo.h - Base PP of a move, by move id.
 *
 * Auto-generated by tools/gen_moveinfo.py from PKHeX MoveInfo9.PP.
 * DO NOT EDIT BY HAND -- rerun the generator instead.
 *
 * Used to set a move's PP when it is created or picked in the editor; the entity's
 * setMove() does not set PP on its own, so without this the game reads 0 PP.
 */
#ifndef NAMES_MOVE_INFO_H
#define NAMES_MOVE_INFO_H

#include <cstdint>

namespace Names {
    /// Base PP (with 0 PP-ups) for a move id. Returns 0 for the empty slot (id 0) and
    /// a small non-zero fallback for ids outside the table (never offered by the picker).
    uint8_t getMoveBasePP(uint16_t moveId);
}

#endif  // NAMES_MOVE_INFO_H
''')

    rows = []
    for i in range(0, len(pp), 20):
        rows.append("        " + " ".join("%d," % v for v in pp[i:i + 20]))
    body = "\n".join(rows)
    with open(OUT_CPP, "w", encoding="utf-8", newline="\n") as fh:
        fh.write('''/**
 * MoveInfo.cpp - Base PP of a move, by move id.
 *
 * Auto-generated by tools/gen_moveinfo.py from PKHeX MoveInfo9.PP.
 * DO NOT EDIT BY HAND -- rerun the generator instead.
 */
#include "Names/MoveInfo.h"

namespace Names {

    static const uint8_t MOVE_BASE_PP[] = {
%s
    };

    uint8_t getMoveBasePP(uint16_t moveId) {
        constexpr uint16_t N = static_cast<uint16_t>(sizeof(MOVE_BASE_PP) / sizeof(MOVE_BASE_PP[0]));
        return moveId < N ? MOVE_BASE_PP[moveId] : 5;
    }
}
''' % body)

    print("Wrote", OUT_H)
    print("Wrote", OUT_CPP)


if __name__ == "__main__":
    main()
