#!/usr/bin/env python3
"""Apply the PKSE Simplified Chinese UI string table."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

TRANSLATIONS = {
    "      Page ": "      第 ",
    "     No. ": "     编号 ",
    "    No. ": "    编号 ",
    "   Lv. ": "   等级 ",
    " (Lv. ": " (等级 ",
    " - can't go in this game": " - 无法存入此游戏",
    " Pokémon save": " 个宝可梦存档",
    " Pokémon saves": " 个宝可梦存档",
    " Pokémon?": "只宝可梦？",
    " in bank": " 在银行中",
    " issue(s)  -  R / tap to view": " 个问题  -  按 R／点击查看",
    " items": " 个道具",
    " mon": "只宝可梦",
    " mons": "只宝可梦",
    " more)": " 个未显示)",
    " selected": " 个已选择",
    " stored": " 个已存储",
    "'s save data": "的存档数据",
    "(none)": "（无）",
    ":  Empty": "：空",
    "A / tap: Edit": "A／点击：编辑",
    "A: Confirm": "A：确认",
    "A: Edit  |  Y: Ribbons  |  L: Randomize IVs  |  ": "A：编辑  |  Y：奖章  |  L：随机个体值  |  ",
    "A: Release  |  B: Cancel": "A：放生  |  B：取消",
    "A: Remove  |  B: Cancel": "A：移除  |  B：取消",
    "A: Save Changes  |  B: Cancel": "A：保存更改  |  B：取消",
    "A: Select    B: Cancel    L/R: Page": "A：选择    B：取消    L/R：翻页",
    "A: Select  |  +: Exit": "A：选择  |  +：退出",
    "A: Select  |  B: Back": "A：选择  |  B：返回",
    "A: Select  |  L/R: Switch User  |  +: Exit": "A：选择  |  L/R：切换用户  |  +：退出",
    "A: Select  |  X: Delete  |  B: Back": "A：选择  |  X：删除  |  B：返回",
    "A: toggle     B: back": "A：切换     B：返回",
    "Ability": "特性",
    "Add Item to Pouch": "向口袋添加道具",
    "Allow illegal values": "允许非法数值",
    "An older backup can now be written over your live game save.": "现在可以用旧备份覆盖游戏中的实时存档。",
    "Any progress made since that backup will be lost.": "该备份之后的所有游戏进度都将丢失。",
    "Apparently met": "相遇方式",
    "Arrows": "方向键",
    "Atk": "攻击",
    "Auto-backup on load": "载入时自动备份",
    "Awakening Values (each 0-200, no total cap)": "觉醒值（每项 0-200，无总和上限）",
    "B / tap: close": "B／点击：关闭",
    "B: Back  |  +: Exit App": "B：返回  |  +：退出应用",
    "B: Close": "B：关闭",
    "B: Discard": "B：放弃",
    "BACKUP": "备份",
    "Back": "返回",
    "Backup name": "备份名称",
    "Backups can no longer be written over your live game save.": "备份将不能再覆盖游戏中的实时存档。",
    "Base": "普通形态",
    "Ball": "精灵球",
    "Bank N": "银行箱 N",
    "Bank box name reset to default.": "银行箱名称已恢复默认。",
    "Bank box name": "银行箱名称",
    "Bank unavailable": "银行不可用",
    "Box ": "盒子 ",
    "Box N": "盒子 N",
    "Box name cleared.": "盒子名称已清除。",
    "Box name selected - press A to rename": "已选择盒子名称 - 按 A 重命名",
    "Box name": "盒子名称",
    "Box sorted by Dex No. (": "盒子已按图鉴编号排序（",
    "Cancel": "取消",
    "Change Item To": "更换道具",
    "Changes will be lost if you continue.": "继续操作将丢失这些更改。",
    "Check Summary": "查看能力",
    "Clear selection": "清除选择",
    "Clone": "复制",
    "Close": "关闭",
    "Confirm": "确认",
    "Contains values the games treat as illegal.": "包含游戏判定为非法的数值。",
    "Continue with this transfer?": "要继续传送吗？",
    "Continue": "继续",
    "Convert to Gen 3?": "要转换为第三世代格式吗？",
    "Couldn't create that backup. Use letters, numbers, spaces or -.": "无法创建该备份。请仅使用字母、数字、空格或 -。",
    "Couldn't create the backup. Check SD card space and try again.": "无法创建备份。请检查 SD 卡空间后重试。",
    "Couldn't save the bank - NOT exiting, so nothing is lost. Check SD space.": "无法保存银行。为防止数据丢失，暂不退出。请检查 SD 卡空间。",
    "Couldn't save the bank - staying in storage so nothing is lost.": "无法保存银行。为防止数据丢失，将停留在存储界面。",
    "Create New Backup": "新建备份",
    "Cured": "已痊愈",
    "D-Pad": "方向键",
    "Dark": "深色",
    "Def": "防御",
    "Delete Backup?": "删除备份？",
    "Delete": "删除",
    "Discard & Exit": "放弃并退出",
    "Discard changes": "放弃更改",
    "Discard removes it; Back keeps editing.": "放弃将移除它；返回可继续编辑。",
    "Discard": "放弃",
    "Down": "下",
    "Debug logging off. No new log files will be written.": "调试日志已关闭，不会写入新的日志文件。",
    "Debug logging on. Logs are written to sdmc:/PKSE/logs.": "调试日志已开启，日志将写入 sdmc:/PKSE/logs。",
    "EXP": "经验值",
    "Edit ": "编辑",
    "Edit Item": "编辑道具",
    "Edit": "编辑",
    "Enable Debug Logging": "启用调试日志",
    "Egg Date (YYYYMMDD)": "蛋获得日期（YYYYMMDD）",
    "Egg Date": "蛋获得日期",
    "Egg Loc": "蛋获得地点",
    "Egg": "蛋",
    "Empty slot": "空槽位",
    "Empty": "空",
    "Fateful": "命运的相遇",
    "Female": "雌性",
    "Form ": "形态 ",
    "Form": "形态",
    "Friendship": "亲密度",
    "From an egg": "来自蛋",
    "Full SID": "完整 SID",
    "Full TID": "完整 TID",
    "GAME": "游戏",
    "Game save": "游戏存档",
    "Gender": "性别",
    "Genderless": "无性别",
    "Held Item": "携带道具",
    "Holding: ": "拿起中：",
    "ITEM": "道具",
    "Infected": "感染中",
    "Inject backups to game save": "允许备份写入游戏存档",
    "Invalid category": "无效分类",
    "Invalid date -- use YYYYMMDD.": "日期无效，请使用 YYYYMMDD 格式。",
    "It will be taken out of this pocket.": "该道具将从此口袋移除。",
    "Item removed.": "道具已移除。",
    "Items - ": "道具 - ",
    "Items": "道具",
    "Keep this new Pokemon?": "保留这只新宝可梦吗？",
    "Keep this new Pokémon?": "保留这只新宝可梦吗？",
    "Keep": "保留",
    "KeyItems": "重要道具",
    "L/R: Box  |  A: Rename  |  B: Back": "L/R：盒子  |  A：重命名  |  B：返回",
    "Language": "语言",
    "Left": "左",
    "Left/Right": "左／右",
    "Legality": "合法性",
    "Legality: ": "合法性：",
    "Legality: no problems found": "合法性：未发现问题",
    "Let's Go move warning": "Let's Go 招式警告",
    "Let's Go transfer": "Let's Go 传送",
    "Level": "等级",
    "Light": "浅色",
    "Load from Title (Create New Backup)": "从游戏载入（创建新备份）",
    "Load from Title (Working Copy)": "从游戏载入（工作副本）",
    "Load from Title": "从游戏载入",
    "Lv. ": "等级 ",
    "MENU": "菜单",
    "MOVE": "移动",
    "MULTI": "多选",
    "Male": "雄性",
    "Met Date (YYYYMMDD)": "相遇日期（YYYYMMDD）",
    "Met Date": "相遇日期",
    "Met Lv": "相遇等级",
    "Met": "相遇地点",
    "Minus": "减号键",
    "Money": "金钱",
    "Move to other side": "移动到另一侧",
    "Move": "招式",
    "Moves": "招式",
    "Moving to/from Let's Go resets AVs/EVs": "传入或传出 Let's Go 会重置觉醒值／努力值",
    "Nature": "性格",
    "New Backup": "新备份",
    "New Pokémon": "新建宝可梦",
    "New backup": "新备份",
    "New backup...": "新备份……",
    "Nickname": "昵称",
    "No Pokémon saves found for this user": "未找到该用户的宝可梦存档",
    "No Pokémon selected": "未选择宝可梦",
    "No box data available": "没有可用的盒子数据",
    "No changes made. Write anyway?": "没有任何更改，仍要写入吗？",
    "No free slot to clone into.": "没有可用于复制的空槽位。",
    "No items in this category": "此分类中没有道具",
    "No met-location list for this game.": "此游戏没有可用的相遇地点列表。",
    "No other item types available in this pocket.": "此口袋中没有其他可用道具。",
    "No problems found.": "未发现问题。",
    "No users found": "未找到用户",
    "No": "否",
    "None": "无",
    "Not recommended. Continue anyway?": "不建议这样操作，仍要继续吗？",
    "Nothing to sort in this box": "此盒子中没有可排序的宝可梦",
    "OFF": "关闭",
    "Off": "关闭",
    "On": "开启",
    "Origin": "初训家游戏",
    "Party": "同行宝可梦",
    "Plus": "加号键",
    "Pokemon ": "宝可梦 ",
    "Pokerus": "宝可病毒",
    "Pokémon Save Editor   v": "宝可梦存档编辑器   v",
    "Pokémon": "宝可梦",
    "Press A to open storage": "按 A 打开存储界面",
    "Randomize": "随机生成",
    "Release ": "放生",
    "Release": "放生",
    "Remove ": "移除",
    "Remove Item": "移除道具",
    "Remove": "移除",
    "Rename Bank Box": "重命名银行箱",
    "Rename Box": "重命名盒子",
    "Ribbons & Marks": "奖章与证章",
    "Ribbons": "奖章与证章",
    "Right": "右",
    "Save & Exit": "保存并退出",
    "Save Backups": "存档备份",
    "Save Changes": "保存更改",
    "Save bank changes?": "保存银行更改吗？",
    "Save": "保存",
    "Select Ability": "选择特性",
    "Select Ball": "选择精灵球",
    "Select Form": "选择形态",
    "Select Friendship": "选择亲密度",
    "Select Gender": "选择性别",
    "Select Held Item": "选择携带道具",
    "Select Language": "选择语言",
    "Select Level": "选择等级",
    "Select Met Level": "选择相遇等级",
    "Select Met Location": "选择相遇地点",
    "Select Move": "选择招式",
    "Select Nature": "选择性格",
    "Select Origin Game": "选择初训家游戏",
    "Select Species": "选择种类",
    "Select Stat Nature (mint)": "选择能力性格（薄荷）",
    "Select": "选择",
    "Settings": "设置",
    "Shield": "盾",
    "Shiny": "异色",
    "Slot ": "槽位 ",
    "SpA": "特攻",
    "SpD": "特防",
    "Spe": "速度",
    "Stat Nature": "能力性格",
    "Stat": "能力值",
    "Storage": "存储",
    "Summary": "能力",
    "That Pokémon is a party member — release it from the party first.": "该宝可梦仍在同行队伍中，请先将它移出队伍。",
    "The backup itself is written either way.": "无论如何都会写入备份本身。",
    "Theme": "主题",
    "This action cannot be undone.": "此操作无法撤销。",
    "This backup": "当前备份",
    "This can't be undone.": "此操作无法撤销。",
    "This game can't store those characters (A-Z, 0-9, and ! ? . - only).": "此游戏无法保存这些字符（仅支持 A-Z、0-9 和 ! ? . -）。",
    "This pocket is full.": "此口袋已满。",
    "Trainer ID": "训练家 ID",
    "Trainer": "训练家",
    "Unknown Item": "未知道具",
    "Unknown User": "未知用户",
    "Unsaved Changes": "未保存的更改",
    "Unsaved changes": "未保存的更改",
    "Up": "上",
    "Up/Down": "上／下",
    "Values": "数值",
    "Where should this be written?": "要写入到哪里？",
    "Working": "工作副本",
    "Write to game": "写入游戏",
    "Write to the game save?": "写入游戏存档吗？",
    "Written to the game save.": "已写入游戏存档。",
    "X: Keep": "X：保留",
    "X: Save": "X：保存",
    "Yes": "是",
    "You already have every item this pocket can hold.": "此口袋可容纳的道具已全部拥有。",
    "You have unsaved changes.": "你有尚未保存的更改。",
    "allow illegal values": "允许非法数值",
    "can't go in this game": "无法存入此游戏",
    "clear it": "清除",
    "create a new mon": "新建宝可梦",
    "create a new save": "创建新存档",
    "create new backup": "创建新备份",
    "current box": "当前盒子",
    "dark": "深色",
    "game save": "游戏存档",
    "in hand": "拿起中",
    "leave it alone": "保持不变",
    "legal": "合法",
    "light": "浅色",
    "name it with the keyboard": "使用键盘命名",
    "new": "新建",
    "no egg location": "无蛋获得地点",
    "no empty slot": "没有空槽位",
    "no saves": "没有存档",
    "none": "无",
    "nothing": "无",
    "open": "打开",
    "owned but empty": "已有但为空",
    "save": "保存",
    "saved": "已保存",
    "this Pokémon": "这只宝可梦",
    "this item": "此道具",
    "throw these away?": "要放弃这些更改吗？",
    "unsaved changes": "未保存的更改",
    "use the default": "使用默认值",
    " (M)": "（雄）",
    " (F)": "（雌）",
    "Lv. %u": "等级 %u",
    "Auto-Backup on Load": "载入时自动备份",
    "Allow Illegal Values": "允许非法数值",
    "Bank Storage Move Warning": "银行存储移动警告",
    "Bank Storage LGPE Move Warning": "银行存储 Let's Go 移动警告",
    "Allow Inject Backups to Game Save": "允许备份写入游戏存档",
    "Name": "名字",
    " in hand (": " 只拿起中（",
    "  (": "  （",
    "x": "×",
    ")": "）",
    "Selecting - A grabs the group": "选择中 - 按 A 拿起整组",
    "   A places them here": "   按 A 放在此处",
    "   won't fit here": "   此处空间不足",
    " in hand": " 只宝可梦拿起中",
    " Pokemon in hand": " 只宝可梦拿起中",
    "Release all": "全部放生",
    "Put back where they came from": "放回原来的位置",
    "Gen 3 has no nature field, so the PID is": "第三世代没有性格字段，因此会重新生成 PID",
    "regenerated to preserve it — the result": "以保留原性格；转换结果可能会被判定为",
    "may read as illegal, and nickname, ribbons": "非法，昵称、奖章与证章及携带道具也会",
    "and held item are dropped. Can't be undone.": "被移除。此操作无法撤销。",
    "to 0, removes held items, and drops any": "为 0、移除携带道具，并删除它无法合法",
    "move it can't legally learn.": "学会的招式。",
    "Trainer Name": "训练家名字",
    "OT name": "初训家名字",
    "This game allows at most ": "此游戏的训练家名字最多允许 ",
    " numbers in a trainer name.": " 个数字。",
    "Trainer name cleared.": "训练家名字已清除。",
    "Trainer name updated.": "训练家名字已更新。",
    " Updated OT on ": " 已更新 ",
    " of your Pokemon.": " 只属于你的宝可梦的初训家信息。",
    "Money set to $": "金钱已设为 $",
    "Written to backup \"": "已写入备份“",
    "Box renamed to \"": "盒子已重命名为“",
    "Bank box renamed to \"": "银行箱已重命名为“",
    "\".": "”。",
    "SAVE FAILED - your changes are still unsaved. Nothing was written.": "保存失败：更改仍未保存，未写入任何内容。",
    " damaged bank slot(s) could not be read and were skipped.": " 个损坏的银行槽位无法读取，已跳过。",
    " party-linked slot(s) stayed behind.": " 个与同行队伍关联的槽位已留在原处。",
    "That group doesn't fit here - move to a slot with room for it.": "此处放不下整组宝可梦，请移动到空间足够的槽位。",
    "conversion failed": "转换失败",
    "no transfer route": "没有可用的传送路径",
    " - still in hand": " - 仍拿在手中",
    " couldn't land on a party-linked slot - still in hand": " 只宝可梦无法放入与同行队伍关联的槽位，仍拿在手中",
    "Copied ": "已复制 ",
    " - originals left in place.": " 只宝可梦，原宝可梦保留在原处。",
    "This game can't store one of those characters.": "此游戏无法保存其中的某些字符。",
    " bank slot(s) failed the integrity check - see the PKSE log.": " 个银行槽位未通过完整性检查，请查看 PKSE 日志。",
    "R: Legality  |  ": "R：合法性  |  ",
    "Right: Values  |  ": "右：数值  |  ",
    "Left: Values  |  ": "左：数值  |  ",
    "Left: Details  |  Right: Moves  |  ": "左：详情  |  右：招式  |  ",
    "[illegal]  ": "[非法]  ",
    "[warning]  ": "[警告]  ",
    "This Pokémon has unsaved changes.": "这只宝可梦有尚未保存的更改。",
    "Discard loses them; Back keeps editing.": "放弃将丢失这些更改；返回可继续编辑。",
}

NAV_TRANSLATIONS = {
    "Arrows: Move  |  A: Select  |  Minus: Options  |  Y: Mode (Multi)  |  X: Sort Box  |  B: Clear": "方向键：移动  |  A：选择  |  -：选项  |  Y：模式（多选）  |  X：排序  |  B：清除",
    "Arrows: Move  |  L/R: Box  |  Y: Mode (Menu)  |  A: Menu  |  X: Sort Box  |  B: Back": "方向键：移动  |  L/R：盒子  |  Y：模式（菜单）  |  A：菜单  |  X：排序  |  B：返回",
    "Arrows: Move  |  L/R: Box  |  Y: Mode (Move)  |  A: Pick Up  |  X: Sort Box  |  B: Back": "方向键：移动  |  L/R：盒子  |  Y：模式（移动）  |  A：拿起  |  X：排序  |  B：返回",
    "Arrows: Move (cross panes at edge)  |  L/R: Box  |  A: Drop / Swap  |  B: Return": "方向键：移动（边缘可跨区域）  |  L/R：盒子  |  A：放下／交换  |  B：返回",
    "Arrows: Navigate  |  A: Open  |  B: Go Back  |  X: Save  |  +: Exit App": "方向键：导航  |  A：打开  |  B：返回  |  X：保存  |  +：退出应用",
    "Arrows: Navigate  |  L/R: Box  |  A: Create  |  B: Back": "方向键：导航  |  L/R：盒子  |  A：创建  |  B：返回",
    "Arrows: Navigate  |  L/R: Box  |  A: Details  |  X: Release  |  Y: Grab/Move  |  B: Back": "方向键：导航  |  L/R：盒子  |  A：详情  |  X：放生  |  Y：拿起／移动  |  B：返回",
    "Arrows: Navigate Grid  |  A: View Details  |  B: Back  |  +: Exit App": "方向键：网格导航  |  A：查看详情  |  B：返回  |  +：退出应用",
    "HOLDING  |  Arrows: Move Cursor  |  L/R: Change Box  |  Y: Drop Here  |  B: Cancel": "拿起中  |  方向键：移动光标  |  L/R：切换盒子  |  Y：放在此处  |  B：取消",
    "Left/Right: +/-1  |  Up/Down: +/-10  |  ZL/ZR: +/-100  |  A: Confirm  |  B: Cancel": "左/右：±1  |  上/下：±10  |  ZL/ZR：±100  |  A：确认  |  B：取消",
    "Up/Down: Category  |  A: Edit  |  B: Close": "上/下：分类  |  A：编辑  |  B：关闭",
    "Up/Down: Choose  |  A: Confirm  |  B: Stay": "上/下：选择  |  A：确认  |  B：留在此处",
    "Up/Down: Choose  |  A: Save  |  B: Cancel": "上/下：选择  |  A：保存  |  B：取消",
    "Up/Down: Choose  |  A: Select  |  B: Cancel": "上/下：选择  |  A：确定  |  B：取消",
    "Up/Down: IV/AV-EV  |  Arrows: +/- Value  |  A: Confirm  |  B: Cancel": "上/下：个体值/觉醒值-努力值  |  方向键：调整数值  |  A：确认  |  B：取消",
    "Up/Down: IV/AV-EV  |  Arrows: +/- Value  |  ZL/ZR: +/-100  |  A: Confirm  |  B: Cancel": "上/下：个体值/觉醒值-努力值  |  方向键：调整数值  |  ZL/ZR：±100  |  A：确认  |  B：取消",
    "Up/Down: Select  |  A: Edit  |  Y: Change View  |  B: Close  |  X: Save": "上/下：选择  |  A：编辑  |  Y：切换视图  |  B：关闭  |  X：保存",
    "Up/Down: Select  |  A: Edit Amount  |  Y: Add Item  |  X: Remove Item  |  Left/Right: Page  |  L/R: Category  |  B: Back": "上/下：选择  |  A：编辑数量  |  Y：添加  |  X：移除  |  左/右：翻页  |  L/R：分类  |  B：返回",
    "Up/Down: Select  |  A: Toggle  |  B: Back": "上/下：选择  |  A：切换  |  B：返回",
    "Up/Down: Select Category  |  A: Select Category  |  B: Close  |  X: Save  |  +: Exit App": "上/下：选择分类  |  A：确定  |  B：关闭  |  X：保存  |  +：退出应用",
    "Up/Down: Select Category  |  B: Close  |  X: Save  |  +: Exit App": "上/下：选择分类  |  B：关闭  |  X：保存  |  +：退出应用",
    "Up/Down: Select Category | A: Select Category  |  B: Close  |  X: Save  |  +: Exit App": "上/下：选择分类  |  A：确定  |  B：关闭  |  X：保存  |  +：退出应用",
    "Up/Down: Select Field  |  A: Edit Field |  B: Back  |  X: Save  |  +: Exit App": "上/下：选择字段  |  A：编辑  |  B：返回  |  X：保存  |  +：退出应用",
    "Up/Down: Select Field | A: Edit Field |  B: Back  |  X: Save  |  +: Exit App": "上/下：选择字段  |  A：编辑  |  B：返回  |  X：保存  |  +：退出应用",
    "Up/Down: Select Field | B: Back  |  X: Save  |  +: Exit App": "上/下：选择字段  |  B：返回  |  X：保存  |  +：退出应用",
    "Arrows: Size Selection  |  A: Grab Group  |  X: Copy Group  |  B: Cancel": "方向键：调整选择范围  |  A：拿起整组  |  X：复制整组  |  B：取消",
    "Arrows: Move Group (cross panes at edge)  |  L/R: Box  |  A: Place Here  |  Minus: Options  |  B: Put Back": "方向键：移动整组（边缘可跨区域）  |  L/R：盒子  |  A：放在此处  |  -：选项  |  B：放回",
    "Arrows: Move (cross panes at edge)  |  L/R: Box  |  A: Drop / Swap  |  Minus: Options  |  B: Put Back": "方向键：移动（边缘可跨区域）  |  L/R：盒子  |  A：放下／交换  |  -：选项  |  B：放回",
    "Arrows: Move  |  L/R: Box  |  Y: Mode (Multi)  |  A: Start Selection  |  X: Sort Box  |  B: Back": "方向键：移动  |  L/R：盒子  |  Y：模式（多选）  |  A：开始选择  |  X：排序  |  B：返回",
    "Up/Down: Select  |  A: Edit  |  B: Back  |  +: Exit App": "上/下：选择  |  A：编辑  |  B：返回  |  +：退出应用",
}

# Save revision labels are rendered in the title bar but originate in the
# trainer parsers, outside src/UI. Keep them here so re-running this script
# after an upstream merge cannot restore the English DLC names.
REVISION_TRANSLATIONS = {
    "Crown Tundra": "冠之雪原",
    "Isle of Armor": "铠之孤岛",
    "Mega Dimension": "超次元爆涌",
    "Rev ": "修订版 ",
    "The Indigo Disk": "蓝之圆盘",
    "The Teal Mask": "碧之假面",
}

REVISION_PATHS = (
    ROOT / "src" / "Trainer" / "Trainer8SWSH.cpp",
    ROOT / "src" / "Trainer" / "Trainer9LZA.cpp",
    ROOT / "src" / "Trainer" / "Trainer9SV.cpp",
)

# These values are part of the machine-readable test trace, not UI copy. Some of
# their tokens also appear as visible labels, so restore the complete expressions
# after applying the literal table above.
TRACE_RESTORATIONS = {
    'Utils::logField("reason", routed ? "转换失败"':
        'Utils::logField("reason", routed ? "conversion failed"',
    '" src=" + (this->loadedFromCart ? "CART" : "备份")':
        '" src=" + (this->loadedFromCart ? "CART" : "BACKUP")',
    '(g_injectToGameSave ? "ON" : "关闭")':
        '(g_injectToGameSave ? "ON" : "OFF")',
    '(g_allowIllegalEdits ? "ON" : "关闭")':
        '(g_allowIllegalEdits ? "ON" : "OFF")',
    '(g_autoBackupEnabled ? "ON" : "关闭")':
        '(g_autoBackupEnabled ? "ON" : "OFF")',
    '(g_lgpeMoveWarn ? "ON" : "关闭")':
        '(g_lgpeMoveWarn ? "ON" : "OFF")',
    '(g_moveWarn ? "ON" : "关闭")':
        '(g_moveWarn ? "ON" : "OFF")',
    '(g_themeMode == ThemeMode::Dark ? "深色" : "浅色")':
        '(g_themeMode == ThemeMode::Dark ? "dark" : "light")',
    '(injectToTitle ? "游戏" : "备份") +':
        '(injectToTitle ? "GAME" : "BACKUP") +',
    '(trainer.saveRevisionString.empty() ? "普通形态" : trainer.saveRevisionString)':
        '(trainer.saveRevisionString.empty() ? "Base" : trainer.saveRevisionString)',
    'trainer.saveRevisionString != "普通形态"':
        'trainer.saveRevisionString != "Base"',
}


def cpp_literal(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    mapping = {**TRANSLATIONS, **NAV_TRANSLATIONS}
    paths = list((ROOT / "src" / "UI").rglob("*.cpp"))
    paths += list((ROOT / "include" / "UI").rglob("*.h"))
    changed = 0
    for path in paths:
        text = path.read_text(encoding="utf-8")
        original = text
        for english, chinese in mapping.items():
            text = text.replace(cpp_literal(english), cpp_literal(chinese))
        if path.name == "TrainerViewScreen.cpp":
            for localized, protocol in TRACE_RESTORATIONS.items():
                text = text.replace(localized, protocol)
        if text != original:
            with path.open("w", encoding="utf-8", newline="\n") as fh:
                fh.write(text)
            changed += 1

    for path in REVISION_PATHS:
        text = path.read_text(encoding="utf-8")
        original = text
        for english, chinese in REVISION_TRANSLATIONS.items():
            text = text.replace(cpp_literal(english), cpp_literal(chinese))
        if text != original:
            with path.open("w", encoding="utf-8", newline="\n") as fh:
                fh.write(text)
            changed += 1
    print(f"Localized UI strings in {changed} files")


if __name__ == "__main__":
    main()
